SharedAnalog32( PV )
SharedAnalog32( MAXIMUM )
SharedAnalog32( MINIMUM )
SharedAnalog32( HH_LIMIT )
SharedAnalog32( H_LIMIT )
SharedAnalog32( L_LIMIT )
SharedAnalog32( LL_LIMIT )
SharedAnalog32( HYST )
SharedChars( DESCR, 512)
SharedChars(VALUE_FORMAT,64)
SharedChars(EU,64)
SharedDigital32(HH)
SharedDigital32(H)
SharedDigital32(L)
SharedDigital32(LL)
SharedDigital32(SetAck)
SharedDigital32(Acked)
SharedChars( DESCR1, 512)
SharedChars( DESCR2, 512)
SharedDigital32( SERVICE )
SharedDigital32(En_HH)
SharedDigital32(En_H)
SharedDigital32(En_L)
SharedDigital32(En_LL)
SharedDigital32( SERVICE_AlarmOn )
SharedDigital32( SERVICE_AlarmOff )
SharedDigital32( MODE )
SharedAnalog32 ( PVmA )
//для комиты
SharedDigital32(ImitOn)
SharedDigital32(SpeedOn)
SharedDigital32(FiltOn)
SharedDigital32(AlgOn)
SharedDigital32(CtrlHiHi)
SharedDigital32(CtrlHi)
SharedDigital32(CtrlLoLo)
SharedDigital32(CtrlLo)
SharedDigital32(CtrlHiScale)
SharedDigital32(CtrlLoScale)
SharedAnalog32( ImitVal )
SharedAnalog32( SpeedVal )
SharedAnalog32( FiltVal )
SharedDigital32( HiScale )
SharedDigital32( LoScale )
SharedDigital32( CtrlPreset )
// аларм флаги
SharedDigital32( AlarmEn )
SharedDigital32 (CtrlHiHiPrev)
SharedDigital32 (CtrlHiPrev)
SharedDigital32 (CtrlLoPrev)
SharedDigital32 (CtrlLoLoPrev)
SharedDigital32 (AlarmEnPrev)
SharedDigital32(CtrlHiHiAlarm)
SharedDigital32(CtrlHiAlarm)
SharedDigital32(CtrlLoLoAlarm)
SharedDigital32(CtrlLoAlarm)
SharedDigital32(CtrlHiHiOffAlarm)
SharedDigital32(CtrlHiOffAlarm)
SharedDigital32(CtrlLoLoOffAlarm)
SharedDigital32(CtrlLoOffAlarm)
SharedDigital32(FiltOnAlarm)
SharedDigital32(FiltOffAlarm)
SharedDigital32(SpeedOnAlarm)
SharedDigital32(SpeedOffAlarm)
SharedDigital32(AlgOnAlarm)
SharedDigital32(AlgOffAlarm)
SharedDigital32(ImitOnAlarm)
SharedDigital32(ImitOffAlarm)
SharedDigital32( HiScaleAlarm )
SharedDigital32( LoScaleAlarm )