SharedAnalog32Savebale(PV)
SharedAnalog32Savebale(SP)
SharedAnalog32Savebale(PREVSP)
SharedAnalog32Savebale(OP)
SharedAnalog32Savebale(PREVOP)
SharedDigital32Savebale(MODE)//ручной/автоматический/CAS
SharedDigital32(PREVMODE)
SharedAnalog32( MAXIMUM )
SharedAnalog32( MINIMUM )
SharedAnalog32( HH_LIM_PV )
SharedAnalog32( H_LIM_PV )
SharedAnalog32( L_LIM_PV )
SharedAnalog32( LL_LIM_PV )
SharedAnalog32( HYST )
SharedChars( DESCR, 512)
SharedChars(VALUE_FORMAT,64)
SharedChars(EU,64)
SharedDigital32(HH)
SharedDigital32(H)
SharedDigital32(L)
SharedDigital32(LL)
SharedChars( DESCR1, 512)
SharedChars( DESCR2, 512)
SharedAnalog32( MAX_OUT )
SharedAnalog32( MIN_OUT )
SharedDigital32( SetAck )
SharedDigital32( Acked )
SharedDigital32( IL_STATE )
SharedAnalog32( P )
SharedAnalog32( I )
SharedDigital32( INVERSE )
SharedAnalog32( MAX_SP )
SharedAnalog32( MIN_SP )
SharedAnalog32( D )
SharedDigital32Savebale( TRK_IND )
SharedAnalog32( SSV ) // SV Slow Increase/Decrease
SharedAnalog32( FSV ) // SV Fast Increase/Decrease
SharedAnalog32 (ActValueSSV)
SharedAnalog32 (ActValueFSV)
SharedAnalog32( SMV ) // MV Slow Increase/Decrease
SharedAnalog32( FMV ) // MV Fast Increase/Decrease
SharedAnalog32 (ActValueSMV)
SharedAnalog32 (ActValueFMV)
// Для комиты
SharedDigital32 ( AlgOn )
SharedDigital32 ( AlgFl  )
SharedDigital32 ( Repair )
SharedDigital32 ( NotAuto )
SharedAnalog32 (SetDeltaErr)
SharedAnalog32 (SetDeltaTime)
SharedAnalog32 (SetValOpened)
SharedAnalog32 (SetValClosed)
SharedDigital32 (Closed)
SharedDigital32 (Opened)
SharedDigital32 (AnCtrl)
SharedDigital32 (DeadZoneCtrl)
SharedDigital32 (CtrlProc)
SharedDigital32 (CtrlStatChain)
SharedDigital32 (PermCasMode)

// Флаги для алармов
SharedDigital32 (InversAlarmOn)
SharedDigital32 (InversAlarmOff)
SharedDigital32 (CtrlProcAlarmOn)
SharedDigital32 (CtrlProcAlarmOff)
SharedDigital32 (CtrlStatChainAlarmOn)
SharedDigital32 (CtrlStatChainAlarmOff)
SharedDigital32 (PermCasModeAlarm)
SharedDigital32 (AutoModeAlarm)
SharedDigital32 (ManModeAlarm)
SharedDigital32 (CasModeAlarm)
SharedDigital32 (AnCtrlAlarm)
SharedDigital32 (RepairAlarmOn)
SharedDigital32 (RepairAlarmOff)
SharedDigital32 (ChangeSpAlarm)
SharedDigital32 (ChangeOpAlarm)
