SharedDigital32Savebale(OP)
SharedDigital32Savebale(PV)
SharedDigital32Savebale(MODE)//ручной/автоматический
SharedChars(DESCR, 512)
SharedChars(EU,64)
SharedDigital32Savebale( ERR )
SharedChars( DESCR1, 512)
SharedChars( DESCR2, 512)
SharedDigital32Savebale( PERMISSIVE )
SharedDigital32( IL_STATE )
SharedDigital32( RESET )
SharedDigital32(SetAck)
SharedDigital32(Acked)
SharedDigital32( IL_Ind )
SharedDigital32 ( LocalMode )
SharedDigital32 ( DO )

// для комиты
SharedDigital32Savebale (AlgOn)
SharedDigital32 (AlgFl)
SharedDigital32Savebale (PermCount1)
SharedDigital32Savebale (StartCount1)
SharedDigital32Savebale (ResetCount1)
SharedDigital32Savebale (PermCount2)
SharedDigital32Savebale (StartCount2)
SharedDigital32Savebale (ResetCount2)
SharedDigital32 (Hour1)
SharedDigital32 (Minute1)
SharedDigital32 (Second1)
SharedDigital32 (Hour2)
SharedDigital32 (Minute2)
SharedDigital32 (Second2)
SharedDigital32 (Repair)
SharedAnalog32(TimeUpOpen)
SharedAnalog32(TimeDownOpen)
SharedAnalog32(TimeUpClose)
SharedAnalog32(TimeDownClose)
SharedAnalog32Savebale( AHOUR1 )
SharedAnalog32Savebale( AHOUR2 )
SharedDigital32 (Day1)
SharedDigital32 (Day2)


// флаги алармов
SharedDigital32 (AlgOnAlarm)
SharedDigital32 (AlgOffAlarm)
SharedDigital32 (RepairOnAlarm)
SharedDigital32 (RepairOffAlarm)
SharedDigital32 (DistModeOnAlarm)
SharedDigital32 (DistModeOffAlarm)
SharedDigital32 (AutoModeOnAlarm)
SharedDigital32 (AutoModeOffAlarm)
SharedDigital32 (OpenCmdAlarm)
SharedDigital32 (CloseCmdAlarm)
SharedDigital32 (ClosedAlarm)
SharedDigital32 (OpenedAlarm)