Enumeration_A(CONFIGCODE,"Configuration Code",8,None,Ok,Def=None)
Enumeration_A(CONFIGSTS,"Configuration Status",8,Ok,Information,Def=Ok)
Real_A(C,"Results of up to eight calculator expressions",8,0)
Enumeration_A(CSTS,"Expression Statuses",8,BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Enumeration_A(EXECCODE,"Execution Code",8,None,ConfigError,Def=None)
Enumeration_A(EXECSTS,"Execution Status",8,Ok,Bypass,Info,Warning,Fail,Error,Def=Ok)
Real_A(P,"Process Input Values 1 through 6",6,0)
Enumeration_A(PSTS,"Status of PV Input Values 1 through 6",6,Bad,Uncertn,Normal,Manual,Def=Bad)
Real(PV,"Function Block Output",0)// - The calculated output of an Auxiliary function block.
Enumeration(PVSTS,"Process Variable (PV) Status",Bad,Uncertain,Normal,Manual,Def=Bad)
Struct4B(PVSTSFL,"",BAD,MAN,NORM,UNCER)
StructRE(PVVALSTS,"",PV,PVSTS)
