Enumeration(BADCTLOPT,"Indicates what to do when Calculated Variable CV is NaN",No_Shed,ShedHold,ShedLow,ShedHigh,ShedSafe,Def=No_Shed)// (i.e., BADCTLFL = On).
Real_A(CVEUHI,"",8,100.)
Real_A(CVEULO,"",8,0.)
Enumeration(CVTYPE,"",EngineeringUnits,Percent,Def=EngineeringUnits)
String_K(DESC,"Block Descriptor",132*4)
Enumeration(ESWENB,"Ext Mode Switch Enable",DISABLE,ENABLE,Def=DISABLE)
Enumeration(ESWPERM,"",NOTPERM,PERMIT,Def=NOTPERM)
String_K(EUDESC,"Block Engineering Units Descriptor",24*4)
Real(GAINHILM,"Gain High Limit",240.)
Real(GAINLOLM,"Gain Low Limit",0.)
Enumeration(HOLDOPT,"The Hold State Option",None,Man,Auto,Cas,FixedOP,HoldPv,FixedSP,RampedSP,Def=None)
Real_A(INITVAL,"",8,0)
//Boolean_A(INSBLOCK,"",10,false)
Real_A(K,"Total Gain for Calculated Variable",8,1.0)
Enumeration(MODEPERM,"",NOTPERM,PERMIT,Def=PERMIT)
String_K(NAME,"",32*4)
Enumeration(NORMMODE,"",Man,Auto,Cas,Bcas,None,Def=None)
Enumeration(NORMMODEATTR,"",None,Operator,Program,Def=None)
Integer(NUMINSERT,"",0)
Integer(NUMPRI,"",0)
Struct_3R_A(OPBIAS,"",8,FIX,FLOAT,RATE)
Real(OPEXHILM,"OP Extended High Limit (in percentage)",106.9)
Real(OPEXLOLM,"OP Extended Low Limit (in percentage)",-6.9)
Real(OPHILM,"",105.)
Real(OPLOLM,"",-5.)
Real(OPMINCHG,"OP Minimum Change Limit (in Percent)",0)//
Real(OPROCLM,"OP Rate of Change Limit (in Percent per minute)",NaN)
//Integer(ORDERINCM,"Execution order",10)
Enumeration(OUTIND,"Output Indication",Direct,Reverse,DirectDisplnd,ReverseDisplnd,Def=Direct)
Enumeration(OUTTYPE,"Defines whether the connected output is a digial or analog type",Digital,Analog,Def=Analog)
Enumeration(RESTARTOPT,"Restart Option",None,LastReq,Def=None)//Indicates activity for device when ControlModule.SCMSTATE returns to Restarting or Running
Struct_BBEI(SIALM,FL,OPT,ALPRIOR,PR,SV)
Enumeration(SIOPT,"Indicates what to do when Calculated Variable CV is NaN",No_Shed,ShedHold,ShedLow,ShedHigh,ShedSafe,Def=No_Shed)// (i.e., BADCTLFL = On).
Real(SPHILM,"SP High Limit (in Engineering Units)",100.)//Defines the upper limit for the SP value
Real(XEUHI,"",100.)
Real(XEULO,"",0.)

Enumeration_A(РасчетCV,"",8,Честно,Брать_с_X1,Def=Честно)

Boolean(INALM,"",false)
Struct_EIE(HIALM,ALPRIOR,PR,SV,DACALMTYPE,TYPE)
Boolean_A(REQCHECK,"Check Request Flags",8,false)
Integer(lastOUT,"",0)
