String_K(NAME,"Имя",31*4)
//Integer_A(ASSOCBLOCK,1000,"Associated Block")
Integer(BADCODE,"Reason of Bad Status",0)
//String_K(BLCKCOMMENT1,40,"Block Comment 1")
//String_K(BLOCKTYPNAME,101,"Block Type Name")
Real(C1,"C1 Scale Factor",1.)
Real(C2,"C2 Scale Factor",1.)
Real(C3,"PL Scale Factor",1.)
//Integer(CBBLOCKPROP,"Block Property")
Enumeration(EDGEDETECT,"Edge Detection",FallingEdge,RisingEdge,Def=RisingEdge)
Integer(FETCHMODE,"Fetch Option",0)
//ENUM(FREQPERIOD,"25ms,50ms,100ms,200ms,500ms,1000ms,2000ms","Freq Integration Period")
Integer(IOCNUMBER,"Channel Number",0)
Integer(IOCTYPE,"Channel Type",0)
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Enumeration(PULSEMODE,"Pulse Measurement Mode",Period,PulseHigh,PulseLow,Def=PulseHigh)
//String_K(QUALSTATE,100,"Qualification State")
Enumeration(SIMMODE,"Simulation Mode",NONE,DIRECTSUB,SIMVALSUB,INITDISABLE,Def=NONE)
Real(SIMVALUE,"Simulated Value",0)
Enumeration(TIMEBASE,"Time Base",SECONDS,MINUTES,HOURS,Def=SECONDS)
Enumeration(UPDATOPT,"Update Option",CYCLE,TRIGGER,Def=CYCLE)
//Integer(X_BLOCKMEM,"Currently used memory (bytes)")
