Integer(ASTEPID,"Active STEP of Request",0)
Enumeration_A(ARWNET,"Network Windup Status",8,NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWNETIN,"Auxiliary Network Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWOP,"Output Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWOPIN,"Auxiliary Output Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Struct_BEI(BADCTLALM,FL,ALPRIOR,PR,SV)
/*STRUCT(BADCTLALM)
  ENUM_S(BADCTLALM,ALL,"",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  FLAG_S(BADCTLALM,FL,"Bad Ctl Alarm Flag")
  ENUM_S(BADCTLALM,PR,"Bad Ctl Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(BADCTLALM,SV,"Bad Ctl Alarm Severity")
STRUCT_END(BADCTLALM)*/
Boolean(BADCTLFL,"Bad Control Flag",false)
Real_A(C,"Expression Result",8,NaN)
Boolean(CASREQFL,"Cascade Request Flag",false)
Boolean(COMPUTEARW,"Recompute windup",false)
Enumeration_A(CONFIGCODE,"Config Code",10,None,Ok,UnknownError,ImplicitConv,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ConstExprRem,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,Def=Ok)
Enumeration_A(CONFIGSTS,"Config Status",10,Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=Error)
Enumeration_A(CSTS,"Expression Result Status",8,BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Boolean(CTLINIT,"Control Init Flag",false)
Enumeration(CTLSTATE,"Control state",FWD,HOLD,INIT,MAN,Def=FWD)
Real(CV,"Calculated Variable",NaN)
Real(CVINIT,"CV at Initialization",NaN)
Real(CVORFB,"CV at Override Feedback",NaN)
Struct4B(ESWFL,"",AUTO,BCAS,CAS,MAN)
/*STRUCT(ESWFL)
  FLAG_S(ESWFL,ALL,"")
  FLAG_S(ESWFL,AUTO,"Auto Ext Mode Switch")
  FLAG_S(ESWFL,BCAS,"Bcas Ext Mode Switch")
  FLAG_S(ESWFL,CAS,"Cas  Ext Mode Switch")
  FLAG_S(ESWFL,MAN,"Man  Ext Mode Switch")
STRUCT_END(ESWFL)*/
Enumeration(FBORSTS,"FB Override Status",NOTCON,SEL,NOTSEL,Def=NOTCON)
String_A(EXECDESC,"ExecCode Desc",39 * 4,10)
Enumeration_A(EXECSTS,"Execution Status",10,Ok,Bypass,Info,Warning,Fail,Error,Def=Bypass)
Boolean(INITMAN,"FB In-Init Flag",false)
Boolean_A(INITREQ,"Init Request for Primary",8,false)
Enumeration(LASTMODEREQ,"Last MODEREQ in RUN",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Real(LASTOPREQ,"Last OPREQ in RUN", NaN)
Enumeration(LASTOPTYPE,"Last OPTYPE in RUN",Null,SET,NOTSTORED,DEFAULT,Def=Null)
Boolean(LASTREQFL,"Last Requested Par Flag",false)
Integer(LASTSTEP,"Last SCO STEP in RUN",0)
Enumeration(MODE,"Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=MAN)
Boolean_A(MODEAPPL,"Mode Applicability Flags",4,false)
Boolean(MODECHANGE,"First time mode Change",false)
Enumeration(MODEREQ,"Requested Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Integer(NUMONESHOT,"# of Oneshot Requests",0)
Integer(NUMPROPREQ,"# of Propaga Requests",0)
Real(OP,"OP Value in %",0)
Real(OPBIAS_TOTAL,"Total Output Bias",0)
Real(OPEU,"OP Value in EUs",NaN)
Boolean(OPEXHIFL,"OP Extended High Flag",false)
Boolean(OPEXLOFL,"OP Extended Low Flag",false)
Boolean(OPHIFL,"OP High Limit Flag",false)
Boolean(OPLOFL,"OP Low Limit Flag",false)
Real(OPREQ,"Requested OP Value",0)
Boolean(OPROCNEGFL,"OP Neg Rate-of-Chng Flag",false)
Boolean(OPROCPOSFL,"OP Pos Rate-of-Chng Flag",false)
Boolean(SIFL,"Safety Interlock Flag",false)
Boolean(TMOUTFL,"Timeout Flag",false)
Real_A(X,"X Input Value",6,NaN)
Real_A(XKB,"X input after Gain & Bias",6,NaN)
Enumeration_A(XSTS,"X Input Status",6,BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Boolean(XWHIFL,"Input Windup High Flag",false)
Boolean(XWLOFL,"Input Windup Low Flag",false)

Real(X1BACKCALOUT,"",NaN)
Real(BACKCALCIN,"",NaN)