String_K(NAME,"",32*4)
//Integer(ORDERINCM,"Execution order",10)
//INTEGER_A(ASSOCBLOCK,1000,"Associated Block")
//INTEGER(CBBLOCKPROP,"Block Property")
//INTEGER(NUMBLOBS,"Number of Dynamic State Blobs")
//STRING(QUALSTATE,100,"Qualification State")
Real(ROLLACCUM,"internal accumulation of samples",0)
Integer(ROLLAVGSZ,"Size of RollAvg sample buffer",0)
Enumeration(ROLLBFBASE,"RollAvg collection - units of time",SECONDS=1,MINUTES=60,HOURS=3600,Def=MINUTES)
Integer(ROLLBUF,"RollAvg collection - time span",1)
Integer(ROLLCOUNTER,"internal counter to next execute",0)
Enumeration(ROLLFRBASE,"RollAvg frequency -units of time",SECONDS=1,MINUTES=60,HOURS=3600,Def=SECONDS)
Integer(ROLLFREQ,"RollAvg frequency -time span",1)
//DOUBLE(ROLLSAMPLE,"internal pointer to samples buff")
//FLAG(X_ALLOWEXECBB,"Allow executing Basic Block")
//INTEGER(X_BLOCKMEM,"Currently used memory (bytes)")
