//ID=156
String_K(NAME,"Имя",32*4)
//String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
//String_K(BLKTYPE,"Block Type",33*4)
//Integer(CBBLOCKPROP,"Block Property")
//Enumeration(CHKPNTST,"Checkpoint State",Invalid,Valid,NotLoaded,Reading,Writing,Restored,DbValidRestored,Def=)
//Boolean(COMMFAILFL,"Communications Failure",false)
//Integer(CONTAINEDIN,"Contained in")
String_K(DESC,"Description",132*4)
//String_K(DEVICELOCATION,"Associated Device Location",64*4)
//Enumeration(DOSTYPE,"DO Slot Type",NONE,UNKNOWN,SONOTCONF,SOPOINT,SOCOMPONENT,ONPULSE,OFFPULSE,OPNOTCONF,OPPOINT,OPCOMPONENT,Def=)
Enumeration(DOTYPE,"DO Type",Status,PWM,OnPulse,OffPulse,Def=Status)
//Enumeration(FAULTOPT,"Fault Option",Hold,Unpower,Power,UseFaultValue,Def=)
//String_K(FAULTOPTENUMMASK,"Not Visible, Fault Option Enumeration Mask",64*4)
Real(FAULTVALUE,"Fault Value",NaN)
Enumeration(I1INPTDIR,"Interlock 1 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I2INPTDIR,"Interlock 2 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I3INPTDIR,"Interlock 3 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I4INPTDIR,"Interlock 4 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I5INPTDIR,"Interlock 5 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I6INPTDIR,"Interlock 6 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I7INPTDIR,"Interlock 7 Input Direction",Direct,Reverse,Def=Direct)
Enumeration(I8INPTDIR,"Interlock 8 Input Direction",Direct,Reverse,Def=Direct)
//Enumeration(ICONSTATE,"Channel Icon State",Inactive,Active,Error,Def=)
//Enumeration(INITPNTTYPE,"Load First Point Type Configuration for UIO Channels",NULL,AI,AO,DI,DO,DigCom,RegPV,RegCtl,Logic,Array,Flag,Numeric,ProcModl,Timer,DevCtl,SVP,SP,PI,UIO,Def=)
//Boolean(INITREQ,"Initialize Request",false)
//Boolean(INITREQLATCH,"Initialize Request Latched",false)
Integer_A(INLCKINPTSRC,"Interlock Input Source",8,0)
//Integer(IOP,"Associated IOM")
//Enumeration(IOPTYPE,"Associated IOM Type",SP,Def=)
Enumeration(MODEPERM,"Mode Permissive",NotPerm,Permit,Def=NotPerm)
//Enumeration(MONACTCMD,"Enum for activate",INACTIVE,ACTIVE,Def=)
//String_K(MONCMDPARAM,"Parameter stores activation",64*4)
//Enumeration(MONINACTCMD,"Enum for inactivate",INACTIVE,ACTIVE,Def=)
//Enumeration(MONLDCMD,"Value prior to load",INACTIVE,ACTIVE,Def=)
//String_K(MONREADPARAM,"Parameter to be monitored",64*4)
//Enumeration(MONRQDLD,"Required load state",INACTIVE,ACTIVE,Def=)
Enumeration_A(MONSTATES,"Enum values for each state",3,Inactive,Active,Error,Def=Inactive)
Enumeration(NMODATTR,"Normal Mode Attribute",None,Operator,Program,Normal,Def=None)
Enumeration(NMODE,"Normal Mode",None,Man,Cas,Normal,Def=None)
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Real(OPINITVAL,"OP Initialize Value",NaN)
Enumeration(OPTDIR,"Output Direction",Direct,Reverse,Def=Direct)
//Integer(ORDERINCM,"Execution Order in CM")
//Enumeration(PNTTYPE,"Point Type",NULL,AI,AO,DI,DO,DigCom,RegPV,RegCtl,Logic,Array,Flag,Numeric,ProcModl,Timer,DevCtl,SVP,SP,PI,UIO,Def=)
//Enumeration(PTEXECST,"Point Execution State",Inactive,Active,Def=)
//String_K(QUALSTATE,"Qualification State",100*4)
//Boolean(REDTAG,"Red Tag",false)
Real(PERIOD,"PWM Period",NaN)
Enumeration(SIMMODE,"Simulation Mode",NONE,DIRECTSUB,SIMVALSUB,INITDISABLE,Def=NONE)
Real(SIMVALUE,"Simulated Value",0)
Boolean(SOINITVAL,"SO Initialize Value",false)
Boolean(SOREADFAIL,"SO Initialize Value Invalid",false)
Boolean(STDBYMAN,"Standby Manual Enabled",false)
