String_K(NAME,"",32*4)
String_K(DESC,"Description",132*4)
//Integer(ORDERINCM,"Execution order",10)
Boolean(BORDER,"",false)
Integer(BKGCOLOR,"",0)
Integer(TEXTCOLOR,"",0)
String_K(TEXTCOMMENT,"",132*4)
Integer(TEXTSIZE,"",10)
String_K(FONTSTYLE,"",32*4)