String_K(NAME,"Имя",31*4)
Boolean(ALMENBSTATE,"Alarming Enabled",0)
//Integer(ASAERRINFO,"Additional Error Info")
//String_K(ASAPATH,64,"ASA path of the IO Module")
//Integer(ASMINSTANCE,"Assembly Instance")
String_K(ASSOCASSET,"Associated Asset",132*4)
//Integer_A(ASSOCBLOCK,1000,"Associated Block")
String_A(AUXDESC,"Auxiliary Descriptor",24 * 4,10)
//String_K(BLCKCOMMENT1,40,"Block Comment 1")
String_K(BLOCKTYPNAME,"Block Type Name",101*4)
Real_A(CALBIAS,"Calibration Bias (f)",6,0)
//Integer(CATNUMBER,"Catalog Number")
//Integer(CBBLOCKPROP,"Block Property")
Integer_A(CFGFLG,"Channel Configuration",6,0)
Integer_A(CHANNUM,"Channel Number",6,0)
Integer_A(CHANTYPE,"Channel Type",6,0)
//Boolean(CJDISABLE,"Cold Junction Disable")
//Real(CJOFFSET,"Cold Junction Offset")
//Integer(CONFREV,"Config rev number")
//Integer(CONFSIZE,"Configuration Size")
//Integer(CONFTYPE,"Configuration Id. Num.")
Integer(CONNTYPE,"Connection Type",0)
//Boolean(CONTCUTOUT,"Alarming Contact CutOut")
//Boolean(CTRLCONFIRM,"Control Confirmation")
Integer(CTRLFLG,"Config RTP,IF,CJ,Temp",0)
//String_K(CURRENTREL,64,"Database Release")
String_K(DESC,"Module Description",132*4)
Integer_A(DIGFILTER,"Digital Filter (msec)",6,0)
//Integer(DLCNBSLOT,"Downlink CNI Slot Number")
String_K(EENAME,"Execution Environment name",16*4)
Real(ESTWEIGHT,"Estimated Weight",NaN)
String_K(EUDESC,"Engineering Units",24*4)
Integer(FTEBBLOCK,"FTE Bridge Name",0)
Integer(GENSTS,"General Status",0)
String_K(GOBACKREL,"Previous DB Release",64*4)
/*STRUCT(GROUP)
Integer_SA(GROUP,NUMBER,25,"Group Number")
Integer_S(GROUP,NUMPARAMS,"Number of Group parameters")
STRUCT_END(GROUP)*/
//String_K(HELPTXT1,128,"HelpTxt1")
Boolean_A(HIGHALARM,"High Alarm Boolean",6,0)
/*STRUCT(HIST)
Boolean_SA(HIST,EXC,25,"Exception Collection Type")
Integer_SA(HIST,EXCCOLLRATE,25,"Collection Rate for Exception History Collection Type")
Integer_SA(HIST,EXCOFFSET,25,"Collection Rate Offset for Exception History Collection Type")
Boolean_SA(HIST,EXTD,25,"Extended Collection Type")
Boolean_SA(HIST,FAST,25,"Fast Collection Type")
Integer_SA(HIST,FASTCOLLRATE,25,"Collection Rate for Fast History Collection Type")
String_SA(HIST,GATEString,25,255,"Gating Parameter String")
String_SA(HIST,GATEVALUE,25,255,"Gating Parameter value")
Integer_S(HIST,NUMPARAMS,"Number of History parameters")
Boolean_SA(HIST,STD,25,"Standard Collection Type")
Integer_SA(HIST,STDCOLLRATE,25,"Collection Rate for Standard History Collection Type")
Integer_SA(HIST,STDOFFSET,25,"Collection Rate Offset for Standard History Collection Type")
String_SA(HIST,TYPE,25,255,"History Type")
STRUCT_END(HIST)*/
Boolean(IFTRANS,"Idle/Fault Trans Enable",0)
//String_K(IMAGEVER,31,"Image Version")
//Integer(INCONNPT,"Input Conn Point")
//Integer(INCONNSIZE,"Input Conn Size")
//ENUM_A(INPUTRANGE,6,"-12_to_78mV,-12_to_30mV","Input Range")
Integer(IOMSLOT,"IOM Slot Number in Chassis",0)
String_K(IOMTYPE,"IO Module Type",64*4)
Enumeration(IOSCHEDOPT,"I/O Schedule Option",NotIOM,OutputModule,MixedModule,InputModule,Def=NotIOM)
Boolean(JOURNALONLY,"Alarming JOURNAL ONLY",0)
//Integer(KEYMASK,"Key Mask")
//String_K(KEYWORD,16,"Keyword Description")
//Integer(LOADID,"ERDB / Controller load consistency ID")
Real_A(HIGHENG,"High Engineering (f)",6,NaN)
Real_A(HIGHSIGNAL,"High Signal",6,NaN)
Real_A(LOWENG,"Low Engineering (f)",6,NaN)
Real_A(LOWSIGNAL,"Low Signal",6,NaN)
//Integer(MAJORREV,"Major Revision")
//Integer(MAPENTRYTYPE,"Map Entry Type")
//Integer(MAPINSTANCE,"Map Instance")
//Integer(MINORREV,"Minor Revision")
//Integer(NAME,"Provide the name for tagged objects")
//ENUM_A(NOTCHFILTER,6,"50Hz,60Hz","Notch Filter")
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Integer(NUMCHANS,"Number of Channels",0)
//Integer(NUMCONN,"Number of Connections")
//Integer(NUMDISCONN,"Number of Disconnects")
//Integer(NUMSHUTDOWN,"Number of Shutdowns")
Enumeration(NUMSIGS,"Electronic Signature Type",NONE,SINGLE,Real,Def=NONE)
//ENUM(OCDEXECSTATE,"INACTIVE,ACTIVE","CheckPointed Execution State")
Integer_A(OHMOFFSET,"10 Ohm Offset",6,0)
Integer(ORDERINCEE,"Execution Order in CEE",0)
//Integer(ORDERINCM,"Execution Order in CM")
//Integer(OTSCHEDULE,"O-T Schedule")
//Integer(OUTCONNPT,"Output Conn Point")
//Integer(OUTCONNSIZE,"Output Conn Size")
String_K(PARENTASSET,"Parent Asset:",132*4)
String_K(PCMNAME,"Platform block name",16*4)
//ENUM(PERIOD,"DEFAULT,5mS,10mS,20mS,50mS,100mS,200mS,500mS,1sec,2sec,5sec,10sec,20sec,25mS,NONE,30sec,1min,2min,5min,10min,20min,30min,1hr,2hr,4hr,8hr,12hr,24hr,40mS,400mS,80mS,800mS","Execution Period")
Real(PERIODSEC,"Execution Period in Seconds",1)
//Integer(PHASE,"Execution Phase")
//Integer(PHASEHOUR,"Execution Phase Hour")
//Integer(PHASEMIN,"Execution Phase Minute")
//String_K(PRIMARYSIG,24,"Primary Signature Meaning")
//Integer(PRODTYPE,"Product Type")
Integer(PUBRATE,"Update Rate in usec",0)
Real_A(PVALDB,"Alarm Deadband",6,NaN)
Real_A(PVHHTP,"High High Alarm",6,NaN)
Real_A(PVHITP,"High Alarm",6,NaN)
Real_A(PVLLTP,"Low Low Alarm",6,NaN)
Real_A(PVLOTP,"Low Alarm",6,NaN)
String_K(QUALSTATE,"Qualification State",6*4)
Integer_A(RATEALARM,"Rate Alarm",6,0)
//Integer(READSTATUS,"Read Status")
//Integer(REASONSET,"Reason Set Number")
//ENUM(RECONFIGSTAT,"None,InProgress,Success,Failed,Abnormal,5,6","Reconfiguration Status")
//Boolean(RTPPRESENT,"RTP Present")
//Integer(SAMPLERATE,"Sample Rate (msec)")
//Real(SCALEPERIOD,"Scale Period")
//String_K(SCANAREA,40,"SCAN Area")
//String_K(SCANASSOCDSP,255,"SCAN Associated Display")
//Integer(SCANCTRLLVL,"SCAN Control Level")
String_K(SCANEUHI,"SCAN EUHI Parameter",255*4)
String_K(SCANEULO,"SCAN EULO Parameter",255*4)
//String_K(SCANGRPDTL,255,"SCAN Group Detail Page")
//String_K(SCANPNTDTL,255,"SCAN Point Detail Page")
//Integer(SCHEDPOS,"Position in scheduler chain (internal use)")
//Integer(SCHEDULECOP,"Schedule COP")
String_K(SECONDARYSIG,"Secondary Signature Meaning",24*4)
Enumeration(SECSIGSECLVL,"Sec Signer Security Level",VIEWONLY,ACKONLY,OPER,SUPV,ENGR,MNGR,Def=VIEWONLY)
Enumeration_A(SENSORTYPE,"Sensor Type",6,mV,B,C,E,J,K,N,R,S,T,D,L,Def=mV)
//Enumeration_A(SIPTYPE,"Channel Type",6,10V_Input,RTD_SIP,Thermocouple,10V_Output,4-20mA_Cur)
Integer(STUBIOM,"Stub IO Module",0)
Enumeration(TEMPMODE,"Temperature Mode",Celsius,Fahrenheit,Def=Fahrenheit)
//Integer(TOSCHEDULE,"T-O Schedule")
/*STRUCT(TREND)
Integer_SA(TREND,NUMBER,32,"Trend Number")
Integer_S(TREND,NUMPARAMS,"Number of Trend parameters")
ENUM_SA(TREND,POSITION,32,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,None","Trend Position")
STRUCT_END(TREND)
*/
//Integer(ULCNBMAC,"Uplink CNI Address in IO Rack")
//Boolean_A(UNDERRANGE,6,"Under Range Alarm Exist")
