Integer(ASACONNSTS,"Connection Status",0x4000)
Integer(ASAERRCODE,"Error Code",0)
Integer(ASAERRINFO,"Additional Error Info",0)
Enumeration(CEESTATE,"CEE State",IDLE,RUN,FAIL,NotLoaded,Def=IDLE)
Boolean(CHANTEXT,"",0)//Channel In Use - Indicates whether the Channel is currently being used (a value of On)or not (a value of Off).
Enumeration(EXECSTATE,"Execution State",INACTIVE,ACTIVE,Def=INACTIVE)
Enumeration( HIALM,"",NoAlarm,Config,OPHi,OPLo,AdvDev,DevHi,DevLo,SafetyIlock,BadCtl,BadCompTerm,Def=NoAlarm)
Enumeration_A(IOCCONN,"Currently Assigned Channels",16,INCONN,OUTCONN,PCONN,Def=INCONN)
            /*NoAlarm: (0) No alarm exists; this is the lowest-level alarm condition.
            Config: (1) Configuration alarm
            OPHi (2) OP High alarm
            OPLo (3) OP Low alarm
            AdvDev (4) Advisory Deviation alarm
            DevHi (5) Deviation High alarm
            DevLo (6) Deviation Low alarm
            SafetyIlock (7) Safety Interlock alarm
            BadCtl (8) Bad Control alarm
            BadCompTerm (9) Bad CompTerm alarm
            */
Boolean(INALM,"In-Alarm Flag",0)
Enumeration(IOMSTATE,"IOM State",INACTIVE,OK,FAIL,STBY,START,STUB,Def=INACTIVE)
Enumeration(SIMSTATE,"Simulation State",NONE,SIMRUN,SIMFREEZE,SIMDISABLE,Def=NONE)
Real_A(HIGHENG,"High Engineering (f)",16,NaN)
Real_A(HIGHSIGNAL,"High Signal",16,NaN)
//KEYWORD
//Integer(NUMDISCONN,"Number of Disconnects",0)
//Integer(NUMSHUTDOWN,"Number of Shutdowns",0)
//PHASE
//SCANASSOCDSP
//SCANGRPDTL
//SCANPNTDTL
//UPDATOPT
Enumeration(IOCONNSTATUS,"IO Connection Status",BadSchedule,CommError,ConfigError,Connected,ConnInUse,IomNotFound,NoConfig,NoKeeper,NoSchedule,NotConnected,WrongModule,unknown,Def=unknown)
Boolean(LOWALARM,"Low Alarm Flag",0)
/*
STRING(ASAPATH,64,"ASA path of the IO Module")
INTEGER(ASMINSTANCE,"Assembly Instance")
STRING(ASSOCASSET,132,"Associated Asset")
INTEGER_A(ASSOCBLOCK,1000,"Associated Block")
STRING_A(AUXDESC,10,24,"Auxiliary Descriptor")
FLAG_A(BADCAL,16,"Bad Calibration Status")
STRING(BLCKCOMMENT1,40,"Block Comment 1")
STRING(BLOCKTYPNAME,101,"Block Type Name")
DOUBLE_A(CALBIAS,16,"Calibration Bias (f)")
INTEGER(CBBLOCKPROP,"Block Property")
INTEGER_A(CFGFLG,16,"Channel Configuration")
INTEGER_A(CHANNUM,16,"Channel Number")
INTEGER_A(CHANSTS,16,"Channel Status")
INTEGER_A(CHANTYPE,16,"Channel Type")
FLAG(CJDISABLE,"Cold Junction Disable")
DOUBLE(CJOFFSET,"Cold Junction Offset")
INTEGER(CONFREV,"Config rev number")
INTEGER(CONFSIZE,"Configuration Size")
INTEGER(CONFTYPE,"Configuration Id. Num.")
INTEGER(CONNTYPE,"Connection Type")
FLAG(CONTCUTOUT,"Alarming Contact CutOut")
FLAG(CTRLCONFIRM,"Control Confirmation")
INTEGER(CTRLFLG,"Config RTP,IF,CJ,Temp")
STRING(CURRENTREL,64,"Database Release")
STRING(DESC,132,"Module Description")
INTEGER_A(DIGFILTER,16,"Digital Filter (msec)")
STRING(EENAME,16,"Execution Environment name")
INTEGER(FTEBBLOCK,"FTE Bridge Name")
INTEGER(GENSTS,"General Status")
STRING(GOBACKREL,64,"Previous DB Release")
STRUCT(GROUP)
INTEGER_SA(GROUP,NUMBER,25,"Group Number")
INTEGER_S(GROUP,NUMPARAMS,"Number of Group parameters")
STRUCT_END(GROUP)
STRING(HELPTXT1,128,"HelpTxt1")
FLAG(HIGHALARM,"High Alarm Flag")
STRUCT(HIST)
FLAG_SA(HIST,EXC,25,"Exception Collection Type")
INTEGER_SA(HIST,EXCCOLLRATE,25,"Collection Rate for Exception History Collection Type")
INTEGER_SA(HIST,EXCOFFSET,25,"Collection Rate Offset for Exception History Collection Type")
FLAG_SA(HIST,EXTD,25,"Extended Collection Type")
FLAG_SA(HIST,FAST,25,"Fast Collection Type")
INTEGER_SA(HIST,FASTCOLLRATE,25,"Collection Rate for Fast History Collection Type")
STRING_SA(HIST,GATESTRING,25,255,"Gating Parameter String")
STRING_SA(HIST,GATEVALUE,25,255,"Gating Parameter value")
INTEGER_S(HIST,NUMPARAMS,"Number of History parameters")
FLAG_SA(HIST,STD,25,"Standard Collection Type")
INTEGER_SA(HIST,STDCOLLRATE,25,"Collection Rate for Standard History Collection Type")
INTEGER_SA(HIST,STDOFFSET,25,"Collection Rate Offset for Standard History Collection Type")
STRING_SA(HIST,TYPE,25,255,"History Type")
STRUCT_END(HIST)
FLAG(IFTRANS,"Idle/Fault Trans Enable")
STRING(IMAGEVER,31,"Image Version")
INTEGER(INCONNPT,"Input Conn Point")
INTEGER(INCONNSIZE,"Input Conn Size")
ENUM_A(INPUTRANGE,16,"-10V_to_10V,0V_to_5V,0V_to_10V,4mA_to_20mA","Input Range")
FLAG(JOURNALONLY,"Alarming JOURNAL ONLY")
INTEGER(KEYMASK,"Key Mask")
//STRING(KEYWORD,16,"Keyword Description")
INTEGER(LOADID,"ERDB / Controller load consistency ID")
INTEGER(MAPENTRYTYPE,"Map Entry Type")
INTEGER(MAPINSTANCE,"Map Instance")
INTEGER(NAME,"Provide the name for tagged objects")
ENUM(NOTCHFILTER,"20Hz","3DB Filter")
INTEGER(NUMBLOBS,"Number of Dynamic State Blobs")
ENUM(NUMSIGS,"NONE,SINGLE,DOUBLE","Electronic Signature Type")
ENUM(OCDEXECSTATE,"INACTIVE,ACTIVE","CheckPointed Execution State")
INTEGER(OHMOFFSET,"10 Ohm Offset")
INTEGER(OTSCHEDULE,"O-T Schedule")
INTEGER(OUTCONNPT,"Output Conn Point")
INTEGER(OUTCONNSIZE,"Output Conn Size")
FLAG_A(OVERRANGE,16,"Over Range Alarm Exist")
STRING(PARENTASSET,132,"Parent Asset:")
STRING(PCMNAME,16,"Platform block name")
DOUBLE(PERIODSEC,"Execution Period in Seconds")
INTEGER(PHASE,"Execution Phase")
INTEGER(PHASEHOUR,"Execution Phase Hour")
INTEGER(PHASEMIN,"Execution Phase Minute")
STRING(PRIMARYSIG,24,"Primary Signature Meaning")
INTEGER(PUBRATE,"Update Rate in usec")
DOUBLE(PVALDB,"Alarm Deadband")
DOUBLE(PVHHTP,"High High Alarm")
DOUBLE(PVHITP,"High Alarm")
DOUBLE(PVLLTP,"Low Low Alarm")
DOUBLE(PVLOTP,"Low Alarm")
DOUBLE_A(PVRAW,16,"PV from AI Device")
STRING(QUALSTATE,100,"Qualification State")
INTEGER(RATEALARM,"Rate Alarm")
INTEGER(READSTATUS,"Read Status")
INTEGER(REASONSET,"Reason Set Number")
ENUM(RECONFIGSTAT,"None,InProgress,Success,Failed,Abnormal,5,6","Reconfiguration Status")
FLAG(RTPPRESENT,"RTP Present")
INTEGER(SAMPLERATE,"Sample Rate (msec)")
DOUBLE(SCALEPERIOD,"Scale Period")
STRING(SCANAREA,40,"SCAN Area")
//STRING(SCANASSOCDSP,255,"SCAN Associated Display")
//STRING(SCANGRPDTL,255,"SCAN Group Detail Page")
//STRING(SCANPNTDTL,255,"SCAN Point Detail Page")
INTEGER(SCHEDPOS,"Position in scheduler chain (internal use)")
INTEGER(SCHEDULECOP,"Schedule COP")
STRING(SECONDARYSIG,24,"Secondary Signature Meaning")
ENUM(SENSORTYPE,"Ohms,100_Pt_385,200_Pt_385,500_Pt_385,1000_Pt_385,100_Pt_3916,200_Pt_3916,500_Pt_3916,1000_Pt_3916,10_Cu_427,120_Ni_672,100_Ni_618,120_Ni_618,200_Ni_618,500_Ni_618","Sensor Type")
ENUM(SIPTYPE,"10V_Input,RTD_SIP,Thermocouple,10V_Output,4-20mA_Cur","Channel Type")
INTEGER(STUBIOM,"Stub IO Module")
INTEGER(TOSCHEDULE,"T-O Schedule")
STRUCT(TREND)
INTEGER_SA(TREND,NUMBER,32,"Trend Number")
INTEGER_S(TREND,NUMPARAMS,"Number of Trend parameters")
ENUM_SA(TREND,POSITION,32,"1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,None","Trend Position")
STRUCT_END(TREND)
FLAG_A(UNDERRANGE,16,"Under Range Alarm Exist")
INTEGER(X_BLOCKMEM,"Currently used memory (bytes)")
ENUM(X_NOTIF_ID,"DO NOT USE,BADCTL,OPHIGH,OPLOW,REGSI,DEVHI,DEVLOW,ADVDEV,UNCMDCHG,PREDPVHI,PREDPVLO,PIDPLBADPV","Alarm condition strings")
*/