#include "./DCUVId.h"
#define DCU_PRODUCTVERSION DCU_VMaj_Id,DCU_VMin_Id,DCU_Build_IdH,DCU_Build_IdL
#define DCU_PRODUCTVERSION_STR DCU_Version_Str
#define DCU_FILEVERSION DCU_PRODUCTVERSION
#define DCU_FILEVERSION_STR DCU_PRODUCTVERSION_STR
#define DCU_COMPANYNAME    "T-Soft\0"
#define DCU_SHORTCOPYRIGHT "Copyright (c) 2024 T-Soft\0"
#define DCU_PRODUCTNAME    "RSU Emulator\0"
