;************************************************************************/
;*****     COPYRIGHT 1997           HONEYWELL LIMITED AUSTRALIA      ****/
;************************************************************************/
;
; $Workfile$	$Revision$
;


[UserMenuAppTags]
20000=%showHelpOperator%
20001=startapp.exe 1
20002=startapp.exe 3
20498=qckbld
20499=dspbld
20500=dspbld %DisplayName%























































[Display Menu Tags]
22000=
22001=sysGrpSummary
22002=sysRptSummary
22003=sysStsSumPntSrv
22004=sysTndSummary
22005=syslicence
22006=sysCfgStnSummary
22007=sysCfgSumPntSrv
22008=sysCfgRedundantServer
22009=sysCfgAssetProfSumm
22010=sysCfgAssetListSumm
22011=sysCfgAssetTPSumm
22012=
22013=syscfgalmpgrcomms
22014=sysHstStd
22015=sysCfgHistoryArchive
22016=sysCfgRptSummary
22017=sysCfgPntCtrlSchedule
22018=sysTndConfigSummary
22019=sysGrpConfigSummary
22020=sysSPQCSumm
22021=sysCfgScriptingGeneral
22022=sysCfgScriptingAutomatic
