;This is a Configuration setting file for stb file migration.It contains migratted ;htm files corresponding to a dsp files.
[Migration_Displays]
sys004.dsp = sysstsflexsummary
sys011.dsp = sysmnu
sysMnuConfiguration = sysmnu
sys119.dsp = sysstsdstsummary
sys198.dsp = sysstsPrntSummary
sysCfgAssetDataPntSrv.dsp = sysCfgAssetDataPntSrv 
sysCfgAssetPntSrvPMD.dsp = sysCfgAssetPntSrvPMD
sysCfgAssetOPC.dsp = sysCfgAssetOPC
sysCfgAssetTPS.dsp = sysCfgAssetTPS
sysCfgAttribOPC.dsp = sysCfgAttribOPC
sysCfgConDetail.dsp = sysCfgConDetail
sysCfgConKeyboard.dsp = sysCfgConKeyboard
sysCfgConOptions.dsp = sysCfgConOptions
sysCfgCStnDetail.dsp = sysCfgCStnDetail
sysCfgCStnKeyboard.dsp = sysCfgCStnKeyboard
sysCfgDataFormat.dsp = sysCfgDataFormat
sysCfgDataPntSrv.dsp = sysCfgDataPntSrv
sysCfgDtlDataPntSrv.dsp = sysCfgDtlDataPntSrv
sysCfgDtlOPC.dsp = sysCfgDtlOPC
sysCfgDtlOPCDisplay.dsp = sysCfgDtlOPCDisplay
sysCfgDtlPntSrvPMD.dsp = sysCfgDtlPntSrvPMD
sysCfgDtlTPS.dsp = sysCfgDtlTPS
sysCfgOPC.dsp = sysCfgOPC
sysCfgOPCDisplay.dsp = sysCfgOPCDisplay
sysCfgPntSrvPMD.dsp = sysCfgPntSrvPMD
sysCfgTPS.dsp = sysCfgTPS
sysDtlFileReplication.dsp = sysDtlFileReplication
sysGrpSummary.dsp = sysGrpSummary
sysstsConSummary.dsp = sysstsConSummary
sysStsCStnDetail.dsp = sysStsCStnDetail
sysCfgCStnOptions.dsp = sysCfgCStnOptions
sysStsCStnSummary.dsp = sysStsCStnSummary
sysStsDataPntSrv.dsp = sysStsDataPntSrv
sysStsOPC.dsp = sysStsOPC
sysStsOPCDisplay.dsp = sysStsOPCDisplay
sysStsPntSrvPMD.dsp = sysStsPntSrvPMD
sysStsTPS.dsp = sysStsTPS
sysLicence = sysLicence
sysLicenceOptions = sysLicenceOptions
sysLicenceInter = sysLicenceInter
sysLicenceETR = sysLicenceETR
sysCfgFileReplication = sysCfgFileReplication
syscfgconsummary = syscfgconsummary
syscfgcstnsummary = syscfgcstnsummary
sys197 = sysCfgPrntSummary
sysCfgPrinter = sysCfgPrinter
sys113.dsp = sysserversredsts
sysCfgRedundantServer = sysCfgRedundantServer
sys117 = syscfgdsasvr
sysCfgIkbColors = sysCfgIkbColors
sysCfgSYSMGT = sysCfgSYSMGT
sysStsSYSMGT.dsp = sysStsSYSMGT
sysCfgDtlSYSMGT = sysCfgDtlSYSMGT
syscfgmigrateserver = syscfgmigrateserver
sysCfgElecSigGeneral = sysCfgElecSigGeneral
sysCfgSumElecSigReason = sysCfgSumElecSigReason
sysCfgElecSigReason = sysCfgElecSigReason
sysCfgRptServerWide = sysCfgRptServerWide 
sys076 = syscfgholschedule
sys083 = syscfgshfschedule
sysGrpConfigSummary = sysGrpConfigSummary
sys229 = syscfgrecsumm
sys230 = syscfgdtlrec
sysMnuControllerApps = sysMnuControllerApps
sys172 = syscfgcntrlpointprogsumm
sys174 = syscfgcntrlrecsumm
sysCfgDataFormatsUnscaled = sysCfgDataFormatsUnscaled
sysCfgDataFormatsScaled = sysCfgDataFormatsScaled
sys008.dsp = sysCfgServerSettings
sys009.dsp = sysCfgStnDetails
sys066.dsp = sysCfgChannelSts
sys068.dsp = sysCfgControllerSts
sys069.dsp = sysSCADAControllers
syscfgsumcntrlr.dsp = sysSCADAControllers
sys145.dsp = sysCfgEvtArchOperate
sysCfgHistoryArchive.dsp = sysCfgHistoryArchive
sysServersCfg.dsp = sysServersCfg
sysServersCfgDtl.dsp = sysServersCfgDtl
sys123 = sysServersLclAlm
sysCfgPntSrv.dsp = sysCfgPntSrv
sysCfgPointProcessing.dsp = sysCfgPointProcessing
sysCfgSumPntSrv.dsp = sysCfgSumPntSrv
sysCfgStnSummary.dsp = sysCfgStnSummary
sys065.dsp = sysStsChannelSummary
sys144.dsp = sysCfgEvtArchConfig
sysRptSummary.dsp = sysRptSummary
sysCfgRptSummary.dsp = sysCfgRptSummary
sysServersLclCfg.dsp = sysServersLclCfg
sysServersLclDtl.dsp = sysServersLclDtl
sysServersLclNoLic.dsp = sysServersLclNoLic
sysServersLclSts.dsp = sysServersLclSts
sysCfgAssetPntSrv.dsp = sysCfgAssetPntSrv
sysCfgDtlPntSrv.dsp = sysCfgDtlPntSrv
sysCfgTypPntSrv.dsp = sysCfgTypPntSrv
sysStsPntSrv.dsp = sysStsPntSrv
sys010.dsp = syschnStats
sys013.dsp = syscfgkeyF1
sys014.dsp = syscfgkeyF21
sys015.dsp = syscfgkeyF41
sys016.dsp = syscfgkeyF61
sys017.dsp = syscfgkeyF81
sys057.dsp = syscfgappdevSinewave
sys064.dsp = sysCfgControllerConfig
sys070.dsp = sysCfgChannelConfig
sys071.dsp = sysCfgOperSumm
sys118.dsp = sysserversLclSts
sys133.dsp = SysCfgAppDevWatchdogTimers
sys137.dsp = syscfgareaconfig
sys139.dsp = SysCfgAppDevTaskTimers
sys141.dsp = syscfgsignonadministration
sys147.dsp = sysCfgConnections
sys190.dsp = SysCfgAppDevSummary
sys191.dsp = sysCfgAppConfig
sys192.dsp = SysCfgAppDevPointLists
sys193.dsp = SysCfgAppPntList
sys205.dsp = sysGrpDetail
sys206.dsp = sysGrpTrend
sys207.dsp = sysgrpnumeric
sys219.dsp = syscfgOperAssetAssignment
sys231.dsp = sysCfgAlarmMessages
sys240.dsp = syscfgmicromaxprocesses
sysAlgo004.dsp = sysAlgo004
sysAlgo005.dsp = sysAlgo005
sysAlgo007.dsp = sysAlgo007
sysAlgo008.dsp = sysAlgo008
sysAlgo010.dsp = sysAlgo010
sysAlgo011.dsp = sysAlgo011
sysAlgo012.dsp = sysAlgo012
sysAlgo015.dsp = sysAlgo015
sysAlgo016.dsp = sysAlgo016
sysAlgo021.dsp = sysAlgo021
sysAlgo022.dsp = sysAlgo022
sysAlgo064.dsp = sysAlgo064
sysAlgo065.dsp = sysAlgo065
sysAlgo067.dsp = sysAlgo067
sysAlgo068.dsp = sysAlgo068
sysAlgo069.dsp = sysAlgo069
sysAlgo070.dsp = sysAlgo070
sysAlgo071.dsp = sysAlgo071
sysAlgo072.dsp = sysAlgo072
sysAlgo074.dsp = sysAlgo074
sysAlgo075.dsp = sysAlgo075
sysAlgo076.dsp = sysAlgo076
sysAlgo077.dsp = sysAlgo077
sysAlgo078.dsp = sysAlgo078
sysAlgo079.dsp = sysAlgo079
sysAlgo080.dsp = sysAlgo080
sysAlgo092.dsp = sysAlgo092
sysCfgAlarmColors.dsp = syscfgalarmappearence
syscfgalarmeventdisplays.dsp = syscfgalarmeventdisplays
sysCfgAlmPgrComms.dsp = sysCfgAlmPgrComms
sysCfgAlmPgrModem.dsp = sysCfgAlmPgrModem
sysCfgAlmPgrSetup.dsp = sysCfgAlmPgrSetup
sysCfgAlmPgrSpecAlms.dsp = sysCfgAlmPgrSpecAlms
sys072.dsp = sysCfgKey10fn
sys076.dsp = syscfgholschedule
sys082.dsp = syscfgalarmprocessing
sys083.dsp = syscfgshfschedule
sys112.dsp = sysCfgKey12fn
sys144.dsp = sysCfgEvtArchConfig
sys145.dsp = sysCfgEvtArchOperate
sys147.dsp = sysCfgConnections
sys172.dsp = syscfgcntrlpointprogsumm
sys174.dsp = syscfgcntrlrecsumm
sys197.dsp = sysCfgPrntSummary
sys198.dsp = sysstsPrntSummary
sys213.dsp = sysCfgOperGeneral
sys218.dsp = sysCfgStnAssetAsn
sys229.dsp = syscfgrecsumm
sys230.dsp = syscfgdtlrec
sys236.dsp = sysCfgOperStation
sysCfgAlarmPriority.dsp = syscfgalarmprocessing
sysChnStats2.dsp = syschnstats
sysChnStats3.dsp = syschnstats
sysChnStats4.dsp = syschnstats
sysChnStats5.dsp = syschnstats
sysServersSysWide.dsp = sysServersCfgDtl
sysStsSumCntrlr.dsp = sysSCADAControllers
sysCfgAreaProfSumm.dsp = sysCfgAssetProfSumm
sysCfgAreaListSumm.dsp = sysCfgAssetListSumm
sysCfgAreaTPSumm.dsp = sysCfgAssetTPSumm














