//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(['text!./actionButtonTemplate.htm'], function(ActionButtonViewTemplate) {
    var ActionButtonShape = {
        // The shape config will be set in the init() function.
        _config: {}
    };
	
	ActionButtonShape.init = function(config) {
        ActionButtonShape._config = config;
        return true;
    };
	
    ActionButtonShape.getViewTemplates = function() {
		return {
			extActionButtonViewTemplate: ActionButtonViewTemplate
		};
	};

	ActionButtonShape.createViewModel = function() {
		return 'PointParamViewModel';
	};

	return ActionButtonShape;

});
