#include "stdafx.h"
// #include "stdafx.cpp"
// #include "Valve_A_b.cpp"
// #include "Valve_A_b_Calc.cpp"
// #include "Valve_A_b_Defects.cpp"
#include "Valve_A_b_dll.cpp"
// #include "Valve_A_b_Param.cpp"
//#include "Valve_A_b_Hydro.cpp"