PrivateAnalog32Savebale( A )
PrivateAnalog32Savebale( B )
PrivateAnalog32Savebale( C )
PrivateAnalog32Savebale( D )
PrivateAnalog32Savebale( O1 )
PrivateAnalog32Savebale( O2 )
PrivateAnalog32Savebale( O3 )
PrivateAnalog32Savebale( O4 )
PrivateConstString(F1)
PrivateConstString(F2)
PrivateConstString(F3)
PrivateConstString(F4)