//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(
    [
        'jquery',
        'asari/util/AsariFunctionalLogger',
        'knockout',
        'kendo',
        'knockout-kendo'
    ],

    function ($, log, ko, kendo, koKendo) {
        var PipelineGraphicBinding = {
            shapesPath: null
        }

        _renderElevations = function (datasource, elevations, pressureJson) {

		var re = /{(.*?),(.*?)}/g;
		var newElevationDS = new kendo.data.DataSource();
		var elevationArray = new kendo.data.ObservableArray([]);

		if (elevations != null) {
			var elevationsJson = elevations.replace(re, '{\"distance\":$1,\"elevation\":$2}');
			var elevationObjs = JSON.parse(elevationsJson);
			for (var i = 0; i < elevationObjs.length; i++) {
				elevationArray.push(elevationObjs[i]);
			}
		}

		if (pressureJson != null) {
			var pressureObjs = JSON.parse(pressureJson);
			for (var j = 0; j < pressureObjs.length; j++) {
				elevationArray.push(pressureObjs[j]);
			}
		}

		newElevationDS.data(elevationArray.toJSON());
		datasource.setDataSource(newElevationDS);
	}

        PipelineGraphicBinding.init = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
            var chart3 = {
                series: [
                {
                    name: "ElevationProfile",
                    type: "scatterLine",
                    xField: "distance",
                    yField: "elevation",
                    color: "#e0e0e0",
                    width: 2,
                    markers: { visible: false },
                    yAxis: "elevation",
                    style: "smooth",
                    markers: { visible: false }
                }, {
                    name: "PressureProfile",
                    type: "scatterLine",
                    xField: "distance",
                    yField: "pressure",
                    color: "#808080",
                    width: 2,
                    labels: { visible: true, template: "#= value.y #", color: "white", background: "#808080", opacity: 1, font: "12px 'Honeywell Sans Web'", position: "right", margin: { bottom: 20 }, padding: { top: 1, bottom: 1, left: 3, right: 3 } },
                    markers: { visible: false },
                    yAxis: "pressure"
                }],
                yAxes: [
                    {
						labels: {font: "12px 'Honeywell Sans Web'"},
                        name: "pressure",
                        title: { text: "kPa", rotation: 0, position: "bottom", margin: { bottom: -15, right: -20 }, font: "12px 'Honeywell Sans Web'"},
                        majorUnit: 500
                    }, {
						labels: {font: "12px 'Honeywell Sans Web'"},						
                        name: "elevation",
                        title: { text: "m", rotation: 0, position: "bottom", margin: { bottom: -15, left: -20 }, font: "12px 'Honeywell Sans Web'" }
                    }],
                xAxis: { axisCrossingValues: [0, 100000], visible: false },
                chartArea: { height: 240 },
                plotArea: { margin: { top: 10, bottom: 0, left: 60, right: 85 } },
                transitions: false,
                legend: { position: "bottom", labels: {font: "12px 'Honeywell Sans Web'"}},
                panes: [{ clip: false }]
            };



            ko.bindingHandlers.kendoChart.options = chart3;
            //var initial = valueAccessor();
            //initial.legend = { visible: false}
            ko.bindingHandlers.kendoChart.init(element, valueAccessor, allBindingsAccessor, viewModel);
        }

        PipelineGraphicBinding.update = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

            var ds = $(element).data("kendoChart");
            var valAccessor = valueAccessor();

            var distancemax = ko.utils.unwrapObservable(valAccessor.distance.source.value);
            var distanceunit = ko.utils.unwrapObservable(valAccessor.distance.source.units);
            var elevations = ko.utils.unwrapObservable(valAccessor.pipelineElevations.source.value);
            var pressureprofile = ko.utils.unwrapObservable(valAccessor.pressureprofile.source.value);

            this._renderElevations(ds, elevations, pressureprofile);

            // ----------------------------------------------
            //  set graphic maximum and unit of measurement
            // ----------------------------------------------	
            ds.options.xAxis.max = distancemax;
            ds.options.xAxis.title.text = distanceunit;

            ds.refresh();

        }



        return PipelineGraphicBinding;
    });
