//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(
    [
        'jquery',
        'asari/util/AsariFunctionalLogger',
        'knockout',
        'kendo',
        'knockout-kendo'
    ],

    function ($, log, ko, kendo, koKendo) {
        var PipelineGraphicBinding = {
            shapesPath: null
        }

        _updateBatchNotification = function (point) {
            var template = kendo.template("#= batchname # \n arriving in #=arrivaltime#");
            var data = { batchname: point.dataItem.name, arrivaltime: point.dataItem.arrival };
            return template(data);

        };

        _defineBatchColor = function (batch) {

            switch (batch.style) {
                case 0:
                    batch.valueColor = "#5B6275";
                    break;
                case 1:
                    batch.valueColor = "#6E869E";
                    break;
                case 2:
                    batch.valueColor = "#BFD99C";
                    break;
                case 3:
                    batch.valueColor = "#8DC9EE";
                    break;
                default:
                    batch.valueColor = "#ffffff";
                    break;
            }
        };


        // ----------------------------------------------
        // Interpret batch list
        // ----------------------------------------------   
        _renderBatches = function (datasource, serverjson, lPosition) {

            var newDS = new kendo.data.DataSource();
            var jsonbatch = JSON.parse(serverjson);
            var batcharray = new kendo.data.ObservableArray([]);

            var flagbatch = true;

            if (serverjson != null) {

                var i = jsonbatch.length;
                while (i--) {
                    if ((!jQuery.isEmptyObject(jsonbatch[i])) && (jsonbatch[i].type != "Segment")) {
                        this._defineBatchColor(jsonbatch[i]);

						// adjust batch location
						jsonbatch[i].location += lPosition
						
                        if (jsonbatch[i].arrival != "-" && flagbatch == true) {

                            if (jsonbatch[i].style != 3) {
                                jsonbatch[i].noteText = "location";

                                flagbatch = false;
                            }
                        }
                    }
                    if (jsonbatch[i].type != "Segment")
                      batcharray.push(jsonbatch[i]);
                }
            }

            newDS.data(batcharray.toJSON());
            newDS.group({ field: "order" });
            datasource.setDataSource(newDS);
        };
        
        // ----------------------------------------------
        // Interpret node locations
        // ----------------------------------------------
        _renderNodes = function (datasource, serverjson, lAlarm, lLocation, lPosition){

            var jsonnode = JSON.parse(serverjson);
            var nodearray = new kendo.data.ObservableArray([]);

            var nodeAdditionalStyles = ko.toJS({ "color": "#E0E0E0", "length": 10 });
            var leakNodeAdditionalStyles = ko.toJS({ "color": "#0096d7", "length": 0 });
            if (serverjson != null) {
                for (var i = 0; i < jsonnode.length; i++) {
					// absolute node position
					jsonnode[i].value += lPosition;

                    // style unavailable on element in defaultseries
                    jsonnode[i].label.margin = ko.toJS(33);
                    jsonnode[i].label.font = "12px 'Honeywell Sans Web'";
                    jsonnode[i].label.color = ko.toJS("black");
                    
                    nodearray.push(jsonnode[i]);
                    
                    jsonnode[i].label.margin = ko.toJS(48);
                    jsonnode[i].label.font = "bold 14px 'Honeywell Sans Web'";
                    jsonnode[i].label.color = ko.toJS("black");
                    jsonnode[i].label.text = jsonnode[i].label.altText;
                    
                    nodearray.push(jsonnode[i]);
                    
                    jsonnode[i].line = nodeAdditionalStyles;
                    jsonnode[i].label.margin = ko.toJS(0);
                    jsonnode[i].label.color = ko.toJS("#C0C0C0");
                    jsonnode[i].label.font = ko.toJS("48px Honeywell_Icons");
                    jsonnode[i].label.text = jsonnode[i].type;
                    nodearray.push(jsonnode[i]);
                }
                // Add the leak indicator
                if (lAlarm > 0)
                {
                    var temp = {};
                    jsonnode.push(jsonnode[jsonnode.length - 1]);
                    jsonnode[jsonnode.length - 1].label.color = ko.toJS("black");
                    jsonnode[jsonnode.length - 1].line = leakNodeAdditionalStyles;
                    jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-35);
                    jsonnode[jsonnode.length - 1].label.font = ko.toJS("24px FontAwesome");
                    jsonnode[jsonnode.length - 1].label.text = String.fromCharCode(61507); // Hex value f043                  

                    if (lAlarm == 1){
                        jsonnode[jsonnode.length - 1].value = ko.toJS(lLocation);
                        jsonnode[jsonnode.length - 1].line = leakNodeAdditionalStyles;
                        
                        jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-40);
						jsonnode[jsonnode.length - 1].label.font = ko.toJS("32px Honeywell_Icons");
                        jsonnode[jsonnode.length - 1].label.color = ko.toJS("#FFC626");
                        jsonnode[jsonnode.length - 1].label.text = "t";
                        nodearray.push(jsonnode[jsonnode.length - 1]);
						
						jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-40);
                        jsonnode[jsonnode.length - 1].label.color = ko.toJS("black");
                        jsonnode[jsonnode.length - 1].label.text = "T";
                        nodearray.push(jsonnode[jsonnode.length - 1]);
                        
                        jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-40);
                        jsonnode[jsonnode.length - 1].label.color = ko.toJS("black");
                        jsonnode[jsonnode.length - 1].label.text = "!";
                        nodearray.push(jsonnode[jsonnode.length - 1]);
                    }
                    
                    if (lAlarm == 2){
                        jsonnode[jsonnode.length - 1].value = ko.toJS(lLocation);
                        jsonnode[jsonnode.length - 1].line = leakNodeAdditionalStyles;
                        
                        jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-40);
						jsonnode[jsonnode.length - 1].label.font = ko.toJS("32px Honeywell_Icons");
                        jsonnode[jsonnode.length - 1].label.color = ko.toJS("#EF3124");
                        jsonnode[jsonnode.length - 1].label.text = "s";
                        nodearray.push(jsonnode[jsonnode.length - 1]);
						
						jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-40);
                        jsonnode[jsonnode.length - 1].label.color = ko.toJS("black");
                        jsonnode[jsonnode.length - 1].label.text = "S";
                        nodearray.push(jsonnode[jsonnode.length - 1]);
                        
                        jsonnode[jsonnode.length - 1].label.margin = ko.toJS(-40);
                        jsonnode[jsonnode.length - 1].label.color = ko.toJS("white");
                        jsonnode[jsonnode.length - 1].label.text = "!";
                        nodearray.push(jsonnode[jsonnode.length - 1]);
                    }
                }
            }

            datasource.options.valueAxis.notes.data = nodearray.toJSON();
        };
        
        _showtooltip = function (point) {

            var template = "";
            if (point.dataItem.style != 3) {
                if (point.dataItem.arrival == "") {
                    var templatecontent = kendo.template("<table id=\"tooltip\"><tr><th>#= b #</th></tr><tr><td>delivering</td></tr></table>");
                    template = templatecontent({ b: point.dataItem.name });
                }
                else {
                    var templatecontent = kendo.template("<table id=\"tooltip\"><tr><th>#= b #</th></tr><tr><td>arriving in: #: a #</td></tr></table>");
                    template = templatecontent({ b: point.dataItem.name, a: point.dataItem.arrival });
                }
            }
            return template;
        }
        
        PipelineGraphicBinding.init = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

            var chart1 = {
                series: [{ field: "location", colorField: "valueColor", categoryField: "type", overlay: { gradient: "none" } }],
                seriesDefaults: {
                    column: { color: "red" },
                    type: "bar",
                    gap: 0,
                    stack: true,
                    notes: { visible: false },
                    visual: function (e) {
                        //set up label
                        var labelText = new kendo.drawing.Text(e.dataItem.name);
                        var labelBBox = labelText.bbox();

                        // position batch label
                        var labelTargetPoint = { x: e.rect.topLeft().x, y: e.rect.center().y };
                        labelText.position([labelTargetPoint.x + 5, labelTargetPoint.y - (labelBBox.height() / 2)]);
                        labelText.options.font = "bold 12px 'Honeywell Sans Web'";
                        labelText.options.fill.color = "black"; // CJC - Label within

                        var defaultVisual = e.createVisual();
                        return new kendo.drawing.Group().append(defaultVisual, labelText);
                    }
                },
                legend: { visible: false },
                valueAxis: {
                    name: "distanceAxis",
                    title: { text: "km", position: "left", margin: { top:0, left:-28, bottom:-15 },	font: "12px 'Honeywell Sans Web'" },
                    line: { visible: false },
                    min: 0,
                    minorGridLines: { visible: true },
                    notes: { // Nodes attached to the pipeline
                        position: "up", visible: true,
                        label: {  position: "outside",
                                  visible: true,
                                  color: "#D0D0D0"
                        },
                        icon: { visible : false }
                    },
                },
                categoryAxis: {
                    majorGridLines: { visible: false }, visible: false,
                    axisCrossingValue: [0]
                },
                chartArea: { height: 140 },
                plotArea: { margin: { top: 70, bottom: 0, left: 100, right: 90 } },
                transitions: false,
                panes: [{ clip: false }]
            };

            ko.bindingHandlers.kendoChart.options = chart1;
            ko.bindingHandlers.kendoChart.init(element, valueAccessor, allBindingsAccessor, viewModel);
        }

        PipelineGraphicBinding.update = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

            var ds = $(element).data("kendoChart");
            var valAccessor = valueAccessor();

            var batchlist = ko.utils.unwrapObservable(valAccessor.batches.source.value);
            var nodelist = ko.utils.unwrapObservable(valAccessor.nodes.source.value);
            var distancemax = ko.utils.unwrapObservable(valAccessor.distance.source.value);
            var distanceunit = ko.utils.unwrapObservable(valAccessor.distance.source.units);
            var leakAlarm = ko.utils.unwrapObservable(valAccessor.routeLeak.source.value);
            var leakLocation = ko.utils.unwrapObservable(valAccessor.routeLeakLocation.source.value);
			var routePos = ko.utils.unwrapObservable(valAccessor.routePos.source.value);

            this._renderBatches(ds, batchlist, routePos);
            this._renderNodes(ds, nodelist, leakAlarm, leakLocation, routePos);

            // ----------------------------------------------
            //  set graphic maximum and unit of measurement
            // ----------------------------------------------	
            ds.options.valueAxis.max = routePos + distancemax;
			ds.options.valueAxis.min = routePos;
            ds.options.valueAxis.title.text = distanceunit;
			ds.options.valueAxis.labels.font = "12px 'Honeywell Sans Web'";

			

            ds.refresh();

        }



        return PipelineGraphicBinding;
    });
