//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(
    [
        'jquery',
        'asari/util/AsariFunctionalLogger',
        'knockout',
        'kendo',
        'knockout-kendo'
    ],

    function ($, log, ko, kendo, koKendo) {
        var PipelineSegmentBinding = {
            shapesPath: null
        }

        // ----------------------------------------------
        // Interpret batch list
        // ----------------------------------------------   
        _renderSegmentBatches = function (datasource, serverjson) {

            var newDS = new kendo.data.DataSource();
            var jsonbatch = JSON.parse(serverjson);
            var batcharray = new kendo.data.ObservableArray([]);

            var flagbatch = true;

            if (serverjson != null) {

                var i = jsonbatch.length;
                while (i--) {
                      if ((!jQuery.isEmptyObject(jsonbatch[i])) && (jsonbatch[i].type == "Segment")) {
                        jsonbatch[i].valueColor = "#D8D8D8";

                        if (jsonbatch[i].arrival != "-" && flagbatch == true) {

                            if (jsonbatch[i].style != 3) {
                                jsonbatch[i].noteText = "location";

                                flagbatch = false;
                            }
                        }
                    }
                    if (jsonbatch[i].type == "Segment")
                      batcharray.push(jsonbatch[i]);
                }
            }

            log.debug("PipelineSegmentBinding.js " + ko.toJSON(batcharray));
            newDS.data(batcharray.toJSON());
            newDS.group({ field: "order" });
            datasource.setDataSource(newDS);

        };

        // ----------------------------------------------
        // Interpret node locations
        // ----------------------------------------------
        _renderSegmentNodes = function (datasource, serverjson) {

            var jsonnode = JSON.parse(serverjson);
            var nodearray = new kendo.data.ObservableArray([]);

            var nodeAdditionalStyles = ko.toJS({ "color": "#0096d7", "length": 5 });
            if (serverjson != null) {
                for (var i = 0; i < jsonnode.length; i++) {
                    // style unavailable on element in defaultseries
                    if (jsonnode[i].label.text == "leak") {
                        jsonnode[i].label.color = ko.toJS("red");

                    } else {
                        jsonnode[i].line = nodeAdditionalStyles;
                    }
                    nodearray.push(jsonnode[i]);
                }
            }
            log.debug("PipelineSegmentBinding.js  " + ko.toJSON(nodearray));

            datasource.options.valueAxis.notes.data = nodearray.toJSON();
        };

        _showtooltip = function (point) {

            var template = "";
            if (point.dataItem.style != 3) {
                if (point.dataItem.arrival == "") {
                    var templatecontent = kendo.template("<table id=\"tooltip\"><tr><th>#= b #</th></tr><tr><td>delivering</td></tr></table>");
                    template = templatecontent({ b: point.dataItem.name });
                }
                else {
                    var templatecontent = kendo.template("<table id=\"tooltip\"><tr><th>#= b #</th></tr><tr><td>arriving in: #: a #</td></tr></table>");
                    template = templatecontent({ b: point.dataItem.name, a: point.dataItem.arrival });
                }
            }
            return template;
        }
        
        PipelineSegmentBinding.init = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

            var chart2 = {
                series: [{ field: "location", colorField: "valueColor", overlay: { gradient: "none" }, gap: 0, margin: 0, spacing: 0 }],
                seriesDefaults: { type: "bar", stack: true, gap: 0 },
                title: { visible: false },
                legend: { visible: false },
                valueAxis: {  line: { visible: false },
                              minorGridLines: { visible: false },
                              majorGridLines: { visible: false},
                              visible: false },
                categoryAxis: { visible: false, majorGridLines: { visible: false } },
                chartArea: { height: 14,  margin: { top: 0, bottom: -28, left: 108, right: 108 } },
                transitions: false
            };



            ko.bindingHandlers.kendoChart.options = chart2;
            ko.bindingHandlers.kendoChart.init(element, valueAccessor, allBindingsAccessor, viewModel);
        }

        PipelineSegmentBinding.update = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {

            var ds = $(element).data("kendoChart");
            var valAccessor = valueAccessor();

            var batchlist = ko.utils.unwrapObservable(valAccessor.batches.source.value);
            var distancemax = ko.utils.unwrapObservable(valAccessor.distance.source.value);

            this._renderSegmentBatches(ds, batchlist);

            // ----------------------------------------------
            //  set graphic maximum and unit of measurement
            // ----------------------------------------------	
            ds.options.valueAxis.max = distancemax;

            ds.refresh();

        }



        return PipelineSegmentBinding;
    });
