cmake_minimum_required (VERSION 3.10) 
set(CMAKE_FOLDER ".RSUs/HoneyWell5xx/DCUs")

set(PROJECT_NAME ControlBuilderH)
include(../../../../global.cmake)

set(Headers
	"AlarmTestPV.h"
	"CBPool.h"
	"ControlBuilder.h"
	"Resource.h"
	"stateKeys.h"
)
source_group("Headers" FILES ${Headers})

set(Sources	
	"2OO3.cpp"
	"848_0601.cpp"
	"9413_DIGIT_0102.cpp"
	"9413-DIGIT_0102.AI.cpp"
	"9413-DIGIT_0102.DO1TB.cpp"
	"9413-DIGIT_0102.MDI.cpp"
	"9413-DIGIT_0102.MDO.cpp"
	"9413-DIGIT_0102.RESOURCE.cpp"
	"ABS.cpp"
	"ADD.cpp"
	"AICHANNEL.cpp"
	"AI-LLMUX.cpp"
	"AIREF.cpp"
	"AND.cpp"
	"AO16.cpp"
	"AOCHANNEL.cpp"
	"AOREF.cpp"
	"AUTOMAN.cpp"
	"AUXCALC.cpp"
	"AUXCALC_FP.cpp"
	"AUXSUMMER.cpp"
	"BlockCreate.cpp"
	"BmBase.cpp"
	"BOOL2NUM.cpp"
	"C300.cpp"
	"CBPool.cpp"
	"CEEC300.cpp"
	"CEEFB.cpp"
	"CHECKBAD.cpp"
	"ConnectionMB.cpp"
	"ControlBuilder.cpp"
	"ControlBuilder_ACS.cpp"
	"ControlBuilder_Calc.cpp"
	"ControlBuilder_dll.cpp"
	"ControlBuilder_Init.cpp"
	"ControlBuilder_Link.cpp"
	"ControlBuilder_Params.cpp"
	"ControlBuilder_State.cpp"
	"CONTROLMODULE.cpp"
	"CPM200.cpp"
	"CTUD.cpp"
	"DATAACQ.cpp"
	"DEADTIME.cpp"
	"DELAY.cpp"
	"DEVCTL.cpp"
	"DI.cpp"
	"DI24V.cpp"
	"DICHANNEL.cpp"
	"DIGACQ.cpp"
	"DIREF.cpp"
	"DISOE.cpp"
	"DIV.cpp"
	"DO32.cpp"
	"DOCHANNEL.cpp"
	"DOREF.cpp"
	"Dx_24y.cpp"
	"Dx_SOE.cpp"
	"ENHAUXCALC.cpp"
	"ENHREGCALC.cpp"
	"EQ.cpp"
	"FANOUT.cpp"
	"FFLINK.cpp"
	"FIM4.cpp"
	"FIRSTOUT.cpp"
	"FLAG.cpp"
	"FLAGARRAY.cpp"
	"FLOWCOMP.cpp"
	"FTEB.cpp"
	"FTRIG.cpp"
	"GE.cpp"
	"GENLIN.cpp"
	"GT.cpp"
	"H_Block.cpp"
	"H_Data.cpp"
	"HAICHANNEL.cpp"
	"HANDLER.cpp"
	"HLAI.cpp"
	"HLAIHART.cpp"
	"INTERLOCK.cpp"
	"IOLINK.cpp"
	"LE.cpp"
	"LIMIT.cpp"
	"LLMUX.cpp"
	"LT.cpp"
	"MAI.cpp"
	"MAX.cpp"
	"MAXPULSE.cpp"
	"MESSAGE.cpp"
	"MIN.cpp"
	"MINPULSE.cpp"
	"ModuleCreate.cpp"
	"MUL.cpp"
	"MUXREAL.cpp"
	"NAND.cpp"
	"NE.cpp"
	"NEG.cpp"
	"NOR.cpp"
	"NOT.cpp"
	"NUM2BOOL.cpp"
	"NUMERIC.cpp"
	"NUMERICARRAY.cpp"
	"OFFDELAY.cpp"
	"ONDELAY.cpp"
	"OR.cpp"
	"OVRDSEL.cpp"
	"ParmVarInfo.cpp"
	"PCDI_MASTER.cpp"
	"PCDIFLAGARRCH.cpp"
	"PCDINUMARRCH.cpp"
	"PICHANNEL.cpp"
	"PID.cpp"
	"PIDFF.cpp"
	"PITOTALIZER.cpp"
	"PULSE.cpp"
	"PUSH.cpp"
	"QOR.cpp"
	"RATIOBIAS.cpp"
	"RATIOCTL.cpp"
	"RBPERMISSION.cpp"
	"REGCALC.cpp"
	"REGSUMMER.cpp"
	"RMFBCLASS.cpp"
	"ROLLAVG.cpp"
	"Root.cpp"
	"ROR.cpp"
	"RS.cpp"
	"RTRIG.cpp"
	"SaveRestoreProject.cpp"
	"SCM.cpp"
	"SEL.cpp"
	"SELREAL.cpp"
	"SIGNALSEL.cpp"
	"SP.cpp"
	"SP_AI.cpp"
	"SP_AO.cpp"
	"SP_DI.cpp"
	"SP_DO.cpp"
	"SP_SPDVOTE.cpp"
	"SP_SPEED.cpp"
	"SPARE.cpp"
	"SR.cpp"
	"STARTSIGNAL.cpp"
	"STEP.cpp"
	"SUB.cpp"
	"SWITCH.cpp"
	"TC-IAH161.cpp"
	"TC-IDD321.cpp"
	"TC-IXL061.cpp"
	"TC-IXL062.cpp"
	"TC-IXR061.cpp"
	"TC-MDP081.cpp"
	"TC-OAV081.cpp"
	"TC-ODD321.cpp"
	"TEXTARRAY.cpp"
	"TEXTCOMMENT.cpp"
	"TIMER.cpp"
	"TOTALIZER.cpp"
	"TRANSITION.cpp"
	"TRIG.cpp"
	"TYPECONVERT.cpp"
	"UIO.cpp"
	"UIO-2.cpp"
	"WATCHDOG.cpp"
	"xHART_HL.cpp"
	"XOR.cpp"
	"ScriptEng/CalcRes.cpp"
	"ScriptEng/CalcVar.cpp"
)
source_group("Sources" FILES ${Sources})	

set(ALL_FILES
    ${Headers}
    ${Sources}
	"../../../../utf8.manifest"
	"ControlBuilder.rc"
)
add_library(${PROJECT_NAME} SHARED ${ALL_FILES})

add_compile_definitions(CONTROLBUILDERH5XX_EXPORTS)

target_link_directories(${PROJECT_NAME} PUBLIC
    "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}"
)
add_dependencies (${PROJECT_NAME} MemoryServiceHCD)

target_link_libraries(${PROJECT_NAME} Utils zlibvc CommonRSUs crosslib RsuX UtilsH5xx ConnectH5xx TinyXML2 MemoryServiceH5xx ScriptoH CnfReader ControlBuilderH5xxDebug)

set(PROJECT_INCLUDES
        "${CMAKE_CURRENT_SOURCE_DIR}/"        
	"${CMAKE_CURRENT_SOURCE_DIR}/../../Include"
	"${CMAKE_CURRENT_SOURCE_DIR}/../../../../system/include/rsus"
    "${CMAKE_CURRENT_SOURCE_DIR}/../../../common/include"
)

target_include_directories(${PROJECT_NAME} PUBLIC
    ${PROJECT_INCLUDES}
    ${COMMON_INCLUDES}
)

