SharedAnalog32Savebale(PV)
SharedAnalog32Savebale(SP)
SharedAnalog32Savebale(OP)
SharedDigital32Savebale(MODE)//ручной/автоматический/CAS
SharedAnalog32( MAXIMUM )
SharedAnalog32( MINIMUM )
SharedAnalog32( HH_LIM_PV )
SharedAnalog32( H_LIM_PV )
SharedAnalog32( L_LIM_PV )
SharedAnalog32( LL_LIM_PV )
SharedAnalog32( HYST )
SharedChars( DESCR, 512)
SharedChars(VALUE_FORMAT,64)
SharedChars(EU,64)
SharedDigital32(HH)
SharedDigital32(H)
SharedDigital32(L)
SharedDigital32(LL)
SharedChars( DESCR1, 512)
SharedChars( DESCR2, 512)
SharedAnalog32( MAX_OUT )
SharedAnalog32( MIN_OUT )
SharedDigital32( SetAck )
SharedDigital32( Acked )
SharedDigital32( IL_STATE )
SharedAnalog32( P )
SharedAnalog32( I )
