String_K(NAME,"",32*4)
//String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
String_K(BLKTYPE,"Block Type",33*4)
/*STRUCT(BLOCK_ALM)
  ENUM_S(BLOCK_ALM,ALARM_STATE,"Alarm State",Undefined,Clear-reported,Clear-not reported,Active-reported,Active-not reported,Def=)
  ENUM_S(BLOCK_ALM,SUB_CODE,"Subcode",Other,BlockConfiguration,LinkConfiguration,SimulationActive,LocalOverride,DeviceFaultState,DeviceMaintenance,InputFailure,OutputFailure,MemoryFailure,LostStaticData,LostNVData,ReadbackCheck,MaintenanceNeeded,PowerUp,OutOfService,Def=)
  ENUM_S(BLOCK_ALM,UNACKNOWLEDGED,"Unacknowledged",Undefined,Acknowledged,Unacknowledged,Def=)
STRUCT_END(BLOCK_ALM)*/
String_K(BLOCKTAG,"Block tag",32*4)
//Integer(CBBLOCKPROP,"Block Property")
Integer(DDITEM,"Block DD Item",0)
String_K(DESC,"Description",132*4)
Integer(DEVICE,"Associated Device",0)
Boolean(IS_IBLOCK,"Is this an Instantiable Block",false)
Boolean(METHODPRESENT,"Method Present",false)
Integer(ORDERINCM,"Execution Order in CM",10)
Boolean(PARTIALLOAD,"Partial Load",false)
//String_K(QUALSTATE,"Qualification State",100*4)
String_K(TAG_DESC,"Block Tag Description",32*4)
/*STRUCT(UPDATE_EVT)
  ENUM_S(UPDATE_EVT,UNACKNOWLEDGED,"Unacknowledged",Undefined,Acknowledged,Unacknowledged,Def=)
  ENUM_S(UPDATE_EVT,UPDATE_STATE,"Update State",Undefined,Update reported,Update not reported,Def=)
STRUCT_END(UPDATE_EVT)
*/