String_K(NAME,"Имя",31*4)
//INTEGER_A(ASSOCBLOCK,1000,"Associated Block")
//STRING(BLCKCOMMENT1,40,"Block Comment 1")
//STRING(BLOCKTYPNAME,101,"Block Type Name")
//INTEGER(CBBLOCKPROP,"Block Property")
//INTEGER(NUMBLOBS,"Number of Dynamic State Blobs")
//STRING(QUALSTATE,100,"Qualification State")
//FLAG(X_ALLOWEXECBB,"Allow executing Basic Block")
//INTEGER(X_BLOCKMEM,"Currently used memory (bytes)")
