String_K(NAME,"Имя",32*4)
//Integer_A(ASSOCBLOCK,"Associated Block",1000)
//String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
//String_K(BLOCKTYPNAME,"Block Type Name",101*4)
//Integer(CBBLOCKPROP,"Block Property")
String_K(DESC,"Description",132*4)
String_K(EUDESC,"Engineering Units",24*4)
Struct_BEI(FIRSTOUTALM,FL,ALPRIOR,PR,SV)
Struct_EIE(HIALM,ALPRIOR,PR,SV,HIALMFLAG,TYPE)
Boolean(INALM,"Function Block In Alarm Flag",false)
String_K(INDESC1,"Description of IN[1]",32*4)
String_K(INDESC2,"Description of IN[2]",32*4)
String_K(INDESC3,"Description of IN[3]",32*4)
String_K(INDESC4,"Description of IN[4]",32*4)
String_K(INDESC5,"Description of IN[5]",32*4)
String_K(INDESC6,"Description of IN[6]",32*4)
String_K(INDESC7,"Description of IN[7]",32*4)
String_K(INDESC8,"Description of IN[8]",32*4)
String_K(INDESC9,"Description of IN[9]",32*4)
String_K(INDESC10,"Description of IN[10]",32*4)
String_K(INDESC11,"Description of IN[11]",32*4)
String_K(INDESC12,"Description of IN[12]",32*4)
String_K(INDESC13,"Description of IN[13]",32*4)
String_K(INDESC14,"Description of IN[14]",32*4)
String_K(INDESC15,"Description of IN[15]",32*4)
String_K(INDESC16,"Description of IN[16]",32*4)
String_K(INDESC17,"Description of IN[17]",32*4)
String_K(INDESC18,"Description of IN[18]",32*4)
String_K(INDESC19,"Description of IN[19]",32*4)
String_K(INDESC20,"Description of IN[20]",32*4)
String_K(INDESC21,"Description of IN[21]",32*4)
String_K(INDESC22,"Description of IN[22]",32*4)
String_K(INDESC23,"Description of IN[23]",32*4)
String_K(INDESC24,"Description of IN[24]",32*4)
String_K(MULTIINPTDESC,"Multiple Input Description",32*4)
Boolean_A(NORMAL,"Normal state of an INPUT[*]",24,false)
Integer(NUMDINPUTS,"",1)
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
//Integer(ORDERINCM,"Execution Order in CM")
//String_K(QUALSTATE,"Qualification State",100*4)
//Boolean(TRANMONITR,"Transition Monitoring Status",false)
//Boolean(X_ALLOWEXECBB,"Allow executing Basic Block",false)
//Integer(X_BLOCKMEM,"Currently used memory (bytes)")
//Enumeration(X_NOTIF_ID,"Alarm condition strings",DO_NOT_USE,BAD_PV,PVHIGH,PVHIHI,PVLOW,PVLOLO,ROCNEG,ROCPOS,BAD_COMPTERM,FIRST_OUT,Def=)
