Enumeration_A(ARWNET,"Network Windup Status",8,NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWNETIN,"Auxiliary Network Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWOP,"Output Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWOPIN,"Auxiliary Output Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Integer(ASTEPID,"Active STEP of Request",0)
Struct_BEI(BADCTLALM,FL,ALPRIOR,PR,SV)
/*STRUCT(BADCTLALM)
  ENUM_S(BADCTLALM,ALL,"",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  FLAG_S(BADCTLALM,FL,"Bad Ctl Alarm Flag")
  ENUM_S(BADCTLALM,PR,"Bad Ctl Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(BADCTLALM,SV,"Bad Ctl Alarm Severity")
STRUCT_END(BADCTLALM)*/
Boolean(BADCTLFL,"Bad Control Flag",false)
Boolean(CASREQFL,"Cascade Request Flag",false)
Boolean(COMPUTEARW,"Recompute windup",false)
Boolean(CTLINIT,"Control Init Flag",false)
Enumeration(CTLSTATE,"Control state",FWD,HOLD,INIT,MAN,Def=FWD)
Real(CV,"Calculated Variable",NaN)
Struct4B(ESWFL,"",AUTO,BCAS,CAS,MAN)
/*STRUCT(ESWFL)
  FLAG_S(ESWFL,ALL,"")
  FLAG_S(ESWFL,AUTO,"Auto Ext Mode Switch")
  FLAG_S(ESWFL,BCAS,"Bcas Ext Mode Switch")
  FLAG_S(ESWFL,CAS,"Cas  Ext Mode Switch")
  FLAG_S(ESWFL,MAN,"Man  Ext Mode Switch")
STRUCT_END(ESWFL)*/
Enumeration(FBORSTS,"FB Override Status",NOTCON,SEL,NOTSEL,Def=NOTCON)
Boolean(INITMAN,"FB In-Init Flag",false)
Boolean_A(INITREQ,"Init Request for Primary",8,false)
Boolean(INSFAILFL,"Insertion fail flag",false)
Enumeration(LASTMODEREQ,"Last MODEREQ in RUN",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Real(LASTOPREQ,"Last OPREQ in RUN",NaN)
Enumeration(LASTOPTYPE,"Last OPTYPE in RUN",Null,SET,NOTSTORED,DEFAULT,Def=Null)
Boolean(LASTREQFL,"Last Requested Par Flag",false)
Integer(LASTSTEP,"Last SCO STEP in RUN",0)
Enumeration(MODE,"Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=MAN)
Boolean_A(MODEAPPL,"Mode Applicability Flags",4,false)
Struct3B(MODEATTRFL,"",NORM,OPER,PROG)
/*STRUCT(MODEATTRFL)
  FLAG_S(MODEATTRFL,ALL,"")
  FLAG_S(MODEATTRFL,NORM,"Norm Mode Attribute Flag")
  FLAG_S(MODEATTRFL,OPER,"Oper Mode Attribute Flag")
  FLAG_S(MODEATTRFL,PROG,"Prog Mode Attribute Flag")
STRUCT_END(MODEATTRFL)*/
Boolean(MODECHANGE,"First time mode Change",false)
Struct5B(MODEFL,"",AUTO,BCAS,CAS,MAN,NORM)
/*STRUCT(MODEFL)
  FLAG_S(MODEFL,ALL,"")
  FLAG_S(MODEFL,AUTO,"Auto Mode Flag")
  FLAG_S(MODEFL,BCAS,"Bcas Mode Flag")
  FLAG_S(MODEFL,CAS,"Cas  Mode Flag")
  FLAG_S(MODEFL,MAN,"Man  Mode Flag")
  FLAG_S(MODEFL,NORM,"Norm Mode Flag")
STRUCT_END(MODEFL)*/
Enumeration(MODEREQ,"Requested Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Integer(NUMONESHOT,"# of Oneshot Requests",0)
Integer(NUMPROPREQ,"# of Propaga Requests",0)
Real(OP,"OP Value in %",0)
Real(OPBIAS_TOTAL,"Total Output Bias",0)
Real(OPEU,"OP Value in EUs",0)
Boolean(OPEXHIFL,"OP Extended High Flag",false)
Boolean(OPEXLOFL,"OP Extended Low Flag",false)
Boolean(OPHIFL,"OP High Limit Flag",false)
Boolean(OPLOFL,"OP Low Limit Flag",false)
Real(OPREQ,"Requested OP Value",0)
Boolean(OPROCNEGFL,"OP Neg Rate-of-Chng Flag",false)
Boolean(OPROCPOSFL,"OP Pos Rate-of-Chng Flag",false)
Boolean(SIFL,"Safety Interlock Flag",false)
String_K(SELXDESC,"Selected Input Descriptor",15*4)
Boolean_A(SELXFL,"Selection Flag",4,false)
Integer(SELXINP,"Selection Id",0)
Boolean(TMOUTFL,"Timeout Flag",false)
Real_A(X,"X Input in EUs",4,NaN)

Real(BACKCALCIN,"",NaN)
Real_A(BACKCALCOUT,"",4,NaN)