String_K(NAME,"",32*4)
Boolean(BOOLMUX,"Flag for Mux Selection (On - Boolean , Off - Integer)",false)
Integer(CURPINPT,"Current Number of Inputs",0)
String_K(DESC,"Description",132*4)
String_K(EUDESC,"Engineering Units",24*4)
Boolean(FRCPERM,"Forced Select Permisive",false)
Boolean(FRCREQ,"Forced Select Request Flag",false)
Enumeration(FRCSEL,"Forced Select Input",None,SelectP1,SelectP2,SelectP3,SelectP4,SelectP5,SelectP6,Def=None)
Integer(IGNORHI,"Ignore Highest Inputs",0)
Real(IGNORLM,"Ignore Limit",0)
Integer(IGNORLO,"Ignore Lowest Inputs",0)
Real(IGNORTM,"Ignore Time",0)
Enumeration(MEDOPT,"Middle Two Inputs",MIN,MAX,AVG,MED,MUX,Def=MIN)
Integer(NMIN,"Minimum Valid Inputs",0)
Integer(NUMPINPT,"Number of Process Inputs",0)
Integer(ORDERINCM,"Execution Order in CM",10)
String_A(PDESC,"Input Descriptors ",24 * 4,6)
Enumeration(PVFORMAT,"Process Variable (PV) Display Format",D0,D1,D2,D3,Def=D1)//D0 (-XXXXXX.) D1 (-XXXXX.X) D2 (-XXXX.XX) D3 (XXX.XXX)
Enumeration(SELMETHOD,"Selection Method",MIN,MAX,AVG,MED,MUX,Def=MIN)
