Boolean(BADPVFL,"Bad PV Flag",false)
Real(LASTPV,"Last PV",NaN)
Real(LASTROCNEGLLDRCRSPD,"Lo Acc. Dur. Last Critical Spd",NaN)
Real(LASTROCPOSHHDRNMSPD,"Hi Acc. Dur. Last Nominal Spd",NaN)
Real(MAXFLOWRATE,"Maximum Flow Rate",NaN)
Real(MINFLOWRATE,"Minimum Flow Rate",NaN)
Real(PV,"Process Value",NaN)
Real(PVAUTO,"PV Auto Value",NaN)
Enumeration(PVAUTOST,"PV Auto Value Status",BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Real(PVCALC,"Calculated PV",NaN)
Real(PVRAW,"PV Raw Value",NaN)
Enumeration(PVSOURCE,"PV Source",SUB,MAN,AUTO,Def=AUTO)
Enumeration(PVSTS,"Process Value Status",BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Real(ROCPV,"Rate Of Change PV (RPM/min)",NaN)
