String_K(NAME,"Имя",32*4)
/*
Real(ALERTTIMEOUT,"Alert Timeout (min)")
Integer_A(ASSOCBLOCK,"Associated Block",1000)
String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
String_K(BLOCKTYPNAME,"Block Type Name",101*4)
Integer(CBBLOCKPROP,"Block Property")
Enumeration(CONFIGCODE,"SCM Part Config Code",None,UnknownError,InternalErr,ILLOwnHandle,ILLHndlrHndl,NextHNotNull,ILLNNextTrns,ConnInvObjs,InvNextType,NotImplNxTyp,ILLExcConds,ILLConds,ILLOutputs,IncObjects,ILLNOutputs,ILLNConds,ILLGateLogic,IncGateLogic,NullGateUsed,OvlpGateInps,SkipGateInps,ILLInvkTObj,ILLInvkTCnfg,ILLHndlrType,ILLHndlrSel,HndlrInstMis,ILLExcCProp,IncOpProp,IncCondProp,IncInvkTProp,IncPropagtn,LostObjects,ActIgnored,EditIgnored,TooFewCond,MaxTmLtMinTm,NegativeTime,EnbHdUnavail,DisHdUnavail,EditNotPermt,IntGateError,UserNullHnd,UserEditHnd,ILLObjAsHnd,NonEditLostO,NonOptGatLog,RefusedConn,ILLMultRef,ConfHndErr,CnfHndSvrWrn,ConfHndWarn,ConfHndInfo,CnfUnknCnfSt,ResrcMissing,IllegalConvErr,ImpConvInfo,ATLoadInProg,ATLoadFailed,IntegrityErr,Spare59,Spare60,Spare61,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,ForceReadReqIgnored,EquipmentNotSupported,ResourceNotSupported,Def=)
*/
String_K(CONFIGDESC,"Part ConfigCode Desc",39*4)
//Enumeration(CONFIGSTS,"SCM Part Config Status",Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=)
String_K(DESC,"Description",132*4)
Integer(ENDOFFSET,"End Offset [Sec]",0)
Enumeration(ENFORCESEQ,"Enforce Seq Order Option",None,CnfmInstrs,AllOutputs,Def=None)
Integer(ESTDURATION,"Estimated Trend Duration [Sec]",0)
String_K(EUDESC,"Engineering Units",24*4)
Boolean(EVTOPTSTEPC,"Step Complete Event Option",false)
Boolean(EVTOPTSTEPS,"Step Start Event Option",false)
//Enumeration(EXECCODE,"SCM Part Execution Code",None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
String_K(EXECDESC,"Part ExecCode DesC",39*4)
//Enumeration(EXECSTS,"SCM Part Exec Status",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=)
Boolean(FORCEREADREQ,"Force Enabling Read Requests",false)
Integer(HANDLER,"Part Belongs to Handler",0)
//Boolean(HIDETBLVIEW,"Hide on Table View",false)
Struct_SCM_STEP_SC(IC)
/*STRUCT(IC)
FLAG_S(IC,BYPPERM,"Step IC Bypass Permit")
ENUM_S(IC,BYPREQ,"Step IC Bypass Request",ToOff,ToOn,None,Def=)
ENUM_S(IC,CONFIGCODE,"Step IC Config Code",None,Ok,UnknownError,ImplicitConv,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ConstExprRem,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,Def=)
STRING_S(IC,CONFIGDESC,39,"Step IC Config Desc")
ENUM_S(IC,CONFIGSTS,"Step IC Config Status",Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=)
STRING_S(IC,DESC,64,"Step IC Description")
ENUM_S(IC,EXECCODE,"Step IC Execution Code",None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
STRING_S(IC,EXECDESC,39,"Step IC ExecCode Desc")
ENUM_S(IC,EXECSTS,"Step IC Exec Status",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=)
STRING_S(IC,EXPR,512,"Step IC Expression")
STRING_S(IC,EXPRPCODE,218,"Step IC Expression PCode")
FLAG_S(IC,FL,"Step IC Status Flag")
INTEGER_S(IC,INCONNSTS1,"Status of InConnector 1")
INTEGER_S(IC,INCONNSTS2,"Status of InConnector 2")
INTEGER_S(IC,INCONNSTS3,"Status of InConnector 3")
INTEGER_S(IC,INCONNSTS4,"Status of InConnector 4")
INTEGER_S(IC,INCONNSTS5,"Status of InConnector 5")
INTEGER_S(IC,INCONNSTS6,"Status of InConnector 6")
FLAG_S(IC,INVOKFL,"Step IC Invoke Flag")
FLAG_S(IC,OPT,"Step IC Option")
STRUCT_END(IC)*/
Integer(ICNUMSRCCONN,"ICond Num of Src Conns",0)
//Integer(ICPCODESIZE,"ICond PCode Size (bytes)")
Integer(ID,"Step Id (user-defined)",0)
Integer(MAXTIME,"Maximum Active Time",0)
Boolean(MAXTIMEFL,"Max Time Expired Flag",false)
Integer(MINTIME,"Minimum Active Time",0)
Integer_A(NEXTHANDLE,"Step Next Handle",10,0)
Integer(NEXTNUMBER,"Step Next Handle Count",0)
Integer(NUM,"Part Number in SCM",0)
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Integer(NUMOUTPUTS,"Number of Outputs",0)

StructA_SCM_STEP_OP(OP,16)
/*STRUCT(OP)
ENUM_SA(OP,ACQSTATE,16,"Acqisition state",16,NONE,ACQUIRING,ACQUIRED,RELEASING,ERROR,WARNING,Def=)
ENUM_SA(OP,BYPREQ,16,"Output Bypass",16,None,Skip,Def=)
INTEGER_SA(OP,CMDREQSTS,16,"Resource command store Status")
FLAG_SA(OP,CONFIGASSOCPARAM,16,"Configure the associate key parameter option")
ENUM_SA(OP,CONFIGCODE,16,"Output Config Code",16,None,Ok,UnknownError,ImplicitConv,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ConstExprRem,DuplExprRem,DstnInvalid,DstnCRqInval,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,Def=)
STRING_SA(OP,CONFIGDESC,16,39,"Output Config Desc")
ENUM_SA(OP,CONFIGSTS,16,"Output Config Status",16,Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=)
FLAG_SA(OP,CURRVALTREND,16,"Current Value Trend")
DOUBLE_SA(OP,DELAYTIME,16,"Output Delay Time (secs)")
DOUBLE_SA(OP,DELAYTIMEREM,16,"Output Delay Time Rem (secs)")
STRING_SA(OP,DESC,16,64,"Output Description")
INTEGER_SA(OP,EQUIPNAME,16,"Name of the resource to be acquired")
ENUM_SA(OP,EXECCODE,16,"Output Execution Code",16,None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
STRING_SA(OP,EXECDESC,16,39,"Output ExecCode Desc")
ENUM_SA(OP,EXECSTS,16,"Output Execution Status",16,Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=)
STRING_SA(OP,EXPRPCODE,16,218,"Output Expression PCode")
FLAG_SA(OP,FILTERABLE,16,"Step Output is Filterable")
FLAG_SA(OP,HIDETBLVIEW,16,"Hide on Table View")
INTEGER_SA(OP,INCONNSTS1,16,"Status of InConnector 1")
INTEGER_SA(OP,INCONNSTS2,16,"Status of InConnector 2")
INTEGER_SA(OP,INCONNSTS3,16,"Status of InConnector 3")
INTEGER_SA(OP,INCONNSTS4,16,"Status of InConnector 4")
INTEGER_SA(OP,INCONNSTS5,16,"Status of InConnector 5")
INTEGER_SA(OP,INCONNSTS6,16,"Status of InConnector 6")
FLAG_SA(OP,INSTRUCTCNFM,16,"Instruction Confirm")
FLAG_SA(OP,INSTRUCTCOMP,16,"Instruction Complete")
FLAG_SA(OP,INSTRUCTPEND,16,"Instruction Pending")
ENUM_SA(OP,INSTRUCTTYPE,16,"Output Instruction Type",16,None,Info,Confirm,Def=)
INTEGER_SA(OP,OWNERSSTS,16,"Resource Owners Get Status")
FLAG_SA(OP,OWNFL,16,"Ownership flag")
FLAG_SA(OP,RELFL,16,"Release resource input")
FLAG_SA(OP,REQFL,16,"Request resource input")
STRING_SA(OP,ROLE,16,16,"Role")
STRING_SA(OP,SRCEXPR,16,512,"Output Src Expression")
ENUM_SA(OP,STATE,16,"Output State",16,Edit,Inactive,ProcDelay,Processing,CompleteBypassed,Complete,IEC_Init,IEC_Wait,Cancelled,IEC_Exit,Def=)
INTEGER_SA(OP,STORESTS,16,"Store Status of Ouput")
FLAG_SA(OP,TARGETCHANGE,16,"Target Value Change")
ENUM_SA(OP,TYPE,16,"Output Expression Type",16,Null,Set,NotStored,DEFAULT,N_IEC,R_IEC,S_IEC,Def=)
INTEGER_SA(OP,USECNT,16,"Requester usage count (diagnostic)")
STRUCT_END(OP)
*/
Integer_A(OPNUMSRCCONN,"Output Num of Src Conns",16,0)
Integer_A(OPPCODESIZE,"Output PCode Size (bytes)",16,0)
String_K(OPTYPEENUMMASK,"STEP Output Type Enumeration Mask",64*4)
//Integer(ORDERINCM,"Execution Order in CM")
Boolean(OVRSCMTMPRSR,"Override SCM Step Timeout Alarm Config",false)
Integer(PEERINPUTENB,"No. Of Enabled Peer Conns",0)
Integer(PEERINPUTNUM,"No. Of Peer Connections",0)
Boolean(PROCESSED,"Part Has Been Proc Flag",false)
//String_K(QUALSTATE,"Qualification State",100*4)
//Enumeration(REEXECOPT,"Re-execution Option",ReExecute,Continue,FollowContainer,FollowConfig,Def=)
//Enumeration(REEXECOPTOG,"Goto Re-execution Option Override",ReExecute,Continue,FollowContainer,FollowConfig,Def=)
//Enumeration(REEXECOPTOH,"Handler Return Re-execution Option Override",ReExecute,Continue,FollowContainer,FollowConfig,Def=)
//Enumeration(REEXECOPTOS,"Standard Sequence Re-execution Option Override",ReExecute,Continue,FollowContainer,FollowConfig,Def=)
String_K(ROLE,"Role",16*4)
Integer(RTABLEIDX,"Index of Step in RTable",0)

Struct_SCM_STEP_SC(SC)
/*STRUCT(SC)
FLAG_S(SC,BYPPERM,"Step SC Bypass Permit")
ENUM_S(SC,BYPREQ,"Step SC Bypass Request",ToOff,ToOn,None,Def=)
ENUM_S(SC,CONFIGCODE,"Step SC Config Code",None,Ok,UnknownError,ImplicitConv,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ConstExprRem,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,Def=)
STRING_S(SC,CONFIGDESC,39,"Step SC Config Desc")
ENUM_S(SC,CONFIGSTS,"Step SC Config Status",Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=)
STRING_S(SC,DESC,64,"Step SC Description")
ENUM_S(SC,EXECCODE,"Step SC Execution Code",None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
STRING_S(SC,EXECDESC,39,"Step SC ExecCode Desc")
ENUM_S(SC,EXECSTS,"Step SC Exec Status",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=)
STRING_S(SC,EXPR,512,"Step SC Expression")
STRING_S(SC,EXPRPCODE,218,"Step SC Expression PCode")
FLAG_S(SC,FL,"Step SC Status Flag")
INTEGER_S(SC,INCONNSTS1,"Status of InConnector 1")
INTEGER_S(SC,INCONNSTS2,"Status of InConnector 2")
INTEGER_S(SC,INCONNSTS3,"Status of InConnector 3")
INTEGER_S(SC,INCONNSTS4,"Status of InConnector 4")
INTEGER_S(SC,INCONNSTS5,"Status of InConnector 5")
INTEGER_S(SC,INCONNSTS6,"Status of InConnector 6")
FLAG_S(SC,INVOKFL,"Step SC Invoke Flag")
FLAG_S(SC,OPT,"Step SC Option")
STRUCT_END(SC)
*/
Integer(SCNUMSRCCONN,"SCond Num of Src Conns",0)
//Integer(SCPCODESIZE,"SCond PCode Size (bytes)")
Integer(STARTOFFSET,"Start Offset [Sec]",0)
//Enumeration(STATE,"SCM Part State",Edit,Inactive,Disabled,Enabled,Active,ActiveComplt,ProcOutputs,ProcMessages,ProcMinWait,ProcAcquire,ProcFormula,ProcExec,ProcState,ProcReport,ProcReset,ProcRelease,ProcModeTrk,Latched,ProcActivity,Def=)
Boolean(STEPICNFMENB,"Step Instrs Confirm Enable",false)

Struct_BEI(TIMEOUTALM,FL,ALPRIOR,PR,SV)
/*STRUCT(TIMEOUTALM)
FLAG_S(TIMEOUTALM,FL,"Step Alarm Flag")
ENUM_S(TIMEOUTALM,PR,"Step Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
INTEGER_S(TIMEOUTALM,SV,"Step Alarm Severity")
STRUCT_END(TIMEOUTALM)*/

//Enumeration(TRENDINTRVAL,"Trend Update Interval",1Min,6MinAvg,1HourAvg,8HourAvg,24HourAvg,5Sec,1Hour,8Hour,24Hour,Def=1Min)
//Integer(TRENDSETNUMBER,"Trend Set Number",0)
Boolean(UPDCEERESOPT,"Update SCM Start Addr on CEE Restart",false)
Boolean(UPDRESOPT,"Update Resume Addr Opt",false)
/*Integer(X_BLOCKMEM,"Currently used memory (bytes)")
Integer(X_BLOCKMEMCR,"Bytes for CR (runtime) data")
Integer(X_BLOCKMEMMR,"Bytes for MR (config) data")
Integer(X_CRWEIGHT,"Do not use for process , Diagnostic only")
Enumeration(X_NOTIF_ID,"Alarm condition strings",DO NOT USE,FAIL,STEPTO,HOLD,STOP,ABORT,Def=)
*/