String_K(NAME,"Имя",32*4)
/*Integer_A(ASSOCBLOCK,"Associated Block",1000)
String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
String_K(BLOCKTYPNAME,"Block Type Name",101*4)*/

StructA_SCM_TRANS_G(G,4)
/*STRUCT(G)
ENUM_SA(G,ALGID,4,"Gate Algorithm Id",4,None,On,Off,Connect,Not,Or,Nor,And,Nand,Xor,Def=None)
INTEGER_SA(G,FIRSTCOND,4,"Gate First Cond Handle")
INTEGER_SA(G,NUMINPTS,4,"Gate Number of Inputs")
FLAG_SA(G,SO,4,"Gate Status Output")
STRUCT_END(G)*/

StructA_SCM_TRANS_C(C,10)
/*STRUCT(C)
FLAG_SA(C,BYPPERM,10,"Cond Bypass Permit")
ENUM_SA(C,BYPREQ,10,"Cond Bypass Request",10,ToOff,ToOn,None,Def=)
ENUM_SA(C,CONFIGCODE,10,"Cond Config Code",10,None,Ok,UnknownError,ImplicitConv,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ConstExprRem,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,Def=)
STRING_SA(C,CONFIGDESC,10,39,"Cond Config Desc")
ENUM_SA(C,CONFIGSTS,10,"Cond Config Status",10,Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=)
STRING_SA(C,DESC,10,64,"Cond Description")
ENUM_SA(C,EXECCODE,10,"Cond Execution Code",10,None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
STRING_SA(C,EXECDESC,10,39,"Cond ExecCode Desc")
ENUM_SA(C,EXECSTS,10,"Cond Execution Status",10,Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=)
STRING_SA(C,EXPR,10,512,"Cond Expression")
STRING_SA(C,EXPRPCODE,10,218,"Cond Expression PCode")
FLAG_SA(C,FL,10,"Cond Status Flag")
ENUM_SA(C,GATEASGN,10,"Cond Gate Assignment",10,GateS,GateP1,GateP2,GateP3,Def=)
INTEGER_SA(C,INCONNSTS1,10,"Status of InConnector 1")
INTEGER_SA(C,INCONNSTS2,10,"Status of InConnector 2")
INTEGER_SA(C,INCONNSTS3,10,"Status of InConnector 3")
INTEGER_SA(C,INCONNSTS4,10,"Status of InConnector 4")
INTEGER_SA(C,INCONNSTS5,10,"Status of InConnector 5")
INTEGER_SA(C,INCONNSTS6,10,"Status of InConnector 6")
FLAG_SA(C,INVOKFL,10,"InvokT Cond Invok Flag")
STRUCT_END(C)*/
//Integer(CBBLOCKPROP,"Block Property")
Integer_A(CNUMSRCCONN,"Cond Num of Src Conns",10,0)
Boolean(COMPLETED,"Part Fully Completed",false)
//Enumeration(CONFIGCODE,"SCM Part Config Code",None,UnknownError,InternalErr,ILLOwnHandle,ILLHndlrHndl,NextHNotNull,ILLNNextTrns,ConnInvObjs,InvNextType,NotImplNxTyp,ILLExcConds,ILLConds,ILLOutputs,IncObjects,ILLNOutputs,ILLNConds,ILLGateLogic,IncGateLogic,NullGateUsed,OvlpGateInps,SkipGateInps,ILLInvkTObj,ILLInvkTCnfg,ILLHndlrType,ILLHndlrSel,HndlrInstMis,ILLExcCProp,IncOpProp,IncCondProp,IncInvkTProp,IncPropagtn,LostObjects,ActIgnored,EditIgnored,TooFewCond,MaxTmLtMinTm,NegativeTime,EnbHdUnavail,DisHdUnavail,EditNotPermt,IntGateError,UserNullHnd,UserEditHnd,ILLObjAsHnd,NonEditLostO,NonOptGatLog,RefusedConn,ILLMultRef,ConfHndErr,CnfHndSvrWrn,ConfHndWarn,ConfHndInfo,CnfUnknCnfSt,ResrcMissing,IllegalConvErr,ImpConvInfo,ATLoadInProg,ATLoadFailed,IntegrityErr,Spare59,Spare60,Spare61,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,ForceReadReqIgnored,EquipmentNotSupported,ResourceNotSupported,Def=None)
String_K(CONFIGDESC,"Part ConfigCode Desc",39*4)
Enumeration(CONFIGSTS,"SCM Part Config Status",Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=Ok)
//Integer_A(CPCODESIZE,"Cond PCode Size (bytes)",10)
String_K(DESC,"Description",132*4)
String_K(EUDESC,"Engineering Units",24*4)
//Enumeration(EXECCODE,"SCM Part Execution Code",None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
String_K(EXECDESC,"Part ExecCode DesC",39*4)
Enumeration(EXECSTS,"SCM Part Exec Status",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=Ok)
Integer(HANDLER,"Part Belongs to Handler",0)
Integer_A(I,"Integer connection",10,0)
Integer(NEXTHANDLE,"Trans Next Handle",0)
//Integer(NUM,"Part Number in SCM")
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Integer(NUMCONDS,"Trans Number of Conds",0)
//Integer(ORDERINCM,"Execution Order in CM")
Integer(PEERINPUTENB,"No. Of Enabled Peer Conns",0)
Integer(PEERINPUTNUM,"No. Of Peer Connections",0)
Boolean(PROCESSED,"Part Has Been Proc Flag",false)
//String_K(QUALSTATE,"Qualification State",100*4)
Integer(RTABLEIDX,"Index of Trans in RTable",0)
/*Enumeration(STATE,"SCM Part State",Edit,Inactive,Disabled,Enabled,Active,ActiveComplt,ProcOutputs,ProcMessages,ProcMinWait,ProcAcquire,ProcFormula,ProcExec,ProcState,ProcReport,ProcReset,ProcRelease,ProcModeTrk,Latched,ProcActivity,Def=)
Integer(X_BLOCKMEM,"Currently used memory (bytes)")
Integer(X_BLOCKMEMCR,"Bytes for CR (runtime) data")
Integer(X_BLOCKMEMMR,"Bytes for MR (config) data")
Integer(X_CRWEIGHT,"Do not use for process , Diagnostic only")
Enumeration(X_NOTIF_ID,"Alarm condition strings",DO NOT USE,BADCTL,OPHIGH,OPLOW,REGSI,DEVHI,DEVLOW,ADVDEV,UNCMDCHG,PREDPVHI,PREDPVLO,PIDPLBADPV,Def=)
*/