// Generated by CoffeeScript 1.10.0
(function() {
  var hmiwebJsBasePath;

  hmiwebJsBasePath = window.external.FrameworkServices.HMIWebJSBasePath;

  if (!hmiwebJsBasePath) {
    throw new Error('Cannot find HMIWebJS base path');
  }

  require.config({
    baseUrl: hmiwebJsBasePath
  });

  require(['asari/requireConfig'], function() {
    return require(['asari/displays/displaylinks/DisplayLinksApp'], function(DisplayLinksApp) {
      var app;
      app = new DisplayLinksApp();
      window.DisplayLinks = app;
      return app.run();
    });
  });

}).call(this);
