String_K(NAME,"Имя",32*4)
String_K(DESC,"Description",132*4)
Enumeration(ACCLOCK,"Access Lock",OPERATOR,ENGINEER,OTHERFB,Def=OPERATOR)
//Integer_A(ASSOCBLOCK,"Associated Block",1000)
//String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
//String_K(BLOCKTYPNAME,"Block Type Name",101*4)
//Integer(CBBLOCKPROP,"Block Property")
Integer(NNUMERIC,"Number of Numeric Values",0)
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
//Integer(ORDERINCM,"Execution Order in CM")
Enumeration(PVFORMAT,"PV Display Format",D0,D1,D2,D3,Def=D0)
//String_K(QUALSTATE,"Qualification State",100*4)
//Integer(X_BLOCKMEM,"Currently used memory (bytes)")
//Boolean(X_NOEXECBB,"Basic Block Doesn't Execute",false)
