Enumeration_A(ARWNET,"Network Windup Status",8,NORMAL,HI,LO,HILO,Def=NORMAL)
Integer(ASTEPID,"Active STEP of Request",0)
Boolean(BADCTLFL,"Bad Control Flag",false)
Boolean(CASREQFL,"Cascade Request Flag",false)
Boolean(COMPUTEARW,"Recompute windup",false)
Boolean(CTLINIT,"Control Init Flag",false)
Enumeration(CTLSTATE,"Control state",FWD,HOLD,INIT,MAN,Def=FWD)
Real(CV,"Calculated Variable",NaN)
Enumeration(FBORSTS,"FB Override Status",NOTCON,SEL,NOTSEL,Def=NOTCON)
Boolean(INALM,"FB In-Alarm Flag",false)
Boolean(INITMAN,"FB In-Init Flag",false)
Boolean_A(INITREQ,"Init Request for Primary",8,false)
Enumeration(LASTMODEREQ,"Last MODEREQ in RUN",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=MAN)
Real(LASTOPREQ,"Last OPREQ in RUN",0)
Enumeration(LASTOPTYPE,"Last OPTYPE in RUN",Null,SET,NOTSTORED,DEFAULT,Def=Null)
Boolean(LASTREQFL,"Last Requested Par Flag",false)
Integer(LASTSTEP,"Last SCO STEP in RUN",0)
Enumeration(MODE,"Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Enumeration(MODEATTR,"Mode Attribute",NONE,OPERATOR,PROGRAM,NORMAL,Def=NONE)
Struct3B(MODEATTRFL,"",NORM,OPER,PROG)
/*STRUCT(MODEATTRFL)
  FLAG_S(MODEATTRFL,ALL,"")
  FLAG_S(MODEATTRFL,NORM,"Norm Mode Attribute Flag")
  FLAG_S(MODEATTRFL,OPER,"Oper Mode Attribute Flag")
  FLAG_S(MODEATTRFL,PROG,"Prog Mode Attribute Flag")
STRUCT_END(MODEATTRFL)*/
Boolean(MODECHANGE,"First time mode Change",false)
Struct5B(MODEFL,"",AUTO,BCAS,CAS,MAN,NORM)
/*STRUCT(MODEFL)
  FLAG_S(MODEFL,ALL,"")
  FLAG_S(MODEFL,AUTO,"Auto Mode Flag")
  FLAG_S(MODEFL,BCAS,"Bcas Mode Flag")
  FLAG_S(MODEFL,CAS,"Cas  Mode Flag")
  FLAG_S(MODEFL,MAN,"Man  Mode Flag")
  FLAG_S(MODEFL,NORM,"Norm Mode Flag")
STRUCT_END(MODEFL)*/
Enumeration(MODEREQ,"Requested Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Integer(NUMONESHOT,"# of Oneshot Requests",0)
Integer(NUMPRI,"# of Primaries",0)
Integer(NUMPROPREQ,"# of Propaga Requests",0)
Integer(NUMSEC,"# of Secondaries",0)
Real(OP,"OP Value in %",0)
Real(OPBIAS_TOTAL,"Total Output Bias",0)
Real(OPEU,"OP Value in EUs",0)
Boolean(OPEXHIFL,"OP Extended High Flag",false)
Boolean(OPEXLOFL,"OP Extended Low Flag",false)
Boolean(OPHIFL,"OP High Limit Flag",false)
Boolean(OPLOFL,"OP Low Limit Flag",false)
Real(OPREQ,"Requested OP Value",0)
Boolean(OPROCNEGFL,"OP Neg Rate-of-Chng Flag",false)
Boolean(OPROCPOSFL,"OP Pos Rate-of-Chng Flag",false)
Real(RT,"RT Input in EUs",0)
Boolean(RTHIFL,"RT High Flag",false)
Boolean(RTLOFL,"RT Low Flag",false)
Boolean(SIFL,"Safety Interlock Flag",false)
Boolean(TMOUTFL,"Timeout Flag",false)
Real(X1,"X1 Input in EUs",0)