//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('scripts/ScadaControlViewModel', ['asari/viewmodels/RootViewModel', 'asari/viewmodels/TabularViewModel'], function(RootViewModel, TabularViewModel) {
    var ScadaControlViewModel;
    return ScadaControlViewModel = (function(_super) {

      __extends(ScadaControlViewModel, _super);

      function ScadaControlViewModel(tableDefinition, bannerDefinition) {
        ScadaControlViewModel.__super__.constructor.call(this);
        this.table = new TabularViewModel.TabularViewModel();
        this.banner = new TabularViewModel.TabularViewModel();
        this.tableDefinition = tableDefinition;
        this.bannerDefinition = bannerDefinition;
		
        //var update = JSON.parse('{"totalRows":1,"rows":[{"index":0,"completeData":false,"cells":[{"source":{"value":{"data":23,"type":"int4"}}},{},{},{},{},{},{},{},{},{}]}],"sequenceNo":0,"sort":{},"updateId":0}');
        //this.banner.requestServerDataComplete(update);
        this.consoleDegradedErrorMsg = 'SCADA Controller summary is not viewable on this Station when the Server is unavailable';
      }
      ScadaControlViewModel.prototype.initialise = function() {
        var config = { autoSubscribe: true };
        this.table.setConfig(config);
        this.banner.setConfig(config);
        this.table.initialise(this.tableDefinition);
        this.banner.initialise(this.bannerDefinition);
      };	  

      ScadaControlViewModel.prototype.clear = function() {
        this.table.clearTable();
        this.banner.clearTable();
      };

      ScadaControlViewModel.prototype.requestData = function() {
        this.table.reopenTable();
        this.banner.reopenTable();
      };

      ScadaControlViewModel.prototype.destroy = function() {
        this.table.destroy();
        this.banner.destroy();
      };

      return ScadaControlViewModel;

    })(RootViewModel);
  });

}).call(this);
