//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('scripts/ScadaControlApp', ['knockout', 'asari/util/AsariFunctionalLogger', 'asari/AppBase', 'scripts/ScadaControlViewModel', 'jquery'], function(ko, log, AppBase, ScadaControlViewModel, $) {
    var ScadaControlApp;
    return ScadaControlApp = (function(_super) {

      __extends(ScadaControlApp, _super);

      function ScadaControlApp(tableDefinition, bannerDefinition) {
      	log.initialise();
        ScadaControlApp.__super__.constructor.call(this, new ScadaControlViewModel(tableDefinition, bannerDefinition));
      }

      ScadaControlApp.prototype.initialise = function() {
        this.enableDetectConsoleDegraded();
      };

      ScadaControlApp.prototype.degradedModeChanged = function(isInDegradedMode) {
		ScadaControlApp.__super__.degradedModeChanged.call(this, isInDegradedMode);
        if (isInDegradedMode) {
          log.info('ScadaControlApp::degradedModeChanged | Entering Console Station degraded mode');
          this.rootViewModel.clear();
        } else {
          log.info('ScadaControlApp::degradedModeChanged | Exiting Console Station degraded mode');
          window.external.Refresh();
        }
      };

      ScadaControlApp.prototype.startup = function() {
        this.rootViewModel.initialise();
        if (this.rootViewModel.isInDegradedMode()) {
          this.rootViewModel.clear();
        }
        ko.applyBindings(this.rootViewModel);
        this.resizeTree();
        $(window).resize(this.resizeTree);
      };

      ScadaControlApp.prototype.shutdown = function() {
        this.rootViewModel.destroy();
      };
	  
      ScadaControlApp.prototype.resizeTree = function() {
        $docH = $(document).height();
        $headerH = $(".TopHeader").height();
        $marginB = 5;
        $filterH = $(".FilterOptions").height();
        $treeH = $("#Tree").height();
        $treeNewH = $docH - ($headerH + $filterH + $marginB);
        $("#Tree").height($treeNewH);
        $("#Tree").css("top", $filterH);
      };

      return ScadaControlApp;

    })(AppBase);
  });

}).call(this);
