Real_A(D,"Float connection",10,NaN)
Boolean(ACTIVEFL,"Step Active Flag",false)
Integer(ACTVTNTIME,"Activation Time",0)
Boolean(COMPLETED,"Part Fully Completed",false)
Boolean(CURRVALTREND,"Current Value Trend",false)
Integer_A(I,"Integer connection",10,0)
Boolean(INSTRUCTCNFM,"Step Instructions Confirm",false)
Boolean(INSTRUCTCOMP,"Step Instructions Complete",false)
Boolean(INSTRUCTPEND,"Step Instruction Pending",false)
Integer(LOOPCOUNT,"Step Loop Counter",0)
String_K(HANDLERREF,"Next Comp Reference",132*4)
String_A(NEXTCOMP,"Next Comp Reference",10 * 4,132)
Enumeration(POSTTRANSEXECSTS,"Execution status of succeding transitions",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=Ok)
Enumeration(PREVTRANSEXECSTS,"Execution status of preceding transitions",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=Ok)
Integer(TIME,"Current Active Time",0)