//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3

define(
[
  './PipelineGraphicBinding', 
  'text!./pipelineGraphicTemplate.htm',
	'asari/viewmodels/PointParamViewModel'
	
], 
	
	function(	PipelineGraphicBinding, pipelineGraphicTemplate, PointParamViewModel ) 	{
	
		var ShapeModule = {
			_config: {}
		};

	ShapeModule.init = function(config) 	{		
		ShapeModule._config = config;
		return true;
	}

	ShapeModule.getViewTemplates = function() 	{
		return {
			extPipelineGraphicTemplate: pipelineGraphicTemplate,
     			MAIN_VIEW_TEMPLATE: 'extPipelineGraphicTemplate'
		};
	}

	ShapeModule.getBindings = function() {	
		PipelineGraphicBinding.shapesPath = ShapeModule._config.shapesPath;
		return {
			extPipelineGraphic: PipelineGraphicBinding
		}
	}
	
	ShapeModule.getDependencies = function(){
		return null;
	}
  
	ShapeModule.getStyleSheets = function() {
		return [
			ShapeModule._config.shapesPath + '/pipelinegraphic/PipelineGraphicStyle.css'
		];
	}
	
	ShapeModule.createViewModel = function()	{ 	
		return new PointParamViewModel.MultiPointParamViewModel(['batchlist','nodelist','maximum']);
	}
  
	return ShapeModule;
});
