//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(
[
    'jquery',
    'asari/util/AsariFunctionalLogger',
    'knockout',
	'kendo',
	'knockout-kendo'
], 

  function($, log, ko, kendo, koKendo) {
    var PipelineGraphicBinding = {
      shapesPath: null
    }
    
    _updateBatchNotification = function(point) {    
		var template = kendo.template("#= batchname # \n arriving in #=arrivaltime#");
		var data = { batchname: point.dataItem.name, arrivaltime: point.dataItem.arrival };
		return template(data);
        
    };
    
    _defineBatchColor = function(batch) {
                
        switch(batch.style){
            case 0:
                batch.valueColor = "#5B6275";       
            break;
            case 1:
                batch.valueColor = "#6E869E";
            break;
            case 2:
                batch.valueColor = "#8A9CB3";
            break;
            case 3:
                batch.valueColor = "#C0C0C0";
            break;
            default:
                batch.valueColor = "#ffffff";
            break;
        }
    };

	
    // ----------------------------------------------
    // Interpret batch list
    // ----------------------------------------------   
    _renderBatches = function(datasource, serverjson) {
        
        var newDS = new kendo.data.DataSource();
        var jsonbatch = JSON.parse(serverjson);     
        var batcharray = new kendo.data.ObservableArray([]);
        
        var flagbatch = true;
        
        if( serverjson != null ){

	    var i = jsonbatch.length;
            while(i--){
               
                if(!jQuery.isEmptyObject(jsonbatch[i])){
                  
                  this._defineBatchColor(jsonbatch[i]);
                  
                  if( jsonbatch[i].arrival != "-" && flagbatch == true){
                    
                      if( jsonbatch[i].style != 3) {
                        jsonbatch[i].noteText = "location";
						
						flagbatch = false;
                      }
                      
                  }
                }
                batcharray.push(jsonbatch[i]);
            }
        }
    
        log.debug("PipelineGraphicBinding.js " + ko.toJSON(batcharray));
        newDS.data(batcharray.toJSON());
        newDS.group({field: "order"});
        datasource.setDataSource(newDS); 
        
    };
    
    // ----------------------------------------------
    // Interpret node locations
    // ----------------------------------------------
    _renderNodes = function(datasource, serverjson) {
        
        var jsonnode = JSON.parse(serverjson);
        var nodearray = new kendo.data.ObservableArray([]);
        
        var nodeAdditionalStyles = ko.toJS({"color":"#0096d7", "length":5});
        
        if( serverjson != null ){
            
            for(var i=0; i< jsonnode.length; i++){
                
                // style unavailable on element in defaultseries
                jsonnode[i].line = nodeAdditionalStyles;
                nodearray.push(jsonnode[i]);
            }
        }
        log.debug("PipelineGraphicBinding.js  " + ko.toJSON(nodearray));
        datasource.options.valueAxis.notes.data = nodearray.toJSON();
    };
    
	_showtooltip = function(point)	{
			
		var template="";
		if(point.dataItem.style != 3)
		{
			if(point.dataItem.arrival == "") {
				var templatecontent = kendo.template("<table id=\"tooltip\"><tr><th>#= b #</th></tr><tr><td>delivering</td></tr></table>");
				template = templatecontent({b:point.dataItem.name });
			}
			else
			{
				var templatecontent = kendo.template("<table id=\"tooltip\"><tr><th>#= b #</th></tr><tr><td>arriving in: #: a #</td></tr></table>");
				template = templatecontent({b:point.dataItem.name, a:point.dataItem.arrival });
			}
		}
		return template;
	}
	
    PipelineGraphicBinding.init = function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {  

        var chart = {
            series: [{field: "location", colorField: "valueColor"}],
            seriesDefaults: { column: {color: "red"}, type: "bar",  stack: true, noteTextField: "noteText",
                notes:{ 
                    label: { 
						position: "outside", 
						template: function(point) { return this._updateBatchNotification(point)},  
						background: "#dcdee0", border: { width:1, color: "#dcdee0"} , visible: true},
                    line: {width:1, length:10},
                    icon: {type:"circle", visible: true, size: 1, border: {width:1}}
				},
				
				visual: function(e) {
					
					//set up label
					var labelText = new kendo.drawing.Text(e.dataItem.name);
					var labelBBox = labelText.bbox();
					
					// position batch label
					var labelTargetPoint = {x: e.rect.topLeft().x, y:e.rect.center().y };										
					labelText.position([labelTargetPoint.x + 5, labelTargetPoint.y - (labelBBox.height() / 2)]);
					labelText.options.font = "12px sans-serif";
					labelText.options.fill.color = "#fff"
									
					// arrival box
					var arrivalPath = new kendo.drawing.Path();
					if(e.dataItem.arrival == "-" && e.dataItem.location == 0)
					{
						var arrivalBoxTargetPoint = {x: e.rect.topLeft().x +1, y: e.rect.topLeft().y+1};
						var arrivalBox = new kendo.geometry.Rect([arrivalBoxTargetPoint.x, arrivalBoxTargetPoint.y], [5,e.rect.size.height]);
						arrivalPath = new kendo.drawing.Path.fromRect(arrivalBox).fill("#dcdee0").stroke("none", 0);
					}
					
					var defaultVisual = e.createVisual();
					return new kendo.drawing.Group().append(defaultVisual, labelText, arrivalPath);
									

				}

			},
			tooltip: { 
					visible: true, 
					background: "#ffffff", 
					border: { width: 0 },
					template: function(point) {return _showtooltip(point); }},
					
            legend: { visible: false },
            valueAxis: { 
				name: "distanceAxis", 
				title: { text: "km" }, 
				line: { visible: false},
				min: 0,
                minorGridLines: { visible: true },              
                notes: { position: "up", visible: true, 
                    label: { position: "outside", visible: true, color: "#0096d7"}, 
                    icon: {background: "#ffffff", border: { color: "#0096d7" }}},
                    },
            categoryAxis: { majorGridLines: { visible: false }, visible: false},
            chartArea: {  height: 190 },
            plotArea: { margin: {top: 10, bottom: 0, left: 100, right: 100 } },
            transitions: false,
			panes: [{clip: false}] 
			};
        
		
		
        ko.bindingHandlers.kendoChart.options = chart;
        ko.bindingHandlers.kendoChart.init(element, valueAccessor, allBindingsAccessor, viewModel);     
        }
        
    PipelineGraphicBinding.update = function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {      
        
        var ds = $(element).data("kendoChart");             
        var valAccessor = valueAccessor();
        
        var batchlist = ko.utils.unwrapObservable(valAccessor.batches.source.value);
        var nodelist = ko.utils.unwrapObservable(valAccessor.nodes.source.value);
        var distancemax = ko.utils.unwrapObservable(valAccessor.distance.source.value);
        var distanceunit = ko.utils.unwrapObservable(valAccessor.distance.source.units);
        
        this._renderBatches(ds, batchlist);
        this._renderNodes(ds, nodelist);
                
        // ----------------------------------------------
        //  set graphic maximum and unit of measurement
        // ----------------------------------------------	
        log.debug("PipelineGraphicBinding.js " + ko.toJSON(distancemax) + " " + ko.toJSON(distanceunit));
        ds.options.valueAxis.max = distancemax;
        ds.options.valueAxis.title.text = distanceunit;
        
        
        ds.refresh();
        
    }  
    
    
    
    return PipelineGraphicBinding;    
  });
  