Boolean_A(BADPVFL,"Bad Process Value Flag",32,false)
Real_A(DOOP,"PWM Output Value (%)",32,NaN)
Real_A(INITVAL,"Echoback Value",32,NaN)
Real_A(OP,"Output Value (%)",32,0)
Real_A(OPFINAL,"Final Output Value",32,NaN)
Real_A(OPINITVAL,"PWM Echoback Value",32,NaN)
Real_A(PV,"Process Value",32,NaN)
Boolean_A(PVFL,"Process Value",32,false)
Enumeration_A(PVSTS,"Process Value Status",32,BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Boolean_A(SO,"Status Output Value",32,false)
Boolean_A(SOINITVAL,"Status Echoback Value",32,false)
