UMODE
ACK_ALARMS
INTEGER(OPMK,"")//
ENUM(BSTS,"",STRT,IBCH,STUP,STDY,ERLY,PBCH,END,NCNT,RSET,EMST,EEMS,RSTS)
INTEGER(AF,"")
FLAG(AOFS   ,"")
DOUBLE(PV,"")
DOUBLE(SUM,"")
DOUBLE(SUM1,"")
INTEGER(SW,"")//0-4
DOUBLE(MV,"")
