YPARM_I(AlarmLevel,12,"EALA")
YPARM_S(Comment,64,"ETCM")
YPARM_S(cMes,8,"EUNT")
YPARM_DD(SH,SL,100.,0.,"ESCL","%D:%D") 
YPARM_DDS(MVH,MVL,cMesMV,W->MSH,W->MSL,8,"AORA","%D:%D:%S") 
YPARM_L(InputSignalConversion,0,"EINP", "%{LINEAR;SQRT;BTHPUL;SUBSYS}")
YPARM_Dref(MH,W->MSH,"----")
YPARM_Dref(ML,W->MSL,"----")
YPARM_DD(SSH,SSL,DBL_MAX,DBL_MAX, "SVRG","%D:%D")
YPARM_D(MSH,DBL_MAX,"----")
YPARM_D(MSL,DBL_MAX,"----")
YPARM_L(Input_Open_alarm,0,"INOP","%{NO;H;L;HL}")
YPARM_B(PV_Overshoot,false,"OVPV")
YPARM_B(PV_Limit,false,"PVRL")
YPARM_Dref(SVH,W->SH,"----")
YPARM_Dref(SVL,W->SL,"----")
YPARM_DB(Out_VL,MAN_bypass,100.,false,"OVLM", "%D:%B")
YPARM_B(Limit_On_CLP,false,"CLPO")
YPARM_4D(Data_GAIN,Data_BIAS,H_Limit,L_Limit,1.,0.,100.,0.,"SSI!","%D:%D:%D:%D")
YPARM_L(OutputSignalConvertion,0,"OUTP","%{LINEAR;PW;SUBSYS;SUBWFT}")
YPARM_DDD(FullStrokeValue,BacklashCompensatedValue,MinOutputWidth,0.,0.,0.,"PWF!","%D:%D:%D")
YPARM_DD_savable(Conv_GAIN,Conv_BIAS,1.,0.,"SSO!","%D:%D")
YPARM_L(Aux,0,"SUOC","%{CPV;DCPV}")
YPARM_L(Aux_Out_Type,0,"SOAC", "%{POSITION;VELOCITY}")
YPARM_Dref(RP,W->MSH-W->MSL,"")//Ramp constant
YPARM_D(CK,1.0,"")//Compensation gain
YPARM_D(CB,0,"")//Compensation bias
YPARM_Dref(OPHI,W->MSH,"----")
YPARM_Dref(OPLO,W->MSL,"----")
