UMODE
ACK_ALARMS
INTEGER(OPMK,"")//

ENUM(BSTS   ,"",STOP,PAUS,RUN)
ENUM(PREBSTS,"",STOP,PAUS,RUN)
//
INTEGER(AF,"")
FLAG(AOFS   ,"")

INTEGER(STEPNO ,"")
INTEGER(SAID   ,"")
INTEGER(UAID   ,"")

INTEGER(DILG,"")
INTEGER(RECIPEGR,"")
INTEGER(OPID,"")
STRING(BATCHID,24,"")
STRING(UNITNAME,24,"")
