UMODE
ACK_ALARMS
INTEGER(OPMK,"")//
//
ENUM(BSTS,"",STOP,NR,PALM,CTUP,RUN,PAUS)//??? 
ENUM(OP,"",nothing,STOP,RSTR,START,WAIT)//TMSTOP=1, TMSTAT=2, TMCONT=3, TMPAUS=4
FLAG(AOFS,"")
FLAG(TKSW,"")// Проверено
FLAG(RES1,"")// Резерв
//
DOUBLE(dblPV,"")
DOUBLE(DV,"")
//
INTEGER(PV,"")
