YPARM_I(AlarmLevel,12,"EALA")
YPARM_S(Comment,64,"ETCM")
YPARM_S(cMes,8,"EUNT")
YPARM_DDS(MH,ML,cMesMV,W->MSH,W->MSL,8,"AORA","%D:%D:%S")
YPARM_Dref(RP,W->MSH-W->MSL,"")//Ramp constant
YPARM_D(CK,1.,"----")
YPARM_D(CB,0.,"----")
YPARM_Dref(PMV,W->MSL,"----")
YPARM_Dref(OPHI,W->MSH,"----")
YPARM_Dref(OPLO,W->MSL,"----")
YPARM_L(OutputSignalConvertion,0,"OUTP","%{LINEAR;PW;SUBSYS;SUBWFT}")
YPARM_DD(Out_MAX,Out_MIN,100.,0.,"AOF!","%D:%D")//100.00:0.00
YPARM_DDD(FullStrokeValue,BacklashCompensatedValue,MinOutputWidth,0.,0.,0.,"PWF!","%D:%D:%D")
YPARM_H(HYS_OUT,1.,"HLHT")
YPARM_DB(Out_VL,MAN_bypass,100.,false,"OVLM", "%D:%B")
YPARM_L( AuxDataType,0,"SUOP","%{PV;DPV}")
YPARM_D(MSH,DBL_MAX,"----")
YPARM_D(MSL,DBL_MAX,"----")
YPARM_L(Positional,1,"SOAC","%{VELOCITY;POSITION}")