//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3

define(
[
  './MORIndicatorBinding', 
  'text!./MORIndicatorTemplate.htm',
  'asari/viewmodels/PointParamViewModel'
], 
	
	function(MORIndicatorBinding, MORIndicatorTemplate, PointParamViewModel) 	{
		var ShapeModule = {
			_config: {}
	};

	ShapeModule.init = function(config) 	{		
		ShapeModule._config = config;
		return true;
	}

	ShapeModule.getViewTemplates = function() 	{
		return {
			hscMORIndicatorTemplate: MORIndicatorTemplate,
     			MAIN_VIEW_TEMPLATE: 'hscMORIndicatorTemplate'
		};
	}

	ShapeModule.getBindings = function() {	
		MORIndicatorBinding.shapesPath = ShapeModule._config.shapesPath;
		return {
			hscMORIndicator: MORIndicatorBinding
		}
	}

  	ShapeModule.getDependencies = function() {
    		return null;
  	}
  
	ShapeModule.createViewModel = function()	{ 
		return new PointParamViewModel.MultiPointParamViewModel(['mor1', 'mor2', 'mor3', 'mor4']);
	}
  
	return ShapeModule;
});
