//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(
[
  'knockout'
],

  	function (ko) {
  	    var MORIndicatorBinding = {
  	        shapesPath: null
  	    }

  	    MORIndicatorBinding.init = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
  	    }

  	    MORIndicatorBinding.update = function (element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
  	        var imageFile = null;
  	        var bindingConfig = valueAccessor();
  	        var mor1 = ko.utils.unwrapObservable(bindingConfig.value1.source.value);
  	        var mor2 = ko.utils.unwrapObservable(bindingConfig.value2.source.value);
  	        var mor3 = ko.utils.unwrapObservable(bindingConfig.value3.source.value);
  	        var mor4 = ko.utils.unwrapObservable(bindingConfig.value4.source.value);

  	        if (mor1 == 1 || mor2 == 1 || mor3 == 1 || mor4 == 1) {
  	            imageFile = 'mor_active.png';
  	        } else {
  	            imageFile = 'blank.png';
  	        }

  	        var path = MORIndicatorBinding.shapesPath + '/morindicator/' + imageFile;

  	        element.src = path;
  	    }

  	    return MORIndicatorBinding;
  	});

