// #pragma once
// #include "HTML.h"

// bool ends_with(char* haystack, char* needle);
// bool shape_contains_object(CHTML& html, CTag* object, char * name);
// bool shape_contains_property(CHTML& html, CTag* obj, char * name);
// CTag* shape_get_object(CHTML& html, CTag* object, char * name);
// SParamValueH shape_get_data_value(CHTML& html, CTag* tag, char * tagname, char * prop);
// char * shape_get_data_value_string(CHTML& html, CTag* tag, char * tagname, char * prop);
// long get_value_integer(CTag* obj, CHTML& html);
// bool shape_property_not_empty(CHTML& html, CTag* obj, char * name);

// void VBSCRIPT_CDA_ExecState_Alp_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_RegCtlValves_RedTag_BadCtlFl_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_Graph_AlpError_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_RegCntlValve_AlpVal_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_Devctl_Hialm_RedTag_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_Device3States_AlpGPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_Discrepancy_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Graph_AlpError_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_DigStateCColor_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_OnOffValves_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_Numeric_AlpPVFormat_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_RegCntl_Mode_Hialm_RedTag_EUDesc_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Numeric_AlpPVFormat_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_RegCntl_Mode_Hialm_EUDesc_OnUpdate_me_1_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_DigState_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_DigStateButton_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_DigStateCColor_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_DigStateColor_Khabarovsk_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_OnOffValves_AlpGPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_AbsorberStatus_Khabarovsk_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Device3States_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_DigState_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_DigStateButton_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_DigStateColor_Khabarovsk_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_BoxLocRem_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_Bypass_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_DigStateCColor_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_Enclav_onupdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_Interlock_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_KHABAROVSK_RotorkValvesLocalRemote_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_libKHABAROVSK_Bypass_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_libKHABAROVSK_Interlock_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_Description_onupdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Butt_Page_OnShapeLoad(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_RP1516CB_TextBox_UpdateScript(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_InitAnalog_AlpPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_Actuador_AlpPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_InitDigital_AlpPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__RecPV1_0140213(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__RecPV2_0140213(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__RecPV3_0140213(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__RecPV1_0140220(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__TxtMode001(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_OnOffValves_Khabarovsk_AlpPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_RegCntlValve_Khabarovsk_AlpVal_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__HWLineHeater14_2500109(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__HWLineHeater13_2500109(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__HWLineHeater23_2500115(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__HWLineHeater24_2500115(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT__HWLineHeater33_2500201(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_RegCntlValve_AlpVal_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_Scd_Khabarovsk_DamperValves_4State_AlpPV_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_Damper_AlpVal_OnUpdate_me_(CTag* _this, HDC hDC, CHTML& html);

// void VBSCRIPT_Cda_CEXXX_AlpPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_LK2B_Cda_CEXXX_AlpPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_LK2B_Cda_CEXXX_ConAlpTP_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_LK2B_Cda_CEXXX_RecPV_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_UZ_Cda_Graph_AlpError_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_All_ILBPGraph_AlpError_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
// void VBSCRIPT_CDA_Interlock_OnUpdate_me_(CTag* oSource, HDC hDC, CHTML& html);
