
#define S_CLASS(Name,Class) \
ASS(pSRFile->WStruct(Name, sizeof ( Class ), static_cast<Class*>(this)));

S_CLASS( AlphaNum , "DataEntry_Alphanumeric_Style"        )
S_CLASS( ComboBox , "Dataentry_Combobox_Style"            )
S_CLASS( HyperLink, "HyperLink"                           )
S_CLASS( TagEuDesc, "TagnameEUdesc"                       )
S_CLASS( PV       , "PV"                                  )
S_CLASS( AlarmEnbS, "AlarmEnbState"                       )
S_CLASS( AlarmType, "AlarmTypes"                          )
S_CLASS( Frame    , "Frame"                               )
S_CLASS( ExecState, "ExecState"                           )
S_CLASS( SimState , "SimState_Style"                      )
S_CLASS( ReadOnlyL, "ReadOnly_Alphatext_LeftAlign_Style"  )
S_CLASS( ReadOnlyR, "ReadOnly_Alphatext_RightAlign_Style" )
S_CLASS( TitleBarR, "Titlebar_AlphaNumeric_Right_Style"   )
S_CLASS( TxtMode, "TxtMode")
S_CLASS( ConAlpOP, "ConAlpOP")
S_CLASS(PlgIn_RegValve_Close, "PlgIn_RegValve_Close")
S_CLASS(PlgOut_RegValve_Close, "PlgOut_RegValve_Close")
S_CLASS(OvlBody_Pump_Stop, "OvlBody_Pump_Stop")
S_CLASS(OvlBody_Blower_Stop, "OvlBody_Blower_Stop")
S_CLASS(PlgIn_OnOffValve_Close, "PlgIn_OnOffValve_Close")
S_CLASS(PlgOut_OnOffValve_Close, "PlgOut_OnOffValve_Close")
S_CLASS(WdgC_MOV_Close, "WdgC_MOV_Close")
S_CLASS(PlgOut_MOV_Close, "PlgOut_MOV_Close")
S_CLASS(PlgIn_MOV_Close, "PlgIn_MOV_Close")
S_CLASS(ScTxtSelectBox_NotSelected, "ScTxtSelectBox_NotSelected")
S_CLASS(T_SOFT2PumpsIn1,"T_SOFT2PumpsIn1")
S_CLASS(RecAlm_MOS_off,"RecAlm_MOS_off")

S_CLASS(TxtError_NoError,"TxtError_NoError")
S_CLASS(RecPV_LK2B_Normal,"RecPV_LK2B_Normal")
S_CLASS(TxtCText_LK2B_Normal,"TxtCText_LK2B_Normal")
S_CLASS(RecPV_LK2B_Fail,"RecPV_LK2B_Fail")
S_CLASS(TxtCText_LK2B_Fail,"TxtCText_LK2B_Fail")
S_CLASS(PlgInterLock_Active,"PlgInterLock_Active")
S_CLASS(PlgInterLock_Inactive,"PlgInterLock_Inactive")
S_CLASS(LinBypass_Active,"LinBypass_Active")
S_CLASS(LinBypass_Inactive,"LinBypass_Inactive")
S_CLASS(LinOutBypass_Inactive,"LinOutBypass_Inactive")
S_CLASS(LinOutBypass_Active,"LinOutBypass_Active")
S_CLASS(RecPV_Cause_Fail,"RecPV_Cause_Fail")
S_CLASS(TxtCText_Cause_Fail,"TxtCText_Cause_Fail")
S_CLASS(TxtCText_Cause_Normal,"TxtCText_Cause_Normal")
S_CLASS(RecPV_MO_Normal,"RecPV_MO_Normal")
S_CLASS(RecPV_MO_Fail,"RecPV_MO_Fail")
