Enumeration(ACTCOMMAND,"Activity Module Command",None,Start,Hold,Stop,Abort,Remove,Def=None)
Boolean_A(ACTIVEHANDLR,"Active Handler Type",8,false)
/*STRUCT(ACTIVELOC)
INTEGER_S(ACTIVELOC,HANDLER,"Active Handler")
INTEGER_S(ACTIVELOC,HANDLERN,"Active Handler Number")
INTEGER_S(ACTIVELOC,HNDTYPE,"Active Handler Type")
INTEGER_SA(ACTIVELOC,STEP,15,"Active Step")
FLAG_SA(ACTIVELOC,STEPICOMP,10,"Active Step Instr Comp")
FLAG_SA(ACTIVELOC,STEPIPEND,10,"Active Step Instr Pend")
INTEGER_SA(ACTIVELOC,STEPN,15,"Active Step Number")
INTEGER_SA(ACTIVELOC,TIME,15,"Active Step Time")
STRUCT_END(ACTIVELOC)*/
Enumeration(ATLOADCMD,"Alias table load command",NONE,START,END,FAIL,Def=NONE)
Enumeration(ATLOADSTATE,"Alias table load state",Failed,LOADINGMOD,LOADINGTABLE,WAITINGEND,COMPLETE,Def=Failed)
Integer(AUXCMD,"Auxiliary SCM Command",0)
Integer(AUXREQ,"Auxiliary SCM Request",0)
Real_A(AUXREQDATA,"Auxiliary SCM Request Data",5,0)
Integer(AUXSTS,"Auxiliary SCM Status",0)
Enumeration(CEESTATE,"CEE State",IDLE,RUN,FAIL,NotLoaded,Def=FAIL)
Enumeration(CHKPTSVSTS,"Checkpoint service status",Ok,NOTOK,Def=NOTOK)
Enumeration(CMDEXEC,"SCM Exec Command",None,Resume,CheckConfig,Def=None)
Enumeration(COMMAND,"SCM Command",None,Inactive,Start,Reset,Interrupt,Restart,Hold,Stop,Abort,Resume,Active,Cancel,Def=None)
Enumeration(EXECSTS,"SCM Exec Status",Ok,Bypass,Info,Warning,Fail,Error,OkPaused,BypassPaused,InfoPaused,WarnPaused,FailPaused,ErrorPaused,Disabled,NoTransition,Def=Ok)
Enumeration(STATE,"SCM State",Loading,Loaded,Inactive,Validated,Running,Complete,Checking,Idle,Interrupting,Interrupted,Restarting,Restarted,Holding,Held,Stopping,Stopped,Aborting,Aborted,CommErr,Starting,Started,Def=Loaded)
Enumeration(MODEATTR,"",Operator=1,Program,Def=Operator)
Real_A(RECTARGET,"",50,NaN)
Integer(activePhase,"",0)