LONG
TAB("Режим колонны",1)
PARM( P_top, "#Давление верха(а)")
PARM( Flow_out, "#Поток наружу")
PARM( Flow_1, "#Поток 1 т.")
PARM( WriteBalance, "#Вывести баланс")
PARM( Work, "#Работает" )
ETAB
TAB("Дополнительные параметры",4)
PARM_D( Lev_Voronka, "Уровень воронки", 0.1 )
PARM( Flow_src_min, "Минимальный поток источника" )
PARM( Tau_cool, "Время охлаждения тарелок, мин" )
PARM( Tau_gas, "Время нагрева газа, мин" )
PARM( Tau_sliv, "Время слива тарелок, мин" )
PARM( T_min, "#Минимальная Т" )
PARM( T_max, "#Максимальная Т" )
//PARM( Use_min_max, "Использовать ограничения температур")
PARM( Calc_Flow_T, "Рассчитывать т-ры потоков источников")
PARM( P_Top_Z, "Заданное давление верха(а)")
PARM( n_Comp_Balance, "Баланс по компоненте" )
PARM( Comp_Balance_Name, "Баланс по этой компоненте" )
//PARM( n_Comp_Delete, "#Убрать компоненту" )
PARM( CanOverflow, "Возможно переполнение" )
PARM( k_P_stage, "Скорость изменения давления тарелок" )
PARM( dt_Vol, "dt псевдообъема")
PARM_B( CaclOnVol, "Расчет давления через объем", false)
PARM_B( UseGasOut, "Учет выхода газа из куба", false)
//PARM_B( Use_NE, "Неравновесные тарелки", false )
//PARM_D ( Vol_Stage, "Объем тарелок", 1. )
//PARM_D( k_GL, "Теплообмен газ-жидкость", 10000. )

//PARM( Omega_Top, "Проходимость верха")
PARM( Omega_Def, "Проходимость при разгерметизации")
PARM ( Ksi_R, "Отн. скорость испарения" )
PARM ( Eps_Gas, "Смешивание газов" )
PARM ( QuickX, "Ускоренное смешивание жидкости" )
PARM ( ShowModelTAB, "Показывать закладки тарелок" )
PARM ( SetPsrc, "Задать сглаживание" )
PARM ( kSrcPlus, "Сглаживание вверх" )
PARM ( kSrcMin, "Сглаживание вниз" )
PARM ( kInertHeat, "Инерционность тепло-бмена" )
PARM ( kInertVout, "Инерционность газо-обмена" )
PARM ( QuickGas, "Отн. скорость опустошения" )
PARM ( CalckVout, "#Расчет к-тов связи вход-выход" )
PARM_I ( n1mixT, "1-ая тарелка", -1 )
PARM_D ( Ext_T, "Внешняя т-ра", 0. )
PARM_I ( nResmixT, "Датчик", -1 )
PARM_D ( Alfa_n1, "Вклад 1-го", 0. )
ETAB
ELONG
