YPARM_S(Comment,64,"ETCM")
YPARM_I(AlarmLevel,12,"EALA")
YPARM_Dref(HH,W->SH,"----")
YPARM_Dref(PH,W->SH,"----")
YPARM_Dref(PL,W->SL,"----")
YPARM_Dref(LL,W->SL,"----")
YPARM_D(DL,1000,"----")
YPARM_Dref(MH,W->MSH,"----")
YPARM_Dref(ML,W->MSL,"----")
YPARM_Dref(PRE,W->MSL,"----")
YPARM_D(LPV,0,"----")
YPARM_D(ILST,0,"----")
YPARM_D(PLST,0,"----")
YPARM_D(BSET,0,"----")
YPARM_D(LK,100,"----")
YPARM_I(TU,0,"")
YPARM_I(TD,0,"")
YPARM_I(TW,0,"")
YPARM_I(ZONE,0,"")//0-11
YPARM_DD(SH,SL,DBL_MAX,DBL_MAX,"ESCL","%D:%D") 
YPARM_D(MSH,DBL_MAX,"----")
YPARM_D(MSL,DBL_MAX,"----")
YPARM_Dref(OPHI,W->MSH,"----")
YPARM_Dref(OPLO,W->MSL,"----")
YPARM_L(InputSignalConversion,0,"EINP", "%{LINEAR;SQRT;BTHPUL;SUBSYS}")
//SKIP("ESUM")//Totalizer time unit, Totalizer low input cut value
YPARM_L(OutputSignalConvertion,0,"OUTB","%{LINEAR;2ST;3ST;SUBSYS;SUBWFT}")
YPARM_S(cMes,8,"EUNT")
YPARM_L(INLL,0,"INLL","%{NO;LL}")
YPARM_L(INHL,0,"INHL","%{NO;H;L;HL}")
YPARM_I(FLCH,0,"FLCH")
YPARM_B(WIOP,false,"WIOP")
YPARM_B(WELL,false,"WELL")
YPARM_B(WEHI,false,"WEHI")
YPARM_B(WELO,false,"WELO")
YPARM_B(WEPL,false,"WEPL")
YPARM_DB(Out_VL,MAN_bypass,100.,false,"OVLM", "%D:%B")