YPARM_S(Comment,64,"ETCM")
YPARM_I(PH,0x7FFFFF,"----")
YPARM_I(PL,0,"----")
YPARM_I(DL,0x7FFFFF,"----")
YPARM_B(Bit_Inversion,false,"BITS")
YPARM_I(Number_Of_Bits_Input,8,"ISPC")
YPARM_L(Code_Conversion,0,"CODE","%{NO;BCD}")
