YPARM_S(Comment,64,"ETCM")
YPARM_DD(SH,SL,DBL_MAX,DBL_MAX,"ESCL","%D:%D") 
//
YPARM_I(AlarmLevel,12,"EALA")
YPARM_Dref(HH,W->SH,"----")
YPARM_Dref(PH,W->SH,"----")
YPARM_Dref(PL,W->SL,"----")
YPARM_Dref(LL,W->SL,"----")
YPARM_D(SVH,100.,"----")
YPARM_D(SVL,0.,"----")
//
YPARM_D(MTM,0.,"")
YPARM_L( Answerback_Check,3, "ABCD", "%{NO;OPEN;CLOSE;BOTH}")
YPARM_L( Output_On_IL3, 0, "ILSO", "%{OFF;ON;STOP}" ) 
YPARM_L( Output_On_IL2, 0, "ILST", "%{OFF;ON;STOP}" )
YPARM_L( Fallback_operation, 0, "ABFB", "%{NO;ANS-;ANS+;BOTH}" )
YPARM_L( IL_Signal_Direction, 0, "ILID", "%{DIRECT;REVERSE}" )
YPARM_B( Answerback_Trk, true, "ABTK")
YPARM_L( Numb_of_IP, 0, "EINP", "%{2ST;3ST}" )
YPARM_L( Answer_Direction, 0, "ABID", "%{DIRECT;REVERSE;INVERTDIR;INVERTREV}" )
YPARM_L( Output_Conversion3, 0, "OUTH", "%{2ST;2PL;3ST;3PL}" ) 
YPARM_L( Output_Conversion2, 0, "OUTW", "%{2ST;2PL;3ST;3PL}" ) 
YPARM_L( Out_Action_Direction, 0, "OADR", "%{DIRECT;REVERSE;INVERTDIR;INVERTREV}" );
YPARM_L( Hold_Output_when_IL, 0, "ILSH", "%{NO;YES}" )