//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3
define(
[
  'knockout'
], 

  	function(ko) {
    		var DirectionIndicatorBinding = {
    			shapesPath: null
  	}
  
 	DirectionIndicatorBinding.init = function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
  	}
  
  DirectionIndicatorBinding.update = function(element, valueAccessor, allBindingsAccessor, viewModel, bindingContext) {
  	var imageFile = 'blank.png';  
   	var value = ko.utils.unwrapObservable(valueAccessor());
	if(value == 0) {
        	imageFile = 'normal-state.png';
      	}
		
        if(value < 0) {
        	imageFile = 'down-arrow.png';
        }
		
        if(value > 0) {
        	imageFile = 'up-arrow.png';
      	}
    	var path = DirectionIndicatorBinding.shapesPath + '/directionindicator/' + imageFile;

    	element.src = path;
    	}

    return DirectionIndicatorBinding;    
});

