//COPYRIGHT (c) 2013
//HONEYWELL INTERNATIONAL INC.
//ALL RIGHTS RESERVED

//Legal rights of Honeywell International Inc. in this software is distinct
//from ownership of any medium in which the software is embodied. Copyright
//notices must be reproduced in any copies authorized by Honeywell International Inc.
// Generated by CoffeeScript 1.3.3

define(
[
  './DirectionIndicatorBinding', 
  'text!./DirectionIndicatorTemplate.htm'
], 
	
	function(DirectionIndicatorBinding, DirectionIndicatorTemplate) 	{
		var ShapeModule = {
			_config: {}
	};

	ShapeModule.init = function(config) 	{		
		ShapeModule._config = config;
		return true;
	}

	ShapeModule.getViewTemplates = function() 	{
		return {
			hscDirectionIndicatorTemplate: DirectionIndicatorTemplate,
     			MAIN_VIEW_TEMPLATE: 'hscDirectionIndicatorTemplate'
		};
	}

	ShapeModule.getBindings = function() {	
		DirectionIndicatorBinding.shapesPath = ShapeModule._config.shapesPath;
		return {
			hscDirectionIndicator: DirectionIndicatorBinding
		}
	}

  	ShapeModule.getDependencies = function() {
    		return null;
  	}
  
	ShapeModule.createViewModel = function()	{ 
		return 'PointParamViewModel';
	}
  
	return ShapeModule;
});
