String_K(NAME,"",32*4)
String_K(ACTUATOR_ID_1,"actuator_id_1",16*4)
String_K(ACTUATOR_ID_2,"actuator_id_2",16*4)
String_K(ACTUATOR_ID_3,"actuator_id_3",16*4)
String_K(ACTUATOR_ID_4,"actuator_id_4",16*4)
String_K(ACTUATOR_MAN_1,"actuator_man_1",16*4)
String_K(ACTUATOR_MAN_2,"actuator_man_2",16*4)
String_K(ACTUATOR_MAN_3,"actuator_man_3",16*4)
String_K(ACTUATOR_MAN_4,"actuator_man_4",16*4)
String_K(ACTUATOR_SER_NUM_1,"actuator_ser_num_1",16*4)
String_K(ACTUATOR_SER_NUM_2,"actuator_ser_num_2",16*4)
String_K(ACTUATOR_SER_NUM_3,"actuator_ser_num_3",16*4)
String_K(ACTUATOR_SER_NUM_4,"actuator_ser_num_4",16*4)
String_K(BLKTYPE,"Block Type",33*4)
/*STRUCT(BLOCK_ALM)
ENUM_S(BLOCK_ALM,ALARM_STATE,"Alarm State",Undefined,Clear-reported,Clear-not reported,Active-reported,Active-not reported,Def=)
ENUM_S(BLOCK_ALM,SUB_CODE,"Subcode",Other,BlockConfiguration,LinkConfiguration,SimulationActive,LocalOverride,DeviceFaultState,DeviceMaintenance,InputFailure,OutputFailure,MemoryFailure,LostStaticData,LostNVData,ReadbackCheck,MaintenanceNeeded,PowerUp,OutOfService,Def=)
ENUM_S(BLOCK_ALM,UNACKNOWLEDGED,"Unacknowledged",Undefined,Acknowledged,Unacknowledged,Def=)
STRUCT_END(BLOCK_ALM)*/
String_K(BLOCKTAG,"Block tag",32*4)
/*Enumeration(CALIB_DO_VALVE_1,"calib_do_valve_1",0x00-inputs INV, sens1 valve open,0x01-inputs INV, sens1 valve close,0x02-inputs notINV, sens1 valve open,0x03-inputs notINV, sens1 valve close,Def=)
Enumeration(CALIB_DO_VALVE_2,"calib_do_valve_2",0x00-inputs INV, sens1 valve open,0x01-inputs INV, sens1 valve close,0x02-inputs notINV, sens1 valve open,0x03-inputs notINV, sens1 valve close,Def=)
Enumeration(CALIB_DO_VALVE_3,"calib_do_valve_3",0x00-inputs INV, sens1 valve open,0x01-inputs INV, sens1 valve close,0x02-inputs notINV, sens1 valve open,0x03-inputs notINV, sens1 valve close,Def=)
Enumeration(CALIB_DO_VALVE_4,"calib_do_valve_4",0x00-inputs INV, sens1 valve open,0x01-inputs INV, sens1 valve close,0x02-inputs notINV, sens1 valve open,0x03-inputs notINV, sens1 valve close,Def=)
Integer(CBBLOCKPROP,"Block Property")
Enumeration(CHECKBACK_1,"checkback_1",0x00 - Status OK,0x01 - Travel count limit exceeded,0x02 - Travel time OPEN exceeded,0x03 - Travel count limit and travel time OPEN exceeded,0x04 - Travel time CLOSE exceeded,0x05 - Travel count limit and travel time CLOSE exceeded,0x06 - Travel time OPEN and travel time CLOSE exceeded,0x07 - Travel count limit and travel time OPEN and travel time 7,Def=)
Enumeration(CHECKBACK_2,"checkback_2",0x00 - Status OK,0x01 - Travel count limit exceeded,0x02 - Travel time OPEN exceeded,0x03 - Travel count limit and travel time OPEN exceeded,0x04 - Travel time CLOSE exceeded,0x05 - Travel count limit and travel time CLOSE exceeded,0x06 - Travel time OPEN and travel time CLOSE exceeded,0x07 - Travel count limit and travel time OPEN and travel time 7,Def=)
Enumeration(CHECKBACK_3,"checkback_3",0x00 - Status OK,0x01 - Travel count limit exceeded,0x02 - Travel time OPEN exceeded,0x03 - Travel count limit and travel time OPEN exceeded,0x04 - Travel time CLOSE exceeded,0x05 - Travel count limit and travel time CLOSE exceeded,0x06 - Travel time OPEN and travel time CLOSE exceeded,0x07 - Travel count limit and travel time OPEN and travel time 7,Def=)
Enumeration(CHECKBACK_4,"checkback_4",0x00 - Status OK,0x01 - Travel count limit exceeded,0x02 - Travel time OPEN exceeded,0x03 - Travel count limit and travel time OPEN exceeded,0x04 - Travel time CLOSE exceeded,0x05 - Travel count limit and travel time CLOSE exceeded,0x06 - Travel time OPEN and travel time CLOSE exceeded,0x07 - Travel count limit and travel time OPEN and travel time 7,Def=)*/
Integer(COLLECTION_DIR_1,"collection_directory",0)
Integer(COLLECTION_DIR_2,"collection_directory",0)
Integer(COLLECTION_DIR_3,"collection_directory",0)
Integer(COLLECTION_DIR_4,"collection_directory",0)
Integer(DDITEM,"Block DD Item",0)
String_K(DESC,"Description",132*4)
Integer(DEVICE,"Associated Device",0)
Boolean(IS_IBLOCK,"Is this an Instantiable Block",false)
Boolean(METHODPRESENT,"Method Present",false)
Integer(ORDERINCM,"Execution Order in CM",10)
Boolean(PARTIALLOAD,"Partial Load",false)
String_K(TAG_DESC,"Block Tag Description",32*4)
//Enumeration(TRANSDUCER_TYPE_1,"transducer_type",Standard Pressure with Calibration,Standard Temperature with Calibration,Standard Dual Temperature with Calibration,Standard Radar Level with Calibration,Standard Flow with Calibration,Standard Basic Positioner Valve,Standard Advanced Positioner Valve,Standard Discrete Valve,Other,Def=)
//Enumeration(TRANSDUCER_TYPE_2,"transducer_type",Standard Pressure with Calibration,Standard Temperature with Calibration,Standard Dual Temperature with Calibration,Standard Radar Level with Calibration,Standard Flow with Calibration,Standard Basic Positioner Valve,Standard Advanced Positioner Valve,Standard Discrete Valve,Other,Def=)
//Enumeration(TRANSDUCER_TYPE_3,"transducer_type",Standard Pressure with Calibration,Standard Temperature with Calibration,Standard Dual Temperature with Calibration,Standard Radar Level with Calibration,Standard Flow with Calibration,Standard Basic Positioner Valve,Standard Advanced Positioner Valve,Standard Discrete Valve,Other,Def=)
//Enumeration(TRANSDUCER_TYPE_4,"transducer_type",Standard Pressure with Calibration,Standard Temperature with Calibration,Standard Dual Temperature with Calibration,Standard Radar Level with Calibration,Standard Flow with Calibration,Standard Basic Positioner Valve,Standard Advanced Positioner Valve,Standard Discrete Valve,Other,Def=)
Integer(TRAVEL_COUNT_1,"travel_count_1",0)
Integer(TRAVEL_COUNT_2,"travel_count_2",0)
Integer(TRAVEL_COUNT_3,"travel_count_3",0)
Integer(TRAVEL_COUNT_4,"travel_count_4",0)
Integer(TRAVEL_COUNT_LIM_1,"travel_count_lim_1",0)
Integer(TRAVEL_COUNT_LIM_2,"travel_count_lim_2",0)
Integer(TRAVEL_COUNT_LIM_3,"travel_count_lim_3",0)
Integer(TRAVEL_COUNT_LIM_4,"travel_count_lim_4",0)
/*STRUCT(UPDATE_EVT)
ENUM_S(UPDATE_EVT,UNACKNOWLEDGED,"Unacknowledged",Undefined,Acknowledged,Unacknowledged,Def=)
ENUM_S(UPDATE_EVT,UPDATE_STATE,"Update State",Undefined,Update reported,Update not reported,Def=)
STRUCT_END(UPDATE_EVT)*/
String_K(VALVE_ID_1,"valve_id_1",16*4)
String_K(VALVE_ID_2,"valve_id_2",16*4)
String_K(VALVE_ID_3,"valve_id_3",16*4)
String_K(VALVE_ID_4,"valve_id_4",16*4)
String_K(VALVE_MAN_1,"valve_man_1",16*4)
String_K(VALVE_MAN_2,"valve_man_2",16*4)
String_K(VALVE_MAN_3,"valve_man_3",16*4)
String_K(VALVE_MAN_4,"valve_man_4",16*4)
String_K(VALVE_SER_NUM_1,"valve_ser_num_1",16*4)
String_K(VALVE_SER_NUM_2,"valve_ser_num_2",16*4)
String_K(VALVE_SER_NUM_3,"valve_ser_num_3",16*4)
String_K(VALVE_SER_NUM_4,"valve_ser_num_4",16*4)
/*Enumeration(XD_ERROR_1,"xd_error",Unspecified error,General error,Calibration error,Configuration error,Electronics Failure,Mechanical Failure,I/O Failure,Data Integrity Error,Software Error,Algorithm Error,Def=)
Enumeration(XD_ERROR_2,"xd_error",Unspecified error,General error,Calibration error,Configuration error,Electronics Failure,Mechanical Failure,I/O Failure,Data Integrity Error,Software Error,Algorithm Error,Def=)
Enumeration(XD_ERROR_3,"xd_error",Unspecified error,General error,Calibration error,Configuration error,Electronics Failure,Mechanical Failure,I/O Failure,Data Integrity Error,Software Error,Algorithm Error,Def=)
Enumeration(XD_ERROR_4,"xd_error",Unspecified error,General error,Calibration error,Configuration error,Electronics Failure,Mechanical Failure,I/O Failure,Data Integrity Error,Software Error,Algorithm Error,Def=)
*/