Real_A(C,"Expression results",8,NaN)
Enumeration_A(CONFIGCODE,"Config Code",10,None,Ok,UnknownError,ImplicitConv,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ConstExprRem,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,Def=None)
Enumeration_A(CONFIGSTS,"Config Status",10,Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=Error)
Enumeration_A(CSTS,"Expression statuses",8,BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Enumeration_A(EXECCODE,"Execution Code",10,None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,Def=None)
Enumeration_A(EXECSTS,"Execution Status",10,Ok,Bypass,Info,Warning,Fail,Error,Def=Bypass)
String_A(EXECDESC,"ExecCode Desc",39 * 4,10)
Real_A(P,"P input Value",10,NaN)
Enumeration_A(PSTS,"P input Status",10,BAD,UNCERTN,NORMAL,MANUAL,INITACK,INITREQ,INITBAD,Def=BAD)
Real(PV,"PV Value",NaN)
Enumeration(PVSTS,"Process Variable (PV) Status",Bad,Uncertain,Normal,Manual,Def=Bad)
Struct4B(PVSTSFL,"",BAD,MAN,NORM,UNCER)
Real_A(PP,"",10,NaN)