Real(ADVDEV,"Advisory Deviation",0)
Struct_REBEIIIR(ADVDEVALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
Struct_REBEIIR(PVHHALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TP)
Real(ALMDB,"Overall Deadband for all analog alarms",0)
Enumeration(ALMDBU,"Overall Deadband unit for all analog alarms",Percent,EngineeringUnits,Def=Percent)
Integer(ALMTM,"Filter Time for all alarms",0)
Enumeration_A(ARWNET,"Network Windup Status",8,Normal,Hi,Lo,HiLo,Def=Normal)
Enumeration(ARWNETIN,"Anti-Reset Windup Network Status Input ",Normal,Hi,Lo,HiLo,Def=Normal)
Enumeration(ARWOP,"Output Windup Status",Normal,Hi,Lo,HiLo,Def=Normal)
Enumeration(BADCTLOPT,"Indicates what to do when Calculated Variable CV is NaN",No_Shed,ShedHold,ShedLow,ShedHigh,ShedSafe,Def=No_Shed)// (i.e., BADCTLFL = On).
Enumeration(CTLACTN,"Control Action",Direct,Reverse,Def=Direct)// - The output direction of a PID function block (direct or reverse).
Enumeration(CTLEQN,"Control Equation Type",EqA,EqB,EqC,EqD,EqE,EqF,EqG,Def=EqA)
Real(CVEUHI,"CV High Range in EUs",100.)
Real(CVEULO,"CV Low Range in EUs",0.)
Enumeration(CVTYPE,"CV Type",EngrUnits,Percent,Def=EngrUnits)//EngineeringUnits
String_K(DESC,"Block Descriptor",132*4)
Struct_REBEIIIR(DEVHIALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
Struct_REBEIIIR(DEVLOALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
Enumeration(ESWENB,"Ext Mode Switch Enable",DISABLE,ENABLE,Def=DISABLE)
Enumeration(ESWPERM,"Ext Mode Switch Permit",NOTPERM,PERMIT,Def=NOTPERM)
String_K(EUDESC,"Block Engineering Units Descriptor",24*4)
Real(GAINHILM,"Gain High Limit",240.)
Real(GAINLOLM,"Gain Low Limit",0.)
Enumeration(GAINOPT,"Specifies how the PID gain should be calculated",Lin,Gap,Nonlin,Ext,Def=Lin)
Real(GAPHILM,"Gap High Limit",0)
Real(GAPLOLM,"Gap Low Limit",0)
Enumeration(HOLDOPT,"The Hold State Option",None,Man,Auto,Cas,FixedOP,HoldPv,FixedSP,RampedSP,Def=None)
Real_A(INITVAL,"",8,0)
//Boolean_A(INSBLOCK,"",10,false)
Real(K,"Total Gain for Calculated Variable",1.0)
Real(KLIN,"Linear Gain factor",1.)
Real(KMODIFEXT,"External Gain Modifier",1.)
Real(KMODIFGAP,"Gap Gain factor",1.)
Real(KMODIFNL,"Nonlinear Gain Modifier",NaN)
Boolean(LEGACYGAP,"Legacy gap option",false)
Boolean_A(MODEAPPL,"",4,false)//MODEAPPL[1] is On, if Manual (Man) mode is valid
                              //MODEAPPL[2] is On, if Automatic (Auto) mode is valid
                              //MODEAPPL[3] is On, if Cascade (Cas) mode is valid
Enumeration(MODEPERM,"Mode Permissive",NOTPERM,PERMIT,Def=PERMIT)
Integer(NLFORM,"Non-linear Gain form",1)//Used if GAINOPT = Nonlin (configured)
Real(NLGAIN,"Non-linear Gain factor",0.)//Used if GAINOPT = Nonlin (configured)
String_K(NAME,"",32*4)
Enumeration(NORMMODE,"",Man,Auto,Cas,Bcas,None,Def=None)
Enumeration(NORMMODEATTR,"Normal Mode Attribute",None,Operator,Program,Normal,Def=None)
//Integer(NUMINSERT,"",0)
Integer(NUMPRI,"# of Primaries",0)
Struct_3R(OPBIAS,"",FIX,FLOAT,RATE)
Struct_REBEIIR(PVHIALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TP)
Real(OPEXHILM,"OP Extended High Limit (in percentage)",106.9)
Real(OPEXLOLM,"OP Extended Low Limit (in percentage)",-6.9)
Real(OPHILM,"OP High Limit in %",105.)
Struct_REBEIIIR(OPLOALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
Real(OPLOLM,"",-5.)
Struct_REBEIIIR(OPHIALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
Real(OPMINCHG,"OP Minimum Change Limit (in Percent)",0)//
Real(OPROCLM,"OP Rate of Change Limit (in Percent per minute)",NaN)
//Integer(ORDERINCM,"Execution order",10)
Enumeration(OUTIND,"Output Indication",Direct,Reverse,DirectDisplnd,ReverseDisplnd,Def=Direct)
Enumeration(OUTTYPE,"Defines whether the connected output is a digial or analog type",Digital,Analog,Def=Analog)
Boolean(PUSHSP,"Enables pushing SP from another block",false)
Real(PVEUHI,"",100.)
Real(PVEULO,"",0.)
Enumeration(PVFORMAT,"PV Display Format",D0,D1,D2,D3,Def=D1)//D0 (-XXXXXX.) D1 (-XXXXX.X) D2 (-XXXX.XX) D3 (XXX.XXX)
Enumeration(PVMANOPT,"",NoShed,ShedHold,ShedLow,ShedHigh,ShedSafe,Def=ShedHold)
Enumeration(PVTRAKOPT,"PV Tracking Option",NoTrack,Track,Def=NoTrack)
Enumeration(PVTRAKOPTAI,"PV Tracking Option",NoTrack,Track,Def=NoTrack)
Enumeration(RESTARTOPT,"Restart Option",None,LastReq,Def=None)//Indicates activity for device when ControlModule.SCMSTATE returns to Restarting or Running
Struct_BBEI(SIALM,FL,OPT,ALPRIOR,PR,SV)
Enumeration(SIOPT,"Indicates what to do when Calculated Variable CV is NaN",No_Shed,ShedHold,ShedLow,ShedHigh,ShedSafe,Def=No_Shed)// (i.e., BADCTLFL = On).
Real(SPEUHI,"SP High Range (in Engineering Units)",100)//This value corresponds to 100% of full-scale value
Real(SPEULO,"SP Low Range (in Engineering Units)",0)//This value corresponds to 0% of full-scale value
Enumeration(SPFORMAT,"SP Display Format",D0,D1,D2,D3,Def=D1)//D0 (-XXXXXX.) D1 (-XXXXX.X) D2 (-XXXX.XX) D3 (XXX.XXX)
Real(SPHILM,"SP High Limit (in Engineering Units)",100.)//Defines the upper limit for the SP value
Real(SPLOLM,"SP Low Limit (in Engineering Units)",0.)//Defines the lower limit for the SP value
Real(SPTVDEVMAX,"SP Target Value Maximum Deviation",NaN)//The maximum deviation allowed during set point ramping, in engineering units
Real(SPTVNORMRATE,"SP Target Value Normal Ramp Rate",NaN)//The rate that the set point will ramp, in engineering units/min
Enumeration(STARTOPT,"Starting State Option",None,MAN,Auto,Cas,FixedOP,HoldPV,FixedSP,RampedSP,Def=None)
Real(STARTVAL,"Starting State Value",NaN)//The value used for setting OPREQ, when STARTOPT is FixedOP; or for setting SPREQ or SPTVREQ, when STARTOPT is FixedSP or RampedSP
Enumeration(STOPOPT,"Fail State Option",None,MAN,Auto,Cas,FixedOP,HoldPV,FixedSP,RampedSP,Def=None)
Real(STOPRATE,"",NaN)
Real(STOPVAL,"",NaN)
Real(T1HILM,"T1 High Limit",1440.)
Real(T1LOLM,"T1 Low Limit",0.)
Real(T2HILM,"T2 High Limit",1440.)
Real(T2LOLM,"T2 Low Limit",0.)
Enumeration(TMOUTMODE,"Timeout Shed Mode",None,Auto,Man,Def=Man)//The mode that a function block sheds to when an initializable input times out
Integer(TMOUTTIME,"Timeout Time",0)//seconds
Real(BADOCOPT,"Bad Output Conn Option",0)
Enumeration(BADOCOPTENB,"Enable Bad Output Connection Option",DISABLE,ENABLE,Def=DISABLE)
Real(BFF,"Feedforward Input Bias",0)
Enumeration(EQNEUNITSOPT,"P-only (EqnE) Units Option",EUs,Percent,Def=EUs)
Enumeration(FFOPT,"Feedforward Option",ADD,MULTIPLY,Def=ADD)
Real(HOLDRATE,"Hold State SP Rate",NaN)
Real(HOLDVAL,"Hold State Value",NaN)
Real(KFF,"Feedforward Input Gain",0)
Enumeration(MODEATTR,"Mode Attribute",None,Operator,Program,Normal,Def=Operator)
String_K(OPERTAGDESC,"Operator Tag Descriptor",15*4)
Real(OPTOL,"OP Tolerance limit in %",0)
Real(PREFSP,"Preferred Setpoint",0)
Real(SAFEOP,"Safe OP Value in %",NaN)
Real(SPTOL,"SP Tolerance",0)

Struct_EIE(HIALM,ALPRIOR,PR,SV,PIDALMTYPE,TYPE)
Boolean(INALM,"",false)
Real(T1,"Integral Time Constant (in Minutes)",0)
Real(T2,"Derivative Time Constant (in Minutes)",0)
/*
//INTEGER_A(ASSOCBLOCK,1000,"Associated Block")
//STRING(BLCKCOMMENT1,40,"Block Comment 1")
//STRING(BLOCKTYPENAME,50,"Name of the Block Type")
//STRING(BLOCKTYPNAME,101,"Block Type Name")
//INTEGER(CBBLOCKPROP,"Block Property")
//INTEGER_A(INSBLOCK,10,"Name of inserted block")
//ENUM_A(INSERTSTS,10,"Unloaded,Normal,Exception,Termination,Dormant,Notsupported","Insertion status")
//FLAG(INSFAILFL,"Insertion fail flag")
//ENUM_A(INSTYPE,10,"Post_Input,Pre_Alg,Ctl_Alg,Post_Alg,Post_Ctlout","Insertion Type")
//INTEGER(NUMBLOBS,"Number of Dynamic State Blobs")
//INTEGER(NUMINSERT,"Number of insertions")
STRUCT(OPSECDATA)
ENUM_S(OPSECDATA,ARWSTS,"NORMAL,HI,LO,HILO","OP SECDATA.ARWSTS")
DOUBLE_S(OPSECDATA,EUHI,"OP SECDATA.EUHI")
DOUBLE_S(OPSECDATA,EULO,"OP SECDATA.EULO")
FLAG_S(OPSECDATA,INITREQ,"OP SECDATA.INITREQ")
DOUBLE_S(OPSECDATA,INITVAL,"OP SECDATA.INITVAL")
INTEGER_S(OPSECDATA,ONESHOT,"OP SECDATA.ONESHOT")
DOUBLE_S(OPSECDATA,ORFBVAL,"OP SECDATA.ORFBVAL")
FLAG_S(OPSECDATA,OROFFSET,"OP SECDATA.OROFFSET")
STRUCT_END(OPSECDATA)

STRUCT(PRIMDATA)
ENUM_SA(PRIMDATA,ARWSTS,8,"NORMAL,HI,LO,HILO","Windup status for Primary")
DOUBLE_SA(PRIMDATA,EUHI,8,"EUHI for Primary")
DOUBLE_SA(PRIMDATA,EULO,8,"EULO for Primary")
FLAG_SA(PRIMDATA,HISELECT,8,"Override type for Primary")
FLAG_SA(PRIMDATA,INITIALIZABLE,8,"Primary Initializable type")
FLAG_SA(PRIMDATA,INITSTS,8,"INIT status for Primary")
DOUBLE_SA(PRIMDATA,INITVAL,8,"INITVAL for Primary")
FLAG_SA(PRIMDATA,LOCALMAN,8,"LOCALMAN for Primary")
INTEGER_SA(PRIMDATA,ONESHOT,8,"One shot sequence for Primary")
ENUM_SA(PRIMDATA,ORFBSTS,8,"NOTCON,SEL,NOTSEL","Override Status for Primary")
DOUBLE_SA(PRIMDATA,ORFBVAL,8,"OVerride feedvack value for Primary")
FLAG_SA(PRIMDATA,OROFFSET,8,"OROFFSET for Primary")
FLAG_SA(PRIMDATA,PROPOVRD,8,"Override propagation enable")
STRUCT_END(PRIMDATA)

//INTEGER(PVRAWREF,"PVRAW Reference")
//INTEGER(SECBLOCKID,"Secondary BlockId Info")
STRUCT(SECDATAIN)
ENUM_S(SECDATAIN,ARWSTS,"NORMAL,HI,LO,HILO","Windup status")
DOUBLE_S(SECDATAIN,EUHI,"Euhi")
DOUBLE_S(SECDATAIN,EULO,"Eulo")
FLAG_S(SECDATAIN,HISELECT,"Hiselect")
FLAG_S(SECDATAIN,INITSTS,"INIT status")
DOUBLE_S(SECDATAIN,INITVAL,"Initval")
FLAG_S(SECDATAIN,LOCALMAN,"Localman")
INTEGER_S(SECDATAIN,ONESHOT,"oneshot sequence")
ENUM_S(SECDATAIN,ORFBSTS,"NOTCON,SEL,NOTSEL","Override status")
DOUBLE_S(SECDATAIN,ORFBVAL,"Orfbval")
FLAG_S(SECDATAIN,OROFFSET,"Override offset")
FLAG_S(SECDATAIN,PROPOVRD,"Propovrd")
STRUCT_END(SECDATAIN)
//ENUM_A(SECINITOPT,8,"DISABLE,ENABLE","Secondary Init Option")

STRUCT(UNCMDCHGALM)
FLAG_S(UNCMDCHGALM,ALL,"")
FLAG_S(UNCMDCHGALM,FL,"Uncmd Chg Alm Flag")
ENUM_S(UNCMDCHGALM,OPT,"DISABLE,ENABLE","Uncmd Chg Alm Option")
ENUM_S(UNCMDCHGALM,PR,"NONE,JOURNAL,LOW,HIGH,URGENT","Uncmd Chg Alm Priority")
INTEGER_S(UNCMDCHGALM,SV,"Uncmd Chg Alm Severity")
STRUCT_END(UNCMDCHGALM)
INTEGER(X_BLOCKMEM,"Currently used memory (bytes)")
ENUM(X_NOTIF_ID,"DO NOT USE,BADCTL,OPHIGH,OPLOW,REGSI,DEVHI,DEVLOW,ADVDEV,UNCMDCHG,PREDPVHI,PREDPVLO,PIDPLBADPV","Alarm condition strings")
*/
