String_K(NAME,"Имя",31*4)
String_K(DESC,"Description",132*4)
//Integer_A(ASSOCBLOCK,1000,"Associated Block")
//String_K(BLCKCOMMENT1,40,"Block Comment 1")
//String_K(BLOCKTYPNAME,101,"Block Type Name")
Real(ACCTV,"Accumulator Target Value",0)
Real(C1,"C1 Scale Factor",1.)
Real(C2,"C2 Scale Factor",1.)
//Integer(CBBLOCKPROP,"Block Property")
Enumeration(CMDATTR,"Command Attribute",OPERATOR,OTHERFB,Def=OPERATOR)
Struct_R(CUTOFF,LM,0)//"Cutoff Limit"
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Enumeration(PVEQN,"Bad Input Options",EQA,EQB,EQC,EQD,EQE,EQF,Def=EQA)
Enumeration(PVFORMAT,"PV Display Format",D0,D1,D2,D3,Def=D0)
//String_K(QUALSTATE,100,"Qualification State")
Enumeration(TIMEBASE,"Time base",SECONDS,MINUTES,HOURS,Def=SECONDS)
//Integer(X_BLOCKMEM,"Currently used memory (bytes)")
Real(RESETVAL,"Reset Value",0)
