String_K(NAME,"Имя",32*4)
Real(ALMDB,"Deadband for all Alarms",0)
Enumeration(ALMDBU,"Dband Units for all Alarms",PERCENT,EU,Def=PERCENT)
Integer(ALMTM,"Filter Time for all Alarms",0)
Enumeration(ARWNETIN,"Auxiliary Network Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWOP,"Output Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
Enumeration(ARWOPIN,"Auxiliary Output Windup Status",NORMAL,HI,LO,HILO,Def=NORMAL)
//Integer_A(ASSOCBLOCK,"Associated Block",1000)
Struct_EBEIII(BADCTLALM,ALMALL,ALL,FL,ALPRIOR,PR,SV,TM,TMO)
/*STRUCT(BADCTLALM)
  ENUM_S(BADCTLALM,ALL,"",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  FLAG_S(BADCTLALM,FL,"Bad Ctl Alarm Flag")
  ENUM_S(BADCTLALM,PR,"Bad Ctl Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(BADCTLALM,SV,"Bad Ctl Alarm Severity")
  INTEGER_S(BADCTLALM,TM,"Bad Ctl Alarm On Delay Time")
  INTEGER_S(BADCTLALM,TMO,"Bad Ctl Alarm Off Delay Time")
STRUCT_END(BADCTLALM)*/
Enumeration(BADCTLOPT,"Bad Control Option",NO_SHED,SHEDHOLD,SHEDLOW,SHEDHIGH,SHEDSAFE,Def=NO_SHED)
Real(BADOCOPT,"Bad Output Conn Option",0)
Enumeration(BADOCOPTENB,"Enable Bad Output Connection Option",DISABLE,ENABLE,Def=DISABLE)
/*String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
String_K(BLOCKTYPENAME,"Name of the Block Type",50*4)
String_K(BLOCKTYPNAME,"Block Type Name",101*4)*/
Real(BSHILM,"BS High Limit in EUs",0)
Real(BSLOLM,"BS Low  Limit in EUs",0)
//Integer(CBBLOCKPROP,"Block Property")
Real(CVEUHI,"CV High Range in EUs",0)
Real(CVEULO,"CV Low Range in EUs",0)
Enumeration(CVTYPE,"CV Type",ENGRUNIT,PERCENT,Def=ENGRUNIT)
String_K(DESC,"Description",132*4)
Enumeration(ESWENB,"Ext Mode Switch Enable",DISABLE,ENABLE,Def=DISABLE)
Struct4B(ESWFL,"",AUTO,BCAS,CAS,MAN)
/*STRUCT(ESWFL)
  FLAG_S(ESWFL,ALL,"")
  FLAG_S(ESWFL,AUTO,"Auto Ext Mode Switch")
  FLAG_S(ESWFL,BCAS,"Bcas Ext Mode Switch")
  FLAG_S(ESWFL,CAS,"Cas  Ext Mode Switch")
  FLAG_S(ESWFL,MAN,"Man  Ext Mode Switch")
STRUCT_END(ESWFL)*/
Enumeration(ESWPERM,"Ext Mode Switch Permit",NOTPERM,PERMIT,Def=NOTPERM)
String_K(EUDESC,"Engineering Units",24*4)
Struct_EIE(HIALM,ALPRIOR,PR,SV,RATIOBIASALMTYPE,TYPE)
/*STRUCT(HIALM)
  ENUM_S(HIALM,PR,"High Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(HIALM,SV,"High Alarm Severity")
  ENUM_S(HIALM,TYPE,"High Alarm Flag",NONE,BadCtl,SafetyIlock,DevHi,DevLo,AdvDev,OpHi,OpLo,PredHi,PredLo,UnCmdChg,Def=)
STRUCT_END(HIALM)*/
Enumeration(HOLDOPT,"Hold State Option",None,Man,Auto,Cas,FixedOp,HoldPv,FixedSp,RampedSp,Def=None)
Real(HOLDRATE,"Hold State SP Rate",NaN)
Real(HOLDVAL,"Hold State Value",NaN)
Real_A(INITVAL,"Init Value for Primary",8,0)
//Integer_A(INSBLOCK,"Name of inserted block",10)
Enumeration_A(INSERTSTS,"Insertion status",10,Unloaded,Normal,Exception,Termination,Dormant,Notsupported,Def=Unloaded)
Boolean(INSFAILFL,"Insertion fail flag",false)
Enumeration_A(INSTYPE,"Insertion Type",10,Post_Input,Pre_Alg,Ctl_Alg,Post_Alg,Post_Ctlout,Def=Post_Input)
Boolean_A(MODEAPPL,"Mode Applicability Flags",4,false)
Enumeration(MODEPERM,"Mode Permissive",NOTPERM,PERMIT,Def=NOTPERM)
Enumeration(MODETRACK,"SCM Mode Tracking Option",NONE,ONESHOT,CONTRTN,SEMICONT,CONT,Def=ONESHOT)
Enumeration(NORMMODE,"Normal Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=MAN)
Enumeration(NORMMODEATTR,"Normal Mode Attribute",NONE,OPERATOR,PROGRAM,NORMAL,Def=NONE)
//Integer(NUMBLOBS,"Number of Dynamic State Blobs")
//Integer(NUMINSERT,"Number of insertions")
Struct_3R(OPBIAS,"",FIX,FLOAT,RATE)
/*STRUCT(OPBIAS)
  DOUBLE_S(OPBIAS,FIX,"Fixed Output Bias")
  DOUBLE_S(OPBIAS,FLOAT,"Floating Output Bias")
  DOUBLE_S(OPBIAS,RATE,"Output Bias Rate")
STRUCT_END(OPBIAS)*/
Boolean(OPERTAG,"Operator Tag",false)
String_K(OPERTAGDESC,"Operator Tag Descriptor",15*4)
Real(OPEXHILM,"OP Extended High Limit",106.9)
Real(OPEXLOLM,"OP Extended Low Limit",-6.9)
Struct_REBEIIIR(OPHIALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
/*STRUCT(OPHIALM)
  FLAG_S(OPHIALM,ALL,"")
  DOUBLE_S(OPHIALM,DB,"OP High Alarm Deadband")
  ENUM_S(OPHIALM,DBU,"OP High Alarm Db Units",PERCENT,EU,Def=)
  FLAG_S(OPHIALM,FL,"OP High Alarm Flag")
  ENUM_S(OPHIALM,PR,"OP High Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(OPHIALM,SV,"OP High Alarm Severity")
  INTEGER_S(OPHIALM,TM,"OP High Alarm On Delay Time")
  INTEGER_S(OPHIALM,TMO,"OP High Alarm Off Delay Time")
  DOUBLE_S(OPHIALM,TP,"OP High Alarm Trippoint")
STRUCT_END(OPHIALM)*/
Real(OPHILM,"OP High Limit in %",0)
Struct_REBEIIIR(OPLOALM,DB,ALMDBU,DBU,FL,ALPRIOR,PR,SV,TM,TMO,TP)
/*STRUCT(OPLOALM)
  FLAG_S(OPLOALM,ALL,"")
  DOUBLE_S(OPLOALM,DB,"OP Low Alarm Deadband")
  ENUM_S(OPLOALM,DBU,"OP Low Alarm Db Units",PERCENT,EU,Def=)
  FLAG_S(OPLOALM,FL,"OP Low Alarm Flag")
  ENUM_S(OPLOALM,PR,"OP Low Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(OPLOALM,SV,"OP Low Alarm Severity")
  INTEGER_S(OPLOALM,TM,"OP Low Alarm On Delay Time")
  INTEGER_S(OPLOALM,TMO,"OP Low Alarm Off Delay Time")
  DOUBLE_S(OPLOALM,TP,"OP Low Alarm Trippoint")
STRUCT_END(OPLOALM)*/
Real(OPLOLM,"OP Low Limit in %",0)
Real(OPMINCHG,"OP Minimum Change",0)
Real(OPROCLM,"OP Rate-of-Change Limit",0)
/*STRUCT(OPSECDATA)
  ENUM_S(OPSECDATA,ARWSTS,"OP SECDATA.ARWSTS",NORMAL,HI,LO,HILO,Def=)
  DOUBLE_S(OPSECDATA,EUHI,"OP SECDATA.EUHI")
  DOUBLE_S(OPSECDATA,EULO,"OP SECDATA.EULO")
  FLAG_S(OPSECDATA,INITREQ,"OP SECDATA.INITREQ")
  DOUBLE_S(OPSECDATA,INITVAL,"OP SECDATA.INITVAL")
  INTEGER_S(OPSECDATA,ONESHOT,"OP SECDATA.ONESHOT")
  DOUBLE_S(OPSECDATA,ORFBVAL,"OP SECDATA.ORFBVAL")
  FLAG_S(OPSECDATA,OROFFSET,"OP SECDATA.OROFFSET")
STRUCT_END(OPSECDATA)*/
Real(OPTOL,"OP Tolerance limit in %",0)
Enumeration(OPTYPE,"OPREQ Option",Null,SET,NOTSTORED,DEFAULT,Def=Null)
//Integer(ORDERINCM,"Execution Order in CM",10)
Enumeration(OUTIND,"Output Indication",Direct,Reverse,DirectDispInd,ReverseDispInd,Def=Direct)
Enumeration(OUTTYPE,"Output Type",DIGITAL,ANALOG,Def=DIGITAL)
/*STRUCT(PRIMDATA)
  ENUM_SA(PRIMDATA,ARWSTS,8,"Windup status for Primary",8,NORMAL,HI,LO,HILO,Def=)
  DOUBLE_SA(PRIMDATA,EUHI,8,"EUHI for Primary")
  DOUBLE_SA(PRIMDATA,EULO,8,"EULO for Primary")
  FLAG_SA(PRIMDATA,HISELECT,8,"Override type for Primary")
  FLAG_SA(PRIMDATA,INITIALIZABLE,8,"Primary Initializable type")
  FLAG_SA(PRIMDATA,INITSTS,8,"INIT status for Primary")
  DOUBLE_SA(PRIMDATA,INITVAL,8,"INITVAL for Primary")
  FLAG_SA(PRIMDATA,LOCALMAN,8,"LOCALMAN for Primary")
  INTEGER_SA(PRIMDATA,ONESHOT,8,"One shot sequence for Primary")
  ENUM_SA(PRIMDATA,ORFBSTS,8,"Override Status for Primary",8,NOTCON,SEL,NOTSEL,Def=)
  DOUBLE_SA(PRIMDATA,ORFBVAL,8,"OVerride feedvack value for Primary")
  FLAG_SA(PRIMDATA,OROFFSET,8,"OROFFSET for Primary")
  FLAG_SA(PRIMDATA,PROPOVRD,8,"Override propagation enable")
STRUCT_END(PRIMDATA)*/
//String_K(QUALSTATE,"Qualification State",100*4)
Enumeration(RBOPTION,"Ratio Bias Option",FIXRATBI,AUTORAT,AUTOBI,Def=FIXRATBI)
Boolean(REDTAG,"Red Tag",false)
Enumeration(RESTARTOPT,"Restart State Option",NONE,LASTREQ,Def=NONE)
Real(RTHILM,"RT High Limit in EUs",0)
Real(RTLOLM,"RT Low  Limit in EUs",0)
Real(SAFEOP,"Safe OP Value in %",NaN)
//Integer(SECBLOCKID,"Secondary BlockId Info")
/*STRUCT(SECDATAIN)
  ENUM_S(SECDATAIN,ARWSTS,"Windup status",NORMAL,HI,LO,HILO,Def=)
  DOUBLE_S(SECDATAIN,EUHI,"Euhi")
  DOUBLE_S(SECDATAIN,EULO,"Eulo")
  FLAG_S(SECDATAIN,HISELECT,"Hiselect")
  FLAG_S(SECDATAIN,INITSTS,"INIT status")
  DOUBLE_S(SECDATAIN,INITVAL,"Initval")
  FLAG_S(SECDATAIN,LOCALMAN,"Localman")
  INTEGER_S(SECDATAIN,ONESHOT,"oneshot sequence")
  ENUM_S(SECDATAIN,ORFBSTS,"Override status",NOTCON,SEL,NOTSEL,Def=)
  DOUBLE_S(SECDATAIN,ORFBVAL,"Orfbval")
  FLAG_S(SECDATAIN,OROFFSET,"Override offset")
  FLAG_S(SECDATAIN,PROPOVRD,"Propovrd")
STRUCT_END(SECDATAIN)*/
Enumeration_A(SECINITOPT,"Secondary Init Option",8,DISABLE,ENABLE,Def=DISABLE)
Struct_BBEI(SIALM,FL,OPT,ALPRIOR,PR,SV)
/*STRUCT(SIALM)
  FLAG_S(SIALM,ALL,"")
  FLAG_S(SIALM,FL,"SI Alarm Flag")
  ENUM_S(SIALM,OPT,"SI Alarm Option",NO,YES,Def=)
  ENUM_S(SIALM,PR,"SI Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(SIALM,SV,"SI Alarm Severity")
STRUCT_END(SIALM)*/
Enumeration(SIOPT,"Safety Interlock Option",NO_SHED,SHEDHOLD,SHEDLOW,SHEDHIGH,SHEDSAFE,Def=NO_SHED)
Enumeration(STARTOPT,"Starting State Option",None,Man,Auto,Cas,FixedOp,HoldPv,FixedSp,RampedSp,Def=None)
Real(STARTRATE,"Starting State SP Rate",NaN)
Real(STARTVAL,"Starting State Value",NaN)
Enumeration(STOPOPT,"Stop State Option",None,Man,Auto,Cas,FixedOp,HoldPv,FixedSp,RampedSp,Def=None)
Real(STOPRATE,"Stop State SP Rate",NaN)
Real(STOPVAL,"Stop State Value",NaN)
Enumeration(TMOUTMODE,"Timeout Mode",MAN,AUTO,CAS,BCAS,NONE,NORMAL,Def=NONE)
Integer(TMOUTTIME,"Timeout Time",0)
/*STRUCT(UNCMDCHGALM)
  FLAG_S(UNCMDCHGALM,ALL,"")
  FLAG_S(UNCMDCHGALM,FL,"Uncmd Chg Alm Flag")
  ENUM_S(UNCMDCHGALM,OPT,"Uncmd Chg Alm Option",DISABLE,ENABLE,Def=)
  ENUM_S(UNCMDCHGALM,PR,"Uncmd Chg Alm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(UNCMDCHGALM,SV,"Uncmd Chg Alm Severity")
STRUCT_END(UNCMDCHGALM)*/
//Integer(X_BLOCKMEM,"Currently used memory (bytes)")
//Enumeration(X_NOTIF_ID,"Alarm condition strings",DO NOT USE,BADCTL,OPHIGH,OPLOW,REGSI,DEVHI,DEVLOW,ADVDEV,UNCMDCHG,PREDPVHI,PREDPVLO,PIDPLBADPV,Def=)
Real(XEUHI,"X1 High Range in EUs",NaN)
Real(XEULO,"X1 Low Range in EUs",NaN)
