Boolean(I1,"Interlock 1",false)
Boolean(I1STS,"Interlock 1 Status",false)
Boolean(I2,"Interlock 2",false)
Boolean(I2STS,"Interlock 2 Status",false)
Boolean(I3,"Interlock 3",false)
Boolean(I3STS,"Interlock 3 Status",false)
Boolean(I4,"Interlock 4",false)
Boolean(I4STS,"Interlock 4 Status",false)
Boolean(I5,"Interlock 5",false)
Boolean(I5STS,"Interlock 5 Status",false)
Boolean(I6,"Interlock 6",false)
Boolean(I6STS,"Interlock 6 Status",false)
Boolean(I7,"Interlock 7",false)
Boolean(I7STS,"Interlock 7 Status",false)
Boolean(I8,"Interlock 8",false)
Boolean(I8STS,"Interlock 8 Status",false)
Integer(LASTTRIPREASON,"Last Trip Reason",0)
Enumeration(MODE,"Mode",None,Man,Cas,Normal,Def=None)
Enumeration(MODEATTR,"Mode Attribute",None,Operator,Program,Normal,Def=None)
Real(OFFPULSE,"Off Pulse Timer",NaN)
Real(ONPULSE,"On Pulse Timer",NaN)
Real(OP,"PWM Percent Output",0)
Boolean(READY,"Ready",false)
Boolean(SO,"Status Output",false)
