// Это для объектов на технологических схемах      (Иконки)
DATATYPE( Unknown          ,  -1, "Неизвестные"         ,  5 )
DATATYPE( Alien            ,   0, "Чужие"               ,  5 )
DATATYPE( System           ,   1, "Система"             ,  5 )
DATATYPE( Value            ,   2, "Переменные"          ,  5 )
DATATYPE( ExternalCondition,   3, "Внешние условия"     ,  5 )
DATATYPE( Sensor           ,   5, "Датчики"             ,  7 )
DATATYPE( ObjRef           ,   6, "Объекты"             ,  5 )
DATATYPE( SensPlace        ,   7, "Автодатчики"         ,  7 )
DATATYPE( Klapan           ,  12, "Клапана"             ,  7 )
DATATYPE( Zadv             ,  13, "Задвижки"            ,  6 )
DATATYPE( Reg              ,  14, "Регуляторы"          ,  7 )
DATATYPE( Pump             ,  15, "Насосы"              ,  8 )
DATATYPE( KVO              ,  16, "АВО"                 ,  9 )
DATATYPE( Goto             ,  17, "Пустые переходы"     ,  6 )
DATATYPE( HeatChange       ,  18, "Теплообменники"      ,  5 )
DATATYPE( Forsunka         ,  22, "Форсунки"            ,  5 )
DATATYPE( Msg              ,  37, "Сообщение"           ,  5 )
DATATYPE( Edg              ,  38, "Электродегидратор"   ,  5 )
DATATYPE( ElectroZadv      ,  40, "Электрозадвижки"     ,  6 )
DATATYPE( SysEvent         ,  42, "Событие"             ,  5 )
DATATYPE( Sensor_45        ,  45, "Датчик_Уровень"      ,  5 )
DATATYPE( Sensor_46        ,  46, "Датчик_с_дренажем"   ,  5 )
DATATYPE( Sensor_47        ,  47, "Датчик_с_диафрагмой" ,  5 )
DATATYPE( HS               ,  55, "Устройства"          ,  6 )
DATATYPE( Level            ,  59, "Уровни"              ,  5 )
DATATYPE( ShSens           ,  60, "Датчики ТС"          ,  5 )
DATATYPE( ObjPntRef        ,  66, "Объекты"             ,  5 )
DATATYPE( ShZaslonka       ,  67, "Заглушки"            ,  6 )
DATATYPE( Turbina          ,  68, "Турбины"             ,  5 )
DATATYPE( ShLocReg         ,  78, "Регуляторы"          , 10 )
DATATYPE( Ventil           ,  79, "Дренажные вентили"   ,  6 )
DATATYPE( 3xZadv           ,  80, "Переключающие устройства" ,  6 )
DATATYPE( ShBallZadv       ,  83, "Шаровые краны"       ,  6 )
DATATYPE( ShZadvVentil     ,  84, "Задвижка_вентиль"    ,  6 )
DATATYPE( GasAnalyz        ,  89, "Анализаторы"         ,  5 )
DATATYPE( ZadvZaglushka    ,  90, "Задвижка_с_заглушкой",  7 )
DATATYPE( Dialog           , 113, "Диалоги"             ,  7 )
DATATYPE( Library          , 119, "Пульты"              ,  7 )
DATATYPE( PHS              , 120, "ППК"                 ,  7 ) 
DATATYPE( Layer            , 122, "Прокладки"           ,  7 )
DATATYPE( Model_Pnt        , 123, "Точки связей"        ,  7 )
DATATYPE( ElectroNagrev    , 124, "Электронагреватели"  ,  7 )
DATATYPE( ModelData        , 128, "Модель"              ,  6 )
DATATYPE( Reductor         , 131, "Редуктор"            ,  6 )
DATATYPE( Custom           , 132, "Сообщения оператора" ,  6 )
