//ID=120
String_K(NAME,"Имя",32*4)
String_K(ASSOCASSET,"Associated Asset",132*4)
//Integer_A(ASSOCBLOCK,"Associated Block",1000)
String_A(AUXDESC,"Auxiliary Descriptor",40 * 4,36)
//Real(AVGPDTIME,"Avg. Control Data Process Time",0)
//String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
String_K(BLOCKTYPNAME,"Block Type Name",101*4)
//Boolean(CALIB1,"Calibration Enabled Flag",false)
//Boolean(CALIB2,"Calibration Enabled Flag",false)
//Enumeration(CALIBFTA1STS,"FTA 1 Calibration Status",Disabled,Enabled,Not_Permitted,Def=)
//Enumeration(CALIBFTA2STS,"FTA 2 Calibration Status",Disabled,Enabled,Not_Permitted,Def=)
//Enumeration(CALIBRJSTS,"Reference Junction Calib Sts",Disabled,Enabled,Not_Permitted,Def=)
//Enumeration(CALIBSTS,"Calibration Status",Disabled,Enabled,Not_Permitted,Def=)
//String_K(CALIBTEXT,"Calibration Help Text",100*4)
//Integer(CBBLOCKPROP,"Block Property")
//Boolean(CHKPTSVSTS,"Checkpoint save status",false)
String_A(CHNLNAME,"Channel Name",64 * 4,16)
//Enumeration(CPRESTORESCOPE,"Checkpoint Restore Scope",ExposedNotChecked,ExposedChecked,UnExposedChecked,UnExposedNotChecked,Def=)
/*Boolean(CTRLCONFIRM,"Control Confirmation",false)
Boolean(DBVALID,"Database Valid",false)
Boolean(DBVALIDA,"Database Valid DPA Part A",false)
Boolean(DBVALIDB,"Database Valid DPA Part B",false)
Boolean(DBVALIDCMD,"Validate IOP Database",false)*/
String_K(DESC,"Description",132*4)
String_K(EUDESC,"Engineering Units",24*4)
/*STRUCT(FFBLKLST)
  INTEGER_SA(FFBLKLST,INSTID,16,"Block Instance ID")
  STRING_SA(FFBLKLST,TMPLTID,16,64,"Block Template ID")
  INTEGER_SA(FFBLKLST,VFDINDX,16,"VFD Array Index associated with the Block")
STRUCT_END(FFBLKLST)
Boolean(FTAPRESA,"FTA Present",false)
Boolean(FTAPRESB,"FTA Present",false)
Boolean(FTAREVERSEDA,"FTA Connections Reversed",false)
Boolean(FTAREVERSEDB,"FTA Connections Reversed",false)
Boolean(FWINVALIDA,"IOP Firmware Not Compatible",false)
Boolean(FWINVALIDB,"IOP Firmware Not Compatible",false)
STRUCT(GROUP)
  INTEGER_SA(GROUP,NUMBER,25,"Group Number")
  INTEGER_S(GROUP,NUMPARAMS,"Number of Group parameters")
STRUCT_END(GROUP)*/
Real(HCUAVAIL,"HART Comm. Units - Available",0)
//Integer_A(HDEVID,"Id (Serial Number)",16)
//Enumeration_A(HDEVMFG,"Manufacturer",16,UNKNOWN 000,Acromag,Allen Bradley,Ametek,Analog Devices,Elsag Bailey,Beckman,Bell Microsensor,Bourns,Bristol Babcock,Brooks Instrument,Chessell,Combustion Engineering,Daniel Endustries,Delta,Dieterich Standard,Dohrmann,Endress && Hauser,Elsag Bailey (2),Fisher Controls,Foxboro,Fuji,ABB Automation,Honeywell,ITT Barton,Kay Ray/Sensall,ABB Automation (2),Leeds && Northrup,Leslie,M-System Co.,Measurex,Micro Motion,Moore Industries,Moore Products,Ohkura Electric,Paine,Rochester Instrument Systems,Ronan,Rosemount,Peek Measurement,Schlumberger,Sensall,Siemens,Weed,Toshiba,Transmation,Rosemount Analytic,Metso Automation,Flowserve,Varec,Viatran,Delta/Weed,Westinghouse,Xomox,Yamatake,Yokogawa,Nuovo Pignone,Promac,Exac Corporation,Meggitt Mobrey,Arcom Control System,Princo,Smar,Foxboro Eckardt,Measurement Technology,Applied System Technologies,Samson,Sparling Instruments,Fireye,Krohne,Betz,Druck,SOR,Elcon Instruments,EMCO,Termiflex Corporation,VAF instruments,Westlock Controls,Drexelbrook,Saab Tank Control,K-TEK,Flowdata,Draeger,Raytek,Siemens Milltronics PI,BTG,Magnetrol,Metso Automation (2),Milltronics,HELIOS,Anderson Instrument Company,INOR,ROBERTSHAW,PEPPERL+FUCHS,ACCUTECH,Flow Measurement,KAMSTRUP,Knick,VEGA,MTS Systems Corp.,Oval,Masoneilan-Dresser,BESTA,Ohmart,Harold Beck and Sons,rittmeyer instrumentation,Rossel Messtechnik,WIKA,Bopp && Reuther Heinrichs,PR Electronics,Jordan Controls,Valcom s.r.l.,US ELECTRIC MOTORS,Apparatebau Hundsbach,Dynisco,Spriano,Direct Measurement,Klay Instruments,Action Instruments,MMG Automatiky DTR,Buerkert Fluid Control Systems,AALIANT Process Mgt,PONDUS INSTRUMENTS,ZAP S.A. Ostrow Wielkopolski,GLI,Fisher-Rosemount Performance Technologies,Paper Machine Components,LABOM,Danfoss,Turbo,TOKYO KEISO,SMC,Status Instruments,Huakong,Duon System,Vortek Instruments, LLC,AG Crosby,Action Instruments (2),Keystone Controls,Thermo Electric Co.,Ise-Magtech,Rueger,Mettler Toledo,Det-Tronics,TN Technologies,DeZURIK,Phase Dynamics,WELLTECH SHANGHAI,ENRAF,4tech ASA,Brandt Instruments,Nivelco,Camille Bauer,Metran,Milton Roy Co.,PMV,Turck,Panametrics,Stahl,Analytical Technology, Inc,Fieldbus International,BERTHOLD,InterCorr,China BRICONTE Co Ltd,Electron Machine,Sierra Instruments,Fluid Components Intl,Solid AT,Meriam Instrument,Invensys,S-Products,Tyco Valves and Controls,Micro Matic INstrument A/S,J-Tec Associates,TRACERCO,AGAR,Phoenix COntact,Andean Instruments,Amer.Level Instr,Hawk,YTC,Pyromation Inc.,Satron Instruments,BIFFI,SAIC,BD Sensors,Andean Instruments,Kemotron,APLISENS,Badger Meter,HIMA,GP.50,Kongsberg Maritime,ASA S.p.A,Hengesbach,Lanlian Instruments,Spectrum Controls,Kajaani Process Measurements,FAFNIR,SICK-MAIHAK,JSP Nova Paka,MEASACON,Spirax Sarco Italy,L and J TECHNOLOGY,Tecfluid S.A,Sailsors Instruments,Roost,KOSO,MJK,GE Energy,BW Technologies,HEINRICHS,SIC,HACH LANGE,Exalon Instruments,FAURE HERMAN,STI S.r.1,Manometr-Kharkiv,Dalian-Instruments,Spectrex,SIPAI Instruments,Advanced Flow,Rexa.Koso America,General Monitors,Manufacturer Expansion,UNKNOWN 225,UNKNOWN 226,UNKNOWN 227,UNKNOWN 228,UNKNOWN 229,UNKNOWN 230,UNKNOWN 231,UNKNOWN 232,UNKNOWN 233,UNKNOWN 234,UNKNOWN 235,UNKNOWN 236,UNKNOWN 237,UNKNOWN 238,UNKNOWN 239,UNKNOWN 240,UNKNOWN 241,UNKNOWN 242,UNKNOWN 243,UNKNOWN 244,UNKNOWN 245,UNKNOWN 246,UNKNOWN 247,UNKNOWN 248,UNKNOWN 249,Generic HART Device,None     251,UNKNOWN  252,Special  253,UNKNOWN  254,UNKNOWN  255, ,HART Communication Foundation ExSaf,SEOJIN INSTECH,TASI FLOW,Daehan Control,APM,ORANGE INST.UK,BARTEC,Detcon,MSA,METROVAL,Etalon Rus,JOGLER,KSB,Richter CT,NET SAFETY,SECanada,SUPCON,DKK -TOA,Dwyer Instruments,Fine Tek,Top Worx Inc.,HOFFER FLOW CNTRLS,DUST NETWORKS,Forbes Marshall,All Measures, Ltd.,MACTek,CSI,TC Fluid Control,Rohrback Cosasco,AirSprite,Microcyber Inc.,TIG,ifm prover Gmbh,FLEXIM,TOKIMEC.INC,SBEM,SkoFlo Industries, Inc/,StoneL Corporation,EUREKA FLOW,BEKA associates,CAPSTAR AUTOMATION,Pulsar,Elemer,Soft Tech Group,Def=)
//Enumeration_A(HDEVTYPENAME,"Type (Name)",16,Any Device,ST3000,STT25H,Logix 1200,Any Device,Def=)
Boolean_A(HENABLE,"HART Enabled",16,true)
//Enumeration(HIOPLHFSTA,"HART Last Hard Fail Status",---,Watchdog Timeout,Internal RAM Diagnostic Error,External RAM Diagnostic Error,Stack OverflowError,RAM Address Error,Startup Diagnostic Error,Invalid Execution Error 11,Invalid Execution Error 12,Invalid Execution Error 13,Invalid Execution Error 14,Invalid Execution Error 15,Invalid Execution Error 16,Invalid Execution Error 17,Def=)
//Enumeration(HIOPLHFSTB,"HART Last Hard Fail Status",---,Watchdog Timeout,Internal RAM Diagnostic Error,External RAM Diagnostic Error,Stack OverflowError,RAM Address Error,Startup Diagnostic Error,Invalid Execution Error 11,Invalid Execution Error 12,Invalid Execution Error 13,Invalid Execution Error 14,Invalid Execution Error 15,Invalid Execution Error 16,Invalid Execution Error 17,Def=)
/*STRUCT(HIST)
  FLAG_SA(HIST,EXC,25,"Exception Collection Type")
  INTEGER_SA(HIST,EXCCOLLRATE,25,"Collection Rate for Exception History Collection Type")
  INTEGER_SA(HIST,EXCOFFSET,25,"Collection Rate Offset for Exception History Collection Type")
  FLAG_SA(HIST,EXTD,25,"Extended Collection Type")
  FLAG_SA(HIST,FAST,25,"Fast Collection Type")
  INTEGER_SA(HIST,FASTCOLLRATE,25,"Collection Rate for Fast History Collection Type")
  STRING_SA(HIST,GATESTRING,25,255,"Gating Parameter String")
  STRING_SA(HIST,GATEVALUE,25,255,"Gating Parameter value")
  INTEGER_S(HIST,NUMPARAMS,"Number of History parameters")
  FLAG_SA(HIST,STD,25,"Standard Collection Type")
  INTEGER_SA(HIST,STDCOLLRATE,25,"Collection Rate for Standard History Collection Type")
  INTEGER_SA(HIST,STDOFFSET,25,"Collection Rate Offset for Standard History Collection Type")
  STRING_SA(HIST,TYPE,25,255,"History Type")
STRUCT_END(HIST)*/
//Enumeration_A(HSCANCFG,"Scan HART Variables",16,1S Device,1S Dynamic,2S Device,2S Dynamic,2S Dev & Dyn,4S Device,4S Dynamic,4S Dev & Dyn,8S Device,8S Dynamic,8S Dev & Dyn,16S Device,16S Dynamic,16S Dev & Dyn,Status Only,Def=)
//Boolean_A(HSCANOVR,"Scan Overrun",16)
String_A(HTAG,"Tag",8 * 4,16)
//Enumeration(ICONSTATE,"Icon States",IDLE,PriIdleNoSec,PriIdleNotSync,PriIdleSync,RUN,PriRunNoSec,PriRunNotSync,PriRunSync,FAILED,PriCommErrNoSec,PriCommErrNoSync,NODB,PriNoDbNoSec,PriNoDbNotSync,PriNoDbSync,Reserve1,Def=)
//Integer(IOLINK,"Associated IOLINK")
//Enumeration(IOLINKCOLOR,"I/O Link Cable Color",Unknown,Gray,Violet,Def=)
/*String_K(IOMFWREVA,"Firmware Revision",12*4)
String_K(IOMFWREVB,"Firmware Revision",12*4)
String_K(IOMHWREVA,"Hardware Revision",12*4)
String_K(IOMHWREVB,"Hardware Revision",12*4)
Enumeration(IOMLHFSTA,"Last Hard Fail Status",Unknown,PowerDown,InvPrgExec,EpromErr,RamCntErr,RamAdrErr,DpaError,DsaError,RxBufOvFl,IolJabber,SramFail,BadPgJmp,AdConvInmcp,AdOutOvfl,AdOutUndef,AdCalibErr,BadLcLtc,Dmt_Tmot,MltOutFail,DataBusDiagFl,BadDaRange,MstrTmot,---,CounterCircuitFail,SoeCounterFail,OutputControlHwFail,OutputMuxFail,AsCrcFail,PsCodeMismatch,ParityHwFail,TaskStackStartFail,StackOverrun,WatchDogTimeout,IllegalWrite,ParityError,UserReset,ZeroRefFail,RefInpChkFail,FPGARdbkFail,AppRAMDiagFail,AppCapSemPhFail,AppCpuDiagFail,AppIllegalIsr,DataBusErr,AppIOTAErr,AppBrdPwrErr,ExtRAMContErr,KrnlPwrFail,CpldVerFail,Parity0Fail,Parity1Fail,DataBusFail,DACRBFail,AppWatchDogTimeout,AoDacFail,Def=)
Enumeration(IOMLHFSTB,"Last Hard Fail Status",Unknown,PowerDown,InvPrgExec,EpromErr,RamCntErr,RamAdrErr,DpaError,DsaError,RxBufOvFl,IolJabber,SramFail,BadPgJmp,AdConvInmcp,AdOutOvfl,AdOutUndef,AdCalibErr,BadLcLtc,Dmt_Tmot,MltOutFail,DataBusDiagFl,BadDaRange,MstrTmot,---,CounterCircuitFail,SoeCounterFail,OutputControlHwFail,OutputMuxFail,AsCrcFail,PsCodeMismatch,ParityHwFail,TaskStackStartFail,StackOverrun,WatchDogTimeout,IllegalWrite,ParityError,UserReset,ZeroRefFail,RefInpChkFail,FPGARdbkFail,AppRAMDiagFail,AppCapSemPhFail,AppCpuDiagFail,AppIllegalIsr,DataBusErr,AppIOTAErr,AppBrdPwrErr,ExtRAMContErr,KrnlPwrFail,CpldVerFail,Parity0Fail,Parity1Fail,DataBusFail,DACRBFail,AppWatchDogTimeout,AoDacFail,Def=)
Enumeration(IOMOPERA,"Operation",Primary,Secondary,---,Def=)
Enumeration(IOMOPERB,"Operation",Primary,Secondary,---,Def=)
String_K(IOMPLREVA,"Programmable Logic Revision",12*4)
String_K(IOMPLREVB,"Programmable Logic Revision",12*4)
Enumeration(IOMSTATE,"Execution State",Idle,Run,Def=)
Enumeration(IOMSTSA,"Status",Power_On,Idle,OK,NoResponse,IdleSF,SoftFail,CommError,ConfgMis,Not_Config,---,Alive,Failed,Def=)
Enumeration(IOMSTSB,"Status",Power_On,Idle,OK,NoResponse,IdleSF,SoftFail,CommError,ConfgMis,Not_Config,---,Alive,Failed,Def=)*/
/*String_K(IOMTYPE,"Module Type",64*4)
String_K(IOPDESCA,"IOP Descriptor",12*4)
String_K(IOPDESCB,"IOP Descriptor",12*4)
String_K(IOPLOCATION,"IOP Location",64*4)
Enumeration(IOPTYPE,"IOP Type",---,LLAI,HLAI,DI,DO16,AO8,LLMUX,STIMV,DISOE,AO16,DO32,RHMUX,HLAIHART,DI24V,AO16HART,AI_HART,AI_LLMUX,AO_HART,DI_HV,DI_24,DO_24B,DI_SOE,AI_HL,AO,SVP,SP,PI,UIO,Def=)
Boolean(IOREDOPT,"This IOP is redundant",false)
Real_A(LRL,"Device Extended Low Range",16)
Real_A(LRV,"Device Low Range (4mA)",16)
Enumeration(MODLTYPEA,"Module Type DPA Part A",---,LLAI,HLAI,DI,DO16,AO8,LLMUX,STIMV,DISOE,AO16,DO32,RHMUX,HLAIHART,DI24V,AO16HART,AI_HART,AI_LLMUX,AO_HART,DI_HV,DI_24,DO_24B,DI_SOE,AI_HL,AO,SVP,SP,PI,UIO,Def=)
Enumeration(MODLTYPEB,"Module Type DPA Part B",---,LLAI,HLAI,DI,DO16,AO8,LLMUX,STIMV,DISOE,AO16,DO32,RHMUX,HLAIHART,DI24V,AO16HART,AI_HART,AI_LLMUX,AO_HART,DI_HV,DI_24,DO_24B,DI_SOE,AI_HL,AO,SVP,SP,PI,UIO,Def=)
Enumeration(MONACTCMD,"Enum for activate",Idle,Run,Def=)
String_K(MONCMDPARAM,"Parameter stores activation",64*4)
Enumeration(MONINACTCMD,"Enum for inactivate",Idle,Run,Def=)
Enumeration(MONLDCMD,"Value prior to load",Idle,Run,Def=)
String_K(MONREADLDUI,"Parameter read for LoadUI",64*4)
String_K(MONREADPARAM,"Parameter to be monitored",64*4)*/
//Enumeration(MONRQDLD,"Required load state",IDLE,PriIdleNoSec,PriIdleNotSync,PriIdleSync,RUN,PriRunNoSec,PriRunNotSync,PriRunSync,FAILED,PriCommErrNoSec,PriCommErrNoSync,NODB,PriNoDbNoSec,PriNoDbNotSync,PriNoDbSync,Reserve1,Def=)
//Enumeration_A(MONSTATES,"Enum values for each state",3,IDLE,PriIdleNoSec,PriIdleNotSync,PriIdleSync,RUN,PriRunNoSec,PriRunNotSync,PriRunSync,FAILED,PriCommErrNoSec,PriCommErrNoSync,NODB,PriNoDbNoSec,PriNoDbNotSync,PriNoDbSync,Reserve,Def=)
/*Boolean(NONREDFTABA,"Non-Redundant IOP on FTA B",false)
Boolean(NONREDFTABB,"Non-Redundant IOP on FTA B",false)
Boolean(NOTREDCNFGA,"IOP Not Redundantly Configurable",false)
Boolean(NOTREDCNFGB,"IOP Not Redundantly Configurable",false)
Boolean(NOTSAMEFTAA,"Redundant IOPs not on same FTA",false)
Boolean(NOTSAMEFTAB,"Redundant IOPs not on same FTA",false)
Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Enumeration(NUMSIGS,"Electronic Signature Type",NONE,SINGLE,DOUBLE,Def=)
Integer(ORDERINCM,"Execution Order in CM")
String_K(PARENTASSET,"Parent Asset:",132*4)
String_K(PRIMARYSIG,"Primary Signature Meaning",24*4)
Boolean(PRIORITYIOM,"Priority IOM",false)
Enumeration_A(PTEXECST,"Point Execution State",16,INACTIVE,ACTIVE,Def=)
Integer(READCOUNT,"Scanned Count")
Integer(READPHASE,"Scan Phase")
Integer(REASONSET,"Reason Set Number")
Enumeration(REDDATAA,"Redundancy Status",---,NotSyncd,DumpFailed,FreezeNotAccepted,SyncFailed,IolTimeOut,Syncd,DumpComplete,FreezePermitted,FreezeAccepted,FoInProgess,FoComplete,SwapInProgress,SwapComplete,Frozen,DumpSeqBegin,DumpSeq_02,DumpSeq_03,DumpSeq_04,DumpSeq_05,DumpSeq_06,DumpSeq_07,DumpSeq_08,DumpSeq_09,DumpSeq_10,DumpSeq_11,DumpSeq_12,DumpSeq_13,DumpSeq_14,DumpSeq_15,DumpSeq_16,DumpSeq_17,DumpSeq_18,DumpSeq_19,DumpSeq_20,DumpSeqMax,Def=)
Enumeration(REDDATAB,"Redundancy Status",---,NotSyncd,DumpFailed,FreezeNotAccepted,SyncFailed,IolTimeOut,Syncd,DumpComplete,FreezePermitted,FreezeAccepted,FoInProgess,FoComplete,SwapInProgress,SwapComplete,Frozen,DumpSeqBegin,DumpSeq_02,DumpSeq_03,DumpSeq_04,DumpSeq_05,DumpSeq_06,DumpSeq_07,DumpSeq_08,DumpSeq_09,DumpSeq_10,DumpSeq_11,DumpSeq_12,DumpSeq_13,DumpSeq_14,DumpSeq_15,DumpSeq_16,DumpSeq_17,DumpSeq_18,DumpSeq_19,DumpSeq_20,DumpSeqMax,Def=)
Boolean(RESETERRORSCMD,"Reset I/O Link Errors",false)*/
/*String_K(SCANAREA,"SCAN Area",40*4)
String_K(SCANASSOCDSP,"SCAN Associated Display",255*4)
Integer(SCANCTRLLVL,"SCAN Control Level")
String_K(SCANEUHI,"SCAN EUHI Parameter",255*4)
String_K(SCANEULO,"SCAN EULO Parameter",255*4)
String_K(SCANGRPDTL,"SCAN Group Detail Page",255*4)
String_K(SCANPNTDTL,"SCAN Point Detail Page",255*4)
Enumeration(SCANRATE,"I/O Link Scan Rate",100_ms,200_ms,250_ms,500_ms,1S,2S,Def=)
String_K(SECONDARYSIG,"Secondary Signature Meaning",24*4)
Enumeration(SECSIGSECLVL,"Sec Signer Security Level",VIEWONLY,ACKONLY,OPER,SUPV,ENGR,MNGR,Def=)
Boolean(SELECTCABLEACMD,"Select I/O Link Cable A",false)
Boolean(SELECTCABLEBCMD,"Select I/O Link Cable B",false)
Enumeration(SFTEXT,"Soft Failure Text",Channel_00,Channel_01,Channel_02,Channel_03,Channel_04,Channel_05,Channel_06,Channel_07,Channel_08,Channel_09,Channel_10,Channel_11,Channel_12,Channel_13,Channel_14,Channel_15,Channel_16,Channel_17,Channel_18,Channel_19,Channel_20,Channel_21,Channel_22,Channel_23,Channel_24,Channel_25,Channel_26,Channel_27,Channel_28,Channel_29,Channel_30,Channel_31,Channel_32,Channel_33,Channel_34,Channel_35,Channel_36,Channel_37,Channel_38,Channel_39,Channel_40,Channel_41,Channel_42,Channel_43,Channel_44,Channel_45,Channel_46,Channel_47,Channel_48,Channel_49,Channel_50,Channel_51,Channel_52,Channel_53,Channel_54,Channel_55,Channel_56,Channel_57,Channel_58,Channel_59,Channel_60,Channel_61,Channel_62,Channel_63,Channel_64,Def=)
Enumeration(SFTEXTA,"Soft Failure Text Partner A",Channel_00_A,Channel_01_A,Channel_02_A,Channel_03_A,Channel_04_A,Channel_05_A,Channel_06_A,Channel_07_A,Channel_08_A,Channel_09_A,Channel_10_A,Channel_11_A,Channel_12_A,Channel_13_A,Channel_14_A,Channel_15_A,Channel_16_A,Channel_17_A,Channel_18_A,Channel_19_A,Channel_20_A,Channel_21_A,Channel_22_A,Channel_23_A,Channel_24_A,Channel_25_A,Channel_26_A,Channel_27_A,Channel_28_A,Channel_29_A,Channel_30_A,Channel_31_A,Channel_32_A,Channel_33_A,Channel_34_A,Channel_35_A,Channel_36_A,Channel_37_A,Channel_38_A,Channel_39_A,Channel_40_A,Channel_41_A,Channel_42_A,Channel_43_A,Channel_44_A,Channel_45_A,Channel_46_A,Channel_47_A,Channel_48_A,Channel_49_A,Channel_50_A,Channel_51_A,Channel_52_A,Channel_53_A,Channel_54_A,Channel_55_A,Channel_56_A,Channel_57_A,Channel_58_A,Channel_59_A,Channel_60_A,Channel_61_A,Channel_62_A,Channel_63_A,Channel_64_A,Def=)
Enumeration(SFTEXTB,"Soft Failure Text Partner B",Channel_00_B,Channel_01_B,Channel_02_B,Channel_03_B,Channel_04_B,Channel_05_B,Channel_06_B,Channel_07_B,Channel_08_B,Channel_09_B,Channel_10_B,Channel_11_B,Channel_12_B,Channel_13_B,Channel_14_B,Channel_15_B,Channel_16_B,Channel_17_B,Channel_18_B,Channel_19_B,Channel_20_B,Channel_21_B,Channel_22_B,Channel_23_B,Channel_24_B,Channel_25_B,Channel_26_B,Channel_27_B,Channel_28_B,Channel_29_B,Channel_30_B,Channel_31_B,Channel_32_B,Channel_33_B,Channel_34_B,Channel_35_B,Channel_36_B,Channel_37_B,Channel_38_B,Channel_39_B,Channel_40_B,Channel_41_B,Channel_42_B,Channel_43_B,Channel_44_B,Channel_45_B,Channel_46_B,Channel_47_B,Channel_48_B,Channel_49_B,Channel_50_B,Channel_51_B,Channel_52_B,Channel_53_B,Channel_54_B,Channel_55_B,Channel_56_B,Channel_57_B,Channel_58_B,Channel_59_B,Channel_60_B,Channel_61_B,Channel_62_B,Channel_63_B,Channel_64_B,Def=)
Enumeration(SIMSTATE,"Simulation State",NONE,SIMRUN,SIMFREEZE,SIMDISABLE,Def=)
Enumeration(STTEXT,"Soft Failure Text",IOP_00,IOP_01,IOP_02,IOP_03,IOP_04,IOP_05,IOP_06,IOP_07,IOP_08,IOP_09,IOP_10,IOP_11,IOP_12,IOP_13,IOP_14,IOP_15,IOP_16,IOP_17,IOP_18,IOP_19,IOP_20,IOP_21,IOP_22,IOP_23,IOP_24,IOP_25,IOP_26,IOP_27,IOP_28,IOP_29,IOP_30,IOP_31,IOP_32,IOP_33,IOP_34,IOP_35,IOP_36,IOP_37,IOP_38,IOP_39,IOP_40,Def=)
Enumeration(STTEXTA,"Soft Failure Text Partner A",PartnerA_00,PartnerA_01,PartnerA_02,PartnerA_03,PartnerA_04,PartnerA_05,PartnerA_06,PartnerA_07,PartnerA_08,PartnerA_09,PartnerA_10,PartnerA_11,PartnerA_12,PartnerA_13,PartnerA_14,PartnerA_15,PartnerA_16,PartnerA_17,PartnerA_18,PartnerA_19,PartnerA_20,PartnerA_21,PartnerA_22,PartnerA_23,PartnerA_24,PartnerA_25,PartnerA_26,PartnerA_27,PartnerA_28,PartnerA_29,PartnerA_30,PartnerA_31,PartnerA_32,PartnerA_33,PartnerA_34,PartnerA_35,PartnerA_36,PartnerA_37,PartnerA_38,PartnerA_39,PartnerA_40,Def=)
Enumeration(STTEXTB,"Soft Failure Text Partner B",PartnerB_00,PartnerB_01,PartnerB_02,PartnerB_03,PartnerB_04,PartnerB_05,PartnerB_06,PartnerB_07,PartnerB_08,PartnerB_09,PartnerB_10,PartnerB_11,PartnerB_12,PartnerB_13,PartnerB_14,PartnerB_15,PartnerB_16,PartnerB_17,PartnerB_18,PartnerB_19,PartnerB_20,PartnerB_21,PartnerB_22,PartnerB_23,PartnerB_24,PartnerB_25,PartnerB_26,PartnerB_27,PartnerB_28,PartnerB_29,PartnerB_30,PartnerB_31,PartnerB_32,PartnerB_33,PartnerB_34,PartnerB_35,PartnerB_36,PartnerB_37,PartnerB_38,PartnerB_39,PartnerB_40,Def=)
Boolean(SWAPPRIMARYCMD,"Swap Primary IOP",false)
STRUCT(TREND)
  INTEGER_SA(TREND,NUMBER,32,"Trend Number")
  INTEGER_S(TREND,NUMPARAMS,"Number of Trend parameters")
  ENUM_SA(TREND,POSITION,32,"Trend Position",32,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,None,Def=)
STRUCT_END(TREND)
Boolean(TYPEINVALIDA,"IOP Type Mismatch",false)
Boolean(TYPEINVALIDB,"IOP Type Mismatch",false)
Real_A(URL,"Device Extended High Range",16)
Real_A(URV,"Device High Range (20mA)",16)
Boolean(WARMSTRTA,"Warm Start Executed",false)
Boolean(WARMSTRTB,"Warm Start Executed",false)
Boolean(WITHBIASA,"With Bias DPA Part A",false)
Boolean(WITHBIASB,"With Bias DPA Part B",false)
Integer(X_BLOCKMEM,"Currently used memory (bytes)")
Enumeration(X_NOTIF_ID,"Alarm condition strings",DO NOT USE,BADCTL,OPHIGH,OPLOW,REGSI,DEVHI,DEVLOW,ADVDEV,UNCMDCHG,PREDPVHI,PREDPVLO,PIDPLBADPV,Def=)
*/