String_K(NAME,"Имя",32*4)
Struct_BEI(ABORTALM,FL,ALPRIOR,PR,SV)
/*STRUCT(ABORTALM)
  FLAG_S(ABORTALM,FL,"SCM Abort Alarm Flag")
  ENUM_S(ABORTALM,PR,"SCM Abort Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(ABORTALM,SV,"SCM Abort Alarm Severity")
STRUCT_END(ABORTALM)*/
Enumeration(ABORTLOCK,"SCM Abort Access Lock",OPERATOR,ENGINEER,VIEWONLY,OTHERFB,SUPERVISOR,Def=VIEWONLY)
Enumeration(ACQONBEHALF,"Acquire On Behalf Option",Self,Parent,Def=Self)
Enumeration(ACQRESTYPE,"Acquired Resource block Type",STEP,PHASE,UCM,SCM,RCM,Def=STEP)
Enumeration(ACTOPT,"Activity Creation option",None,Auto,User_or_App,All,Def=None)
Enumeration(ACTREMOVETYPE,"Activity Removal Method",None,Auto,User_or_App,Def=None)
Enumeration(ACTTYPE,"Type of the Activity",None,Batch,Procedure,Def=None)
String_A(AHISTDESC,"Alias History Parameter Descriptor",63 * 4,50)
/*STRUCT(ALIAS)
  ENUM_SA(ALIAS,STATUS,500,"Binding status of the alias",500,Null,OK,BINDING,Def=)
STRUCT_END(ALIAS)*/
//String_A(ALIASBLKTYP,"Block type of the alias",64*4,500)
//Integer_A(ALIASDATATYP,"Data type of the alias",500)
Boolean(ALIASOPT,"Alias Table Option",false)
//String_A(ALIASPRMTYP,"Parameter of the alias",64*4,500)
//String_A(ALIASREFSTR,"Alias reference string",64*4,500)
Boolean(ALMENBSTATE,"Alarming Enabled",false)
String_A(ARECDESC,"Alias Recipe Parameter Descriptor",23 * 4,50)
//String_K(ASSOCASSET,"Associated Asset",132*4)
//Integer_A(ASSOCBLOCK,"Associated Block",1000)
Boolean(AUTOPUBLICNAME,"Track Name to Public Name",false)
Integer(AUXOPT,"Auxiliary Option",0)
Integer(AUXUNIT,"Auxiliary Unit Number",0)
Boolean(AVAILFL,"Resource is available",false)
//String_K(BLCKCOMMENT1,"Block Comment 1",40*4)
//String_K(BLOCKTYPNAME,"Block Type Name",101*4)
Enumeration(BYPCANCELOPT,"Bypass Cancel Option",None,OnReset,OnTransEnd,Def=None)
//Integer(CBBLOCKPROP,"Block Property")
//Integer_A(CEERESADDR,"SCM Start Addr on CEE Restart",15)
//Integer_A(CEERESADDRN,"Numeric SCM Start Addr on CEE Restart",15)
/*Enumeration(CEESTARTMODE,"Mode after CEE Start",AUTO,SEMIAUTO,SINGLESTEP,MANUAL,NORMAL,LASTMODE,FOLLOWCEE,Def=AUTO)
Enumeration(CEESTARTOPT,"SCM Behavior on CEE Restart",FOLLOWCEE,ALWAYSCOLD,ALWAYSWARM,Def=FOLLOWCEE)
Boolean(CEETOPSTART,"Restart from Top on CEE Restart",false)
Boolean(CLRQUEUEOPT,"Clear Arbitration Queue on Inactivation",false)
String_K(COMPTYPEREF,"Block type info storage",32*4)
Enumeration(CONFIGCODE,"SCM Config Code",None,UnknownError,InternalErr,ILLOwnHandle,ILLHndlrHndl,NextHNotNull,ILLNNextTrns,ConnInvObjs,InvNextType,NotImplNxTyp,ILLExcConds,ILLConds,ILLOutputs,IncObjects,ILLNOutputs,ILLNConds,ILLGateLogic,IncGateLogic,NullGateUsed,OvlpGateInps,SkipGateInps,ILLInvkTObj,ILLInvkTCnfg,ILLHndlrType,ILLHndlrSel,HndlrInstMis,ILLExcCProp,IncOpProp,IncCondProp,IncInvkTProp,IncPropagtn,LostObjects,ActIgnored,EditIgnored,TooFewCond,MaxTmLtMinTm,NegativeTime,EnbHdUnavail,DisHdUnavail,EditNotPermt,IntGateError,UserNullHnd,UserEditHnd,ILLObjAsHnd,NonEditLostO,NonOptGatLog,RefusedConn,ILLMultRef,ConfHndErr,CnfHndSvrWrn,ConfHndWarn,ConfHndInfo,CnfUnknCnfSt,ResrcMissing,IllegalConvErr,ImpConvInfo,ATLoadInProg,ATLoadFailed,IntegrityErr,Spare59,Spare60,Spare61,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,PeerAlgOptConfigError,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,IllegalNullPhase,ExecOptWoScmRcm,UnsupportedFeature,TermStateOptWoScmRcm,ScmRcmWoAcqOpt,ScmRcmWoExecOpt,MissingCmdReqOutConn,MissingValueRefConn,ConnNotEstablished,EquipConnNotEstablished,RsrcConnNotEstablished,LonelyTermState,EquipmentIgnored,ForceReadReqIgnored,EquipmentNotSupported,ResourceNotSupported,Def=)
String_K(CONFIGDESC,"SCM ConfigCode Desc",39*4)
Enumeration(CONFIGSTS,"SCM Config Status",Ok,Information,Warning,SevereWarn,Fail,Error,SevereError,Def=)
Boolean(CONFLICTFL,"Unmanaged Conflicts",false)
Integer(CONTAINMEM,"Sum of used memory (bytes)")
Boolean(CONTCUTOUT,"Alarming Contact CutOut",false)
Enumeration(CONTROLLOCK,"SCM Control Access Lock",OPERATOR,ENGINEER,VIEWONLY,OTHERFB,SUPERVISOR,Def=)
Integer(CPUMAXFLOAT,"Floating Maximum CPU usage indicator")
Boolean(CTRLCONFIRM,"Control Confirmation",false)
Integer(DATABLOCK,"Data Block")
Integer_A(DELLWABLKLST,"List of deleted active loadable blocks",256)*/
String_K(DESC,"Description",132*4)
/*Enumeration(DYNPEERALLOC,"Allocate Peer resource when needed",Load,Dynamic,Def=)
String_K(EENAME,"Execution Environment name",16*4)
/*Boolean_A(ENBHANDLER,"Enable Handler Type",8)
Enumeration_A(EQMTORECMAP,"Recipe Response To Equipment State Mapping",3,None,Default,Start,Reset,Interrupt,Restart,Hold,Stop,Abort,Resume,Def=)*/
Real(ESTWEIGHT,"Estimated Weight",NaN)
String_K(EUDESC,"Engineering Units",24*4)
Integer_A(EVALTRANS,"Current EvalTrans",15,0)
Integer_A(EVALTRANSN,"Current EvalTrans Number",15,0)
/*Boolean(EVTOPT,"Overall Event Option",false)
Boolean(EVTOPTHIST,"History Parameter Event Option",false)
Boolean(EVTOPTMODEATR,"Mode Attribute Change Event Option",false)
Boolean(EVTOPTRECIPE,"Recipe Parameter Event Option",false)
Boolean(EVTOPTSCMS,"SCM Start Event Option",false)
Boolean(EVTOPTSCMTS,"SCM Terminal State Event Option",false)
Boolean(EVTOPTSTATECHG,"State Change Event Option",false)
Boolean(EVTOPTSTEPC,"Step Complete Event Option",false)
Boolean(EVTOPTSTEPS,"Step Start Event Option",false)
Enumeration(EXCMODEOPT,"Exception Mode Option",None,Auto,Def=)
Enumeration(EXECCODE,"SCM Execution Code",None,ConfigError,ExprEvalFail,StoreFailed,CommError,StoreWarning,InternalErr,CtrlReqErr,DataTypeErr,StorePending,ResourcLimit,EqmNotInProgram,EqmAcqError,FormulaRangeError,FormulaFetchNotComplete,ReportRangeError,ReportFetchNotComplete,EqmAcqRlsError,RTableFull,AcquiringResource,InvalidCommandValue,ReleasingResource,DestIsNotADevice,RemoteFetchPending,EqmNotAvailable,InstSelectChange,EmptyAliasTableCell,PendingHold,PendingStop,PendingAbort,RequesterBusy,PendingInterrupt,UnsuitableEqmState,ActNotAssociated,HoldForReload,OutOfMemory,RCMACTOutOfSync,ChildActCreateWarn,ChildActIsInvalid,ChildActCreateFail,ChildActNotAvailable,ChildActCloning,Delayed,ConfMrAndNoAct,ChildHasActiviy,UnitInvalid,IntegrityError,DelayBySystem,ExecStsFromChild,Instruction,UnitNotSelected,MROnly,AssocEntErr,ExecObjErr,RefNotAssigned,SubstitutedValues,ChildInActive,UnitBeingAcquired,CreatePending,Ok,UnknownError,ConstExprRem,LossOfPrecsn,UnexpctEnd,UnexpctComma,ColonWoQMark,FctNotMltArg,ClosParenExp,OperandExp,MissingArg,OperatorExp,ColonExp,TypeMismatch,TypeNotSupp,SyntaxError,ExprTooCmplx,NotEPcodeMem,NotEDataStak,UnsuppFeatur,ExprTooLong,DivideByZero,UnknownToken,UnexpTokenOS,UnknownFunc,UnexpOCExpr2,UnexpOCExpr3,ZeroArgument,UnexpToken,InvalResult,InvalTokenTb,IntegerExp,DoubleExp,MissedImpl,UnicodeConv,ImplicitConv,DuplExprRem,ExtUse38,ExtUse39,ExtUse40,ExtUse41,ExtUse42,ExtUse43,ExtUse44,ExtUse45,ExtUse46,ExtUse47,ExtUse48,ExtUse49,ExtUse50,UnSupConType,UnExpClsParn,CantAssRVal,UnExpArrOpen,ArrClsExpect,ArrOpnExpect,ArrIndxError,StringExpect,InvalidRefer,TooManyConns,CantConvInpt,FctExpParen,AsgnOpLimExc,AsgnOperMiss,NullExprErr,StrRefNotSup,CantFtchConn,ComplexLHS,NullExprWarn,ExtUse70,RemoteFetchPending,RemoteFetchDisabled,DataNotEnabled,WCTUnknown,DynPeerMemError,RefdParamNotLoaded,InvalidRefToParam,StringSizeExceeded,Def=)
String_K(EXECDESC,"SCM ExecCode Description",39*4)
Boolean(EXECIDOPT,"Enable ExecutionID Processing",false)
Integer(EXECNAME,"Execution Name")
Enumeration(EXECSTATE,"Execution State",INACTIVE,ACTIVE,Def=)
*/
/*Real(EXECSTSFAILTM,"Execution Status Fail Filter Time")
Enumeration(EXECUTIONMODE,"reserved for future use",ProcedureExecution,DeviceExecution,Def=)*/
Struct_BEI(FAILALM,FL,ALPRIOR,PR,SV)
/*STRUCT(FAILALM)
  FLAG_S(FAILALM,FL,"SCM Fail Alarm Flag")
  ENUM_S(FAILALM,PR,"SCM Fail Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(FAILALM,SV,"SCM Fail Alarm Severity")
STRUCT_END(FAILALM)*/

/*Boolean(FREEFL,"Resource Is Unused",false)
Boolean(FULLFL,"Resource Is Not Available",false)
Boolean(GENERATEALERTS,"Generate Alerts",false)
STRUCT(GROUP)
  INTEGER_SA(GROUP,NUMBER,25,"Group Number")
  INTEGER_S(GROUP,NUMPARAMS,"Number of Group parameters")
STRUCT_END(GROUP)*/
/*STRUCT(HIALM)
  ENUM_S(HIALM,PR,"High Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(HIALM,SV,"High Alarm Severity")
  ENUM_S(HIALM,TYPE,"High Alarm Flag",NONE,Fail,Abort,Stop,Hold,Step,Def=)
STRUCT_END(HIALM)*/
/*STRUCT(HIST)
  FLAG_SA(HIST,EXC,25,"Exception Collection Type")
  INTEGER_SA(HIST,EXCCOLLRATE,25,"Collection Rate for Exception History Collection Type")
  INTEGER_SA(HIST,EXCOFFSET,25,"Collection Rate Offset for Exception History Collection Type")
  FLAG_SA(HIST,EXTD,25,"Extended Collection Type")
  FLAG_SA(HIST,FAST,25,"Fast Collection Type")
  INTEGER_SA(HIST,FASTCOLLRATE,25,"Collection Rate for Fast History Collection Type")
  STRING_SA(HIST,GATESTRING,25,255,"Gating Parameter String")
  STRING_SA(HIST,GATEVALUE,25,255,"Gating Parameter value")
  INTEGER_S(HIST,NUMPARAMS,"Number of History parameters")
  FLAG_SA(HIST,STD,25,"Standard Collection Type")
  INTEGER_SA(HIST,STDCOLLRATE,25,"Collection Rate for Standard History Collection Type")
  INTEGER_SA(HIST,STDOFFSET,25,"Collection Rate Offset for Standard History Collection Type")
  STRING_SA(HIST,TYPE,25,255,"History Type")
STRUCT_END(HIST)
String_A(HISTDESC,"History Parameter Descriptor",63*4,50)
String_A(HISTEUDESC,"History Parameter Engineering Units",64*4,50)
String_A(HISTTYPE,"History Parameter Type",11*4,50)
Real_A(HISTVALUE,"History Parameter Value",50)
Real_A(HISTVALUEMAX,"History Parameter Value Maximum",50)
Real_A(HISTVALUEMIN,"History Parameter Value Minimum",50)*/
Struct_BEI(HOLDALM,FL,ALPRIOR,PR,SV)
/*STRUCT(HOLDALM)
  FLAG_S(HOLDALM,FL,"SCM Hold Alarm Flag")
  ENUM_S(HOLDALM,PR,"SCM Hold Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(HOLDALM,SV,"SCM Hold Alarm Severity")
STRUCT_END(HOLDALM)*/
/*String_K(IMAGEVER,"Image Version",31*4)
Boolean(INALM,"FB In-Alarm Flag",false)
Integer(INSERTINDEX,"# of Blocks Ever Inserted")
Boolean(INSTRUCTPEND,"SCM Instruction Pending",false)
Integer(INSTSELECT,"Instance selection")
Integer_A(INVCOND,"Invoke Cond Number",8)
Integer_A(INVFRMHNDLER,"Invoke FromLoc Handler",8)
Integer_A(INVFRMHNDLRN,"Invoke FromLoc Handler-Num",8)
Integer_A(INVFRMHNDTYP,"Invoke FromLoc Hnd Type",8)
Integer_A(INVFROMSTEP,"Invoke FromLoc Step",8)
Integer_A(INVFROMSTEPN,"Invoke FromLoc Step-Num",8)
Enumeration_A(INVREASON,"Invoke Reason",8,Unknown,Command,LocalCond,GlobalCond,EqmToRecProjection,CommandByPhase,Def=)
Integer_A(INVTHREAD,"Invoke Thread Number",8)
Integer_A(INVTIME,"Invoke Time of Handler",8)
Enumeration(IOSCHEDOPT,"I/O Schedule Option",NotIOM,OutputModule,MixedModule,InputModule,Def=)*/
Boolean(JOURNALONLY,"Alarming JOURNAL ONLY",false)
/*Boolean(JUMPSAFEENB,"Jump safe Enable option",false)
String_K(KEYWORD,"Keyword Description",16*4)
Integer(LOADID,"ERDB / Controller load consistency ID")*/
Enumeration(LOADSTATE,"Load State",LOADFAILED,UNLOADED,LOADINGPROG,LDNGCMPTYPES,CMLOADINGTBR,LOADINGCONFG,LOADINGCONN,READY,LOADINGOUTSIDEOPAQUE,Def=UNLOADED)
/*Enumeration(LOOKAHEAD,"Look-Ahead Algorithm",NONE,SIMPLE,FULL,BKG_FULL,Def=)
Integer(MAXOWNERS,"Maximum Granted Requesters")
Integer(MAXRESOURCES,"max. Number of allocatable Resources")
Enumeration(MODE,"SCM Mode",NONE,AUTO,SEMIAUTO,SINGLESTEP,MANUAL,NORMAL,SAFESTEP,Def=)
Enumeration(MODEATTR,"SCM Mode Attribute",NONE,OPERATOR,PROGRAM,NORMAL,Def=)
Enumeration(MODETRACK,"Mode Tracking Option",NONE,ONESHOT,CONTRTN,SEMICONT,CONT,Def=)
Integer(NAME,"Provide the name for tagged objects")
Enumeration(NORMMODE,"SCM Normal Mode",NONE,AUTO,SEMIAUTO,SINGLESTEP,MANUAL,NORMAL,SAFESTEP,Def=)
Enumeration(NORMMODEATTR,"SCM Normal Mode Attribute",NONE,OPERATOR,PROGRAM,NORMAL,Def=)
Boolean(NOWAITINGFL,"No Waiting Requests",false)*/
/*Integer(NUM,"Internal Handle")
Integer(NUMADJPARAMS,"Number of adjustable formula parameter")
Integer(NUMADJRPARAMS,"Number of adjustable report parameter")
Integer(NUMALIASES,"Number of aliases")
Integer(NUMASSOCACT,"Number of Activities Associated with the RCM/SCM")
Integer(NUMBLOBS,"Number of Dynamic State Blobs")
Integer(NUMBLOCKS,"Number of Blocks (real count without holes)")
Integer(NUMCOMPFB,"Number of Component FB's")
Integer(NUMHANDLERS,"Number of Handlers")
Integer(NUMHISTPARMS,"Number of History Parameters")
Integer(NUMINSTANCES,"Number of instances")
Integer(NUMOWNERS,"Number of Granted Requesters")
Integer(NUMPARALLEL,"Number of Parallel Threads")
Integer(NUMPHASES,"Number of Phases")
Integer(NUMRECPARMS,"Number of Recipe Parameters")
Integer(NUMREQUESTR,"Number of internal Requesters used")
Enumeration(NUMSIGS,"Electronic Signature Type",NONE,SINGLE,DOUBLE,Def=)*/
Integer(NUMSTEPS,"Number of Steps",0)
/*Integer(NUMSYNCS,"Number of Syncs")
Integer(NUMTHREADS,"Current Numberof Threads")*/
Integer(NUMTRANS,"Number of Transitions",0)
/*Integer(NUMWAITING,"Number of Waiting Requesters")
Enumeration(OCDEXECSTATE,"CheckPointed Execution State",INACTIVE,ACTIVE,Def=)
Integer(ORDERINCEE,"Execution Order in CEE")
Integer(ORDERINCM,"Execution Order in CM")
Integer_A(OWNERID,"Name of Owner Block",5)
Integer_A(OWNERIDN,"Shows current owner, Identification of requester",5)
String_A(OWNERLOOKUP,"ClusterID, EEC and IOC of Owner Block",20*4,5)
Boolean(PARAMINIT,"ParamInit Option",false)
String_A(PARAMNAME,"Formula Parameter Name",80*4,500)
String_K(PARENTASSET,"Parent Asset:",132*4)
Boolean(PAUSEFL,"Pause Flag",false)
String_K(PCMNAME,"Platform block name",16*4)
Real(PEERAGETIME,"Peer Age Time [sec]")
Enumeration(PEERALGOPT,"Peer Algorithm Option",None,Auto,Max,50_Percent,33_Percent,25_Percent,20_Percent,10_Percent,Def=)
Integer(PEERALIASENB,"No. Enabled Peers in AliasTable")
Integer(PEERALIASNUM,"No. Peer Conns in AliasTable")
Integer(PEERINPUTENB,"No. Enabled Peers in SCM")
Integer(PEERINPUTNUM,"No. Peer Conns in SCM")*/
Enumeration(PERIOD,"Execution Period",DEFAULT,_5mS,_10mS,_20mS,_50mS,_100mS,_200mS,_500mS,_1sec,_2sec,_5sec,_10sec,_20sec,_25mS,NONE,_30sec,_1min,_2min,_5min,_10min,_20min,_30min,_1hr,_2hr,_4hr,_8hr,_12hr,_24hr,_40mS,_400mS,_80mS,_800mS,Def=DEFAULT)
String_K(PERIODENUMMASK,"Execution Period Enumeration Mask",64*4)
Real(PERIODSEC,"Execution Period in Seconds",-1)
Integer(PHASE,"Execution Phase",0)
Integer(PHASEHOUR,"Execution Phase Hour",-1)
Integer(PHASEMIN,"Execution Phase Minute",-1)
/*String_A(PHASENAME,"Phase Name of Formula parameter",80*4,500)
Enumeration(PREVLOADSTAT,"Previous value of LOADSTATE",LOADFAILED,UNLOADED,LOADINGPROG,LDNGCMPTYPES,CMLOADINGTBR,LOADINGCONFG,LOADINGCONN,READY,LOADINGOUTSIDEOPAQUE,Def=)
String_K(PRIMARYSIG,"Primary Signature Meaning",24*4)
Enumeration(PROCEDURALLEVEL,"Procedural Level",None,Phase,UnitOp,UnitProcedure,Procedure,Batch,Def=)
Boolean(PROGLOCKED,"ModeAttr Program is locked",false)
String_K(PUBLICNAME,"RCM/SCM Public Name",80*4)
String_K(QUALSTATE,"Qualification State",100*4)
Boolean(QUEUEFULLFL,"Waiting Queue is full",false)
Integer_A(QUEUEID,"Name of Requesting Block",10)
Integer_A(QUEUEIDN,"Shows current queue,Identification of requester",10)
String_A(QUEUELOOKUP,"ClusterID, EEC and IOC of Requesting Block",20*4,10)
Integer(QUEUESIZE,"Maximum Waiting Requesters")
Integer(REASONSET,"Reason Set Number")
String_A(RECDESC,"Recipe Parameter Descriptor",23*4,50)
String_A(RECEUDESC,"Recipe Parameter Engineering Units",64*4,50)
Enumeration(RECLIMITOPT,"Recipe Target Exceed Limits Option",REJECTANDERROR,CLAMPANDWARN,Def=)
Integer_A(RECMATCODE,"Recipe Parameter Material Code",50)
Boolean_A(RECSCALE,"Recipe Parameter Scale Allowed Option",50)
Real_A(RECTARGET,"Recipe Parameter Target Value",50)
Real_A(RECTARGETMAX,"Recipe Parameter Target Value Maximum",50)
Real_A(RECTARGETMIN,"Recipe Parameter Target Value Minimum",50)
Enumeration(REEXECOPT,"Step Re-execution Option",ReExecute,Continue,FollowContainer,FollowConfig,Def=)
Enumeration(REEXECPOLICY,"Step Re-execution Policy",AlwaysReExecute,Flexible,Def=)
STRUCT(REQ)
  ENUM_SA(REQ,ACQSTATE,200,"Acqisition state",200,NONE,ACQUIRING,ACQUIRED,RELEASING,ERROR,WARNING,Def=)
  INTEGER_SA(REQ,CMDREQSTS,200,"Resource command store Status")
  INTEGER_SA(REQ,EQUIPNAME,200,"Name of the resource to be acquired")
  INTEGER_SA(REQ,OWNERSSTS,200,"Resource Owners Get Status")
  FLAG_SA(REQ,OWNFL,200,"Ownership flag")
  FLAG_SA(REQ,RELFL,200,"Release resource input")
  FLAG_SA(REQ,REQFL,200,"Request resource input")
  INTEGER_SA(REQ,USECNT,200,"Requester usage count (diagnostic)")
STRUCT_END(REQ)
Integer(REQORDER,"Resource request order")
Integer_A(RESADDR,"Resume Address",15)
Integer_A(RESADDRFUTRN,"Resume Address Future-Num",15)
Integer_A(RESADDRFUTUR,"Resume Address Future",15)
Integer_A(RESADDRN,"Resume Address Number",15)
Enumeration(RESTART,"Last Restart Type",NONE,CMLOAD,CMACTIVE,CEECOLD,CEEWARM,CEESWITCH,Def=)
Boolean(RETAINISTS,"Retain Instruction Status",false)
Enumeration(RETRYOPT,"Retry Option",Default,Retry0,Retry1,Retry3,Retry10,Def=)
Boolean(RLSRESABNORM,"Release Resource After Abnormal  Termination",false)
Boolean(RLSRESNORM,"Release Resource After Normal  Termination",false)
String_K(ROLE,"Role",16*4)
String_A(RPARAMNAME,"Reporting Parameter Name",80*4,500)
String_A(RPHASENAME,"Phase Name of report parameter",80*4,500)
Boolean(RSTPROCESSED,"Reset Processed Command",false)
STRUCT(RTABLE)
  INTEGER_SA(RTABLE,DIAG,5000,"R-Table: Diagnostic Bits")
  INTEGER_SA(RTABLE,INTTIME,5000,"R-Table: Age of internal Request [sec]")
  INTEGER_SA(RTABLE,PART,5000,"R-Table: Step/Transition")
  INTEGER_SA(RTABLE,PARTN,5000,"R-Table: Step/Trans Number")
  INTEGER_SA(RTABLE,PEER,5000,"R-Table: No. of Peer Conns")
  INTEGER_SA(RTABLE,STATE,5000,"R-Table: EnableGetRequest State")
  INTEGER_SA(RTABLE,TIME,5000,"R-Table: Age of Part [sec]")
STRUCT_END(RTABLE)
Integer(RTABLENROWS,"No of R-Table Rows")
Integer(RTABLEUROWS,"No of R-Table Used Rows")
Real(SCALEPERIOD,"Scale Period")
String_K(SCANAREA,"SCAN Area",40*4)
String_K(SCANASSOCDSP,"SCAN Associated Display",255*4)
Integer(SCANCTRLLVL,"SCAN Control Level")
String_K(SCANEUHI,"SCAN EUHI Parameter",255*4)
String_K(SCANEULO,"SCAN EULO Parameter",255*4)
String_K(SCANGRPDTL,"SCAN Group Detail Page",255*4)
String_K(SCANPNTDTL,"SCAN Point Detail Page",255*4)
Boolean_A(SCHEDCYCLE,"Scheduled Cycle",120)
Integer(SCHEDPOS,"Position in scheduler chain (internal use)")
String_K(SECONDARYSIG,"Secondary Signature Meaning",24*4)
Enumeration(SECSIGSECLVL,"Sec Signer Security Level",VIEWONLY,ACKONLY,OPER,SUPV,ENGR,MNGR,Def=)
Integer_A(SELHANDLER,"Select Hndlr Instance",8)
Integer_A(SELHANDLERN,"Select Hndlr Instance-Num",8)
Enumeration(SIMSTATE,"Simulation State",NONE,SIMRUN,SIMFREEZE,SIMDISABLE,Def=)
Enumeration(SSTEPLOCK,"SCM Single Step Access Lock",OPERATOR,ENGINEER,VIEWONLY,OTHERFB,SUPERVISOR,Def=)
*/
Struct_BEI(STEPALM,FL,ALPRIOR,PR,SV)
/*STRUCT(STEPALM)
  FLAG_S(STEPALM,FL,"SCM Step Alarm Flag")
  ENUM_S(STEPALM,PR,"SCM Step Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(STEPALM,SV,"SCM Step Alarm Severity")
STRUCT_END(STEPALM)*/
Struct_BEI(STOPALM,FL,ALPRIOR,PR,SV)
/*STRUCT(STOPALM)
  FLAG_S(STOPALM,FL,"SCM Stop Alarm Flag")
  ENUM_S(STOPALM,PR,"SCM Stop Alarm Priority",NONE,JOURNAL,LOW,HIGH,URGENT,Def=)
  INTEGER_S(STOPALM,SV,"SCM Stop Alarm Severity")
STRUCT_END(STOPALM)*/
Enumeration(STOPSTATEOPT,"STOPPED state option",NotTerminal,Terminal,Def=NotTerminal)
Integer_A(TARGETSTEP,"Target Step",15,0)
Integer_A(TARGETSTEPN,"Target Step Number",15,0)
/*Real(TGTRNGDEF,"Recipe Default Target Range")
Boolean(TGTRNGDEFOPT,"Recipe Default Target Range Option",false)
Integer_A(TIME,"Current Time in Handler",8)
STRUCT(TREND)
  INTEGER_SA(TREND,NUMBER,32,"Trend Number")
  INTEGER_S(TREND,NUMPARAMS,"Number of Trend parameters")
  ENUM_SA(TREND,POSITION,32,"Trend Position",32,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,None,Def=)
STRUCT_END(TREND)
Boolean(TYPEIDENTIFIER,"Sequence Type (SCM or RCM )",false)*/
String_K(UNITTEXT,"Unit Text",2*4)
/*Boolean(USEDFL,"Resource Is Used",false)
Boolean(WAITINGFL,"Some Waiting Requests",false)
Integer(X_BLOCKMEM,"Currently used memory (bytes)")
Integer(X_DATAINITBLOCK,"Data Init Block")
Enumeration(X_NOTIF_ID,"Alarm condition strings",DO NOT USE,FAIL,STEPTO,HOLD,STOP,ABORT,Def=)
*/