Integer(ASACONNSTS,"Connection Status",0x4000)
Integer(ASAERRCODE,"Error Code",0)
Real_A(AV,"Accumulated Value",8,0)
Integer_A(AVRAW,"Raw Accumulated Value",8,0)
Enumeration(CEESTATE,"CEE State",IDLE,RUN,FAIL,NotLoaded,Def=IDLE)
Enumeration(EXECSTATE,"Execution State",INACTIVE,ACTIVE,Def=INACTIVE)
Boolean(INALM,"In-Alarm Boolean",0)
Enumeration(IOCONNSTATUS,"IO Connection Status",BadSchedule,CommError,ConfigError,Connected,ConnInUse,IomNotFound,NoConfig,NoKeeper,NoSchedule,NotConnected,WrongModule,unknown,Def=unknown)
Enumeration(IOMSTATE,"IOM State",INACTIVE,OK,FAIL,STBY,START,STUB,Def=INACTIVE)
Real_A(PL,"Pulse Length",6,0)
Real_A(PV,"Process Value",8,0)
Boolean_A(RESETFL,"Reset Counter Boolean",8,0)
Boolean_A(SO,"Output State",2,0)
Real_A(TV,"Target Value",2,0)
Boolean_A(TVPROC,"TV Processing",2,0)
Integer_A(TVRAW,"Raw Target Value",2,0)
Enumeration_A(VOLTAGE,"Voltage Threshold",8,Low,High,Def=Low)
Enumeration_A(IOCCONN,"Currently Assigned Channels",8,INCONN,OUTCONN,PCONN,Def=INCONN)
