[Station]
;Check # 56. Invoking a slow Chart Monitoring or slow ActiveX control
KreepyKrawlyCycle=30000
;Legacy alarm indication on status window
AlarmBarFullHighlighting=1
AllowRightClickBrowserMenus=0
DisableDirectoryRecursion=1
DisableEchoSafeBrowseMessage=1
DisableMaximizeButton=0
DisableMenuMnemonic=0
FixedWindowSize=0
FlashWindowOnAlarm=0
helpOperator=DocumentationSet.htm
HighPriority=0
MessageFontSize=10
MessageFontStyle=1
USKeyboardPort=3
UseHandIconOnButton=1
WindowsNavigation=0
WindowsObjects=1
DSPZoomingAllowed=1
LightWeightWindowsInSWMode=4
URLsToLoadInSameWindow=
ApplicationLookAndFeel=NewTheme
NewVisual=1
MessageCommandZoneBgColor=#555555

; Use the following commands for fast Station failover.
; Refer to documentation and readme for information on configuring fast Station failover.
;KeepAliveTimeout=30
;DisConnectTimeout=30

[Video Overlay]
alias=HLA_Overlay
capture_file=overlay.bmp

; Use the following commands for Integral Technologies FlashPoint
;
;set_frame=0
;set_source=0
;set_fixed=0
; If you want the live video to be copied to the windows clipboard.
;clipboard_command1=copy HLA_Overlay
; and if you want the live video to be copied to the file overlay.bmp as a RLE bit map.
;clipboard_command2=save HLA_Overlay overlay.bmp depth 24
MaximumWidth=580
MaximumHeight=435

; Use the following commands for Creative Labs Video Blaster
;
;set_frame=1
;set_source=1
;set_fixed=0
;clipboard_command1=save HLA_Overlay overlay.bmp type 1

; Use the following commands for FAST Screen Machine II or Movie Machine
;
;set_frame=0
;set_source=0
;set_fixed=0
; If you want the live video to be copied to the windows clipboard.
;clipboard_command1=save HLA_Overlay <clipboard> with -d8r
; or if you want the live video to be copied to the file overlay.bmp as a RLE bit map.
;clipboard_command1=save HLA_Overlay overlay.bmp with -d8r
; or if you want the live video to be copied to the the file overlay.tga as a TGA file.
;clipboard_command1=save HLA_Overlay overlay.tga with -a24

[Application Keys]
; The following application key assignments are used for camera control

;Keypad 1 - pan left tilt down
Key79DownLRN=98
Key79DownPAR1=2
Key79DownPAR2=17
Key79UpLRN=98
Key79UpPAR1=2
Key79UpPAR2=20

;Keypad 2 - tilt down
Key80DownLRN=98
Key80DownPAR1=2
Key80DownPAR2=5
Key80UpLRN=98
Key80UpPAR1=2
Key80UpPAR2=4

;Keypad 3 - pan right tilt down
Key81DownLRN=98
Key81DownPAR1=2
Key81DownPAR2=19
Key81UpLRN=98
Key81UpPAR1=2
Key81UpPAR2=20

;Keypad 4 - pan left
Key75DownLRN=98
Key75DownPAR1=2
Key75DownPAR2=3
Key75UpLRN=98
Key75UpPAR1=2
Key75UpPAR2=1

;Keypad 5 - no functionality

;Keypad 6 - pan right
Key77DownLRN=98
Key77DownPAR1=2
Key77DownPAR2=2
Key77UpLRN=98
Key77UpPAR1=2
Key77UpPAR2=1

;Keypad 7 - pan left tilt up
Key71DownLRN=98
Key71DownPAR1=2
Key71DownPAR2=16
Key71UpLRN=98
Key71UpPAR1=2
Key71UpPAR2=20

;Keypad 8 - tilt up
Key72DownLRN=98
Key72DownPAR1=2
Key72DownPAR2=6
Key72UpLRN=98
Key72UpPAR1=2
Key72UpPAR2=4

;Keypad 9 - pan right tilt up
Key73DownLRN=98
Key73DownPAR1=2
Key73DownPAR2=18
Key73UpLRN=98
Key73UpPAR1=2
Key73UpPAR2=20

;Keypad / - zoom in
Key53DownLRN=98
Key53DownPAR1=2
Key53DownPAR2=8
Key53UpLRN=98
Key53UpPAR1=2
Key53UpPAR2=7

;Keypad * - zoom out
Key55DownLRN=98
Key55DownPAR1=2
Key55DownPAR2=9
Key55UpLRN=98
Key55UpPAR1=2
Key55UpPAR2=7

;Keypad - - focus near
Key74DownLRN=98
Key74DownPAR1=2
Key74DownPAR2=14
Key74UpLRN=98
Key74UpPAR1=2
Key74UpPAR2=13

;Keypad + - focus far
Key78DownLRN=98
Key78DownPAR1=2
Key78DownPAR2=15
Key78UpLRN=98
Key78UpPAR1=2
Key78UpPAR2=13

[UseHTMLPrinting]
Display0=sysOrphanActivitySummary.htm
Display1=sysSystemSummary.htm
Display2=sysActivitySummary.htm
Display3=sysBatchSummary.htm
Display4=sysProcedureSummary.htm
Display5=sysAlertSummary.htm
Display6=sysEventSummary.htm
Display7=sysMessageSummary.htm
Display8=sysSOESummary.htm
Display9=sysAlarmSummary.htm