// Generated by CoffeeScript 1.12.6
(function() {
  var hmiwebJsBasePath;

  hmiwebJsBasePath = window.external.FrameworkServices.HMIWebJSBasePath;

  if (!hmiwebJsBasePath) {
    throw new Error('Cannot find HMIWebJS base path');
  }

  require.config({
    baseUrl: hmiwebJsBasePath
  });

  require(['asari/requireConfig'], function() {
    return require(['asari/EquipmentApp'], function(EquipmentApp) {
      var app;
      app = new EquipmentApp();
      return app.run();
    });
  });

}).call(this);
