; Lists the Script Data methods for validation
[ScriptData]
AlarmSeverity  = 1
DataAlarm = 1
DataChanged = 1
DataExists = 1
DataQuality = 1
DataValue = 1
InAlarm = 1
IsNaN = 1
IsElementNaN = 1
QualityBad = 1
QualityConfigError = 1
QualityDeviceFailure = 1
QualityGood = 1
QualityLastKnown = 1
QualityNonSpecific = 1
QualityOutOfService = 1
SetDataValueSynchronous = 1
SetDataValueSynchronouslyWithSecurityLevel = 1
SetDataValueWithSecurityLevel = 1
UnacknowledgedAlarm = 1